:FRAGMENT_RELATIVE_DIR: ../../../
include::../../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../../

[[core-config-annotations-section]]
===== Configuration Using Java Annotations.

To override the default value, the RxMicro framework provides the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/DefaultConfigValue.java[`@DefaultConfigValue`^] annotation.

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/config-annotations/src/main/java/module-info.java[tag=content,indent=0]
----

<1> When overriding the configuration value, You must specify the configuration class.
<2> If the configuration class is specified, the namespace may not be specified. +
_(It means the field of the specified configuration class.)_
<3> If no configuration class is specified, the name *must* contain a namespace. +
_(The namespace allows You to clearly define to which configuration class the specified setting belongs.)_
<4> When configuring a microservice project, the annotation must be specified on the `module-info.java` descriptor. +
_(A microservice project may contain several classes of REST controllers, so the common settings are configured using the `module-info.java` descriptor rather than the REST controller class.)_

[WARNING]
====
*Please, pay attention when overriding the default value with the annotations!*

If You make a mistake when specifying a setting name (this refers to the namespace and field name), no error will occur upon starting!
The overridden value will be simply *ignored*!
====

By overriding the default values using the `module-info.java` descriptor, You can start the microservice.
While reading the configuration of the `HttpServerConfig` class, the RxMicro framework reads the default values set with annotations:

[source,text]
----
2020-01-13 13:09:44.236 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at localhost:9090 using NETTY transport in 500 millis. # <1>
----

<1>  HTTP server started on `localhost:9090`

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-common/config-annotations
include::../../../___notes/full-source-code-of-example.adoc[]

[IMPORTANT]
====
The main difference between configuring with annotations and configuring with Java classes is support of the *settings inheritance and overriding*.

In other words, when using configuration via annotations, the RxMicro framework can also read other configuration sources.

When using configuration via Java classes, other configuration sources *are always ignored*.
====

[NOTE]
====
For the test environment only, the RxMicro framework provides special <<{testing}#testing-annotations-WithConfig-inline,`@WithConfig`>> annotation.
Using this annotation it is convenient to configure the configuration manager for the test environment:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-microservice-with-config/src/test/java/io/rxmicro/examples/testing/microservice/with/config/MicroServiceTest.java[tags=WithConfig,indent=0]
----

The source code of the project using the <<{testing}#testing-annotations-WithConfig-inline,`@WithConfig`>> annotation is available at the following link:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-microservice-with-config[`https://github.com/rxmicro/rxmicro-usage/tree/master/examples/testing-microservice-with-config`^]
====

{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/DefaultConfigValue.java[`@DefaultConfigValue`^]
annotation can be applied to override primitive values only:

* `strings`,
* `booleans`,
* `numbers`,
* `dates`,
* `times`,
* `enums`.

If You need to override a complex value, it is necessary to use
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/DefaultConfigValueSupplier.java[`@DefaultConfigValueSupplier`^]
annotation instead.

[TIP]
====
The source code of the project using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/DefaultConfigValueSupplier.java[`@DefaultConfigValueSupplier`^]
annotation is available at the following link:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-common/config-annotations-supplier[`https://github.com/rxmicro/rxmicro-usage/tree/master/examples/config-annotations-supplier`^]
====

include::../../../___notes/recompile-after-change.adoc[]
