:FRAGMENT_RELATIVE_DIR: ../../../
include::../../../___fragment-settings.adoc[]

===== Configuration Using `classpath` Resources.

The RxMicro framework supports shared and separate classpath resources for the external configuration in relation to the microservice source code.

The only supported classpath resource format is the `properties` file format.

====== Configuration Using Separate `classpath` Resource.

If the classpath of the current project contains the `http-server.properties` resource with the following content:

[source,properties]
----
port=9090 # <1>
----
<1> Custom port for HTTP server.

then the RxMicro framework when reading the `HttpServerConfig` class configuration will read this resource:

[source,text]
----
2020-01-11 12:44:27.518 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at 0.0.0.0:9090 using NETTY transport in 500 millis. # <1>
----
<1> The HTTP server has started at the `9090` port instead of the standard `8080` port.

include::___tip-namespace.adoc[]

====== Configuration Using Shared `classpath` Resource.

If the classpath of the current project contains the `rxmicro.properties` resource with the following content:

[source,properties]
----
http-server.port=9090 # <1>
----
<1> Custom port for HTTP server.

then the RxMicro framework when reading the `HttpServerConfig` class configuration will read this resource:

[source,text]
----
2020-01-11 12:44:27.518 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at 0.0.0.0:9090 using NETTY transport in 500 millis. # <1>
----
<1> The HTTP server has started at the `9090` port instead of the standard `8080` port.

include::___tip-rxmicro-resource.adoc[]

Since the `rxmicro.properties` resource is a shared resource for *any* configuration, You must specify a namespace when specifying the settings.

include::___note-common-and-special-resource-difference.adoc[]
