:FRAGMENT_RELATIVE_DIR: ../../../
include::../../../___fragment-settings.adoc[]

===== Configuration Using Environment Variables.

When using environment variables, the format of configurations matches the following format:

`export ${name-space}.${property-name} = ${value}`:

[source,text,subs="verbatim,quotes"]
----
*export* http-server.port=9090 # <1>

*java* -p ./classes:lib -m *examples.quick.start/io.rxmicro.examples.quick.start.HelloWorldMicroService*
2020-01-02 18:49:58.372 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at 0.0.0.0:9090 using NETTY transport in 500 millis. # <2>
----

<1> Setting the `http-server.port` environment variable = 9090 (custom port for HTTP server).
<2> The HTTP server has started at the `9090` port instead of the standard `8080` port.

[TIP]
====
Thus, the format of configurations using environment variables corresponds to the format of `rxmicro.properties` file or classpath resource.
====

*Configuring with environment variables is very convenient when using https://www.docker.com/[docker^] containers!*

[IMPORTANT]
====
To protect Your secret data, use configuration via properties files instead of environment variables.
The config directory with secret config files (for example `$HOME/.rxmicro/`) must be mount as external volume using https://en.wikipedia.org/wiki/Tmpfs[`tmpfs`^] file system.
====