:FRAGMENT_RELATIVE_DIR: ../../../
include::../../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../../

[[core-config-properties-files-section]]
===== Configuration Using `properties` Files.

Similar to classpath resources, the RxMicro framework also supports shared and separate `properties` files for the external configuration in relation to the microservice source code.

Configuration files can be located:

* in the current directory in relation to the microservice;
* in the `$HOME` directory:
** for Linux platform the `$HOME` directory is `/home/$USERNAME`;
** for MacOS platform the `$HOME` directory is `/Users/$USERNAME`;
** for Windows platform the `$HOME` directory is `C:\Documents and Settings\%USERNAME%` or `C:\Users\%USERNAME%`.
* in the default rxmicro config directory: `$HOME/.rxmicro/` (predefined name and location). +
_(Using `$HOME/.rxmicro/` directory instead of `$HOME` one allows configuring this directory as https://www.docker.com/[docker^] or https://kubernetes.io/[kubernetes^] volume.)_

[TIP]
====
To find out the location of the `$HOME` directory on Your computer using Java, start the following program:

[source,java]
----
public final class GetHomeDirectory {

    public static void main(final String[] args) {
        System.out.println(System.getProperty("user.home"));
    }
}
----
====

*By default, the function of searching and reading configuration files is disabled in the RxMicro framework!*

To activate this function, You must use the `Configs.Builder` class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/config/all/Main.java[tag=content,indent=0]
----
<1> Activation of all available configuration sources for the current microservice.

[TIP]
====
Besides activating all available sources, it is possible to activate only configuration files in a given location.

For details on how to do this, go to the <<core-config-order-settings>>.
====

====== Configuration Using Separate `properties` File.

If the current directory (or `$HOME`, or `$HOME/.rxmicro/`) directory contains the `http-server.properties` file with the following content

[source,properties]
----
port=9090 # <1>
----
<1> Custom port for HTTP server.

then the RxMicro framework when reading the `HttpServerConfig` class configuration will read this file:

[source,text]
----
2020-01-11 12:44:27.518 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at 0.0.0.0:9090 using NETTY transport in 500 millis. # <1>
----
<1> The HTTP server has started at the `9090` port instead of the standard `8080` port.

include::___tip-namespace.adoc[]

====== Configuration Using Shared `properties` File.

If the current directory (or `$HOME`, or `$HOME/.rxmicro/`) directory contains the `rxmicro.properties` file with the following content

[source,properties]
----
http-server.port=9090 # <1>
----
<1> Custom port for HTTP server.

then the RxMicro framework when reading the `HttpServerConfig` class configuration will read this resource:

[source,text]
----
2020-01-11 12:44:27.518 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at 0.0.0.0:9090 using NETTY transport in 500 millis. # <1>
----
<1> The HTTP server has started at the `9090` port instead of the standard `8080` port.

include::___tip-rxmicro-resource.adoc[]

Since the `rxmicro.properties` file is a shared file for *any* configuration, You must specify a namespace when specifying the settings.

include::___note-common-and-special-resource-difference.adoc[]
