:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]
:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== HTTP Requests Server Validation

After activation of the `rxmicro.validation` module in the `module-info.java` descriptor

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-validation/validation-server-basic/src/main/java/module-info.java[tag=content,indent=0]
----
<1> `rxmicro.validation` is a module for request and response validation.

the developer can use <<validation-std-constraints-section, built-in constraints>> to validate HTTP request parameters:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-validation/validation-server-basic/src/main/java/io/rxmicro/examples/validation/server/basic/MicroService.java[tag=content,indent=0]
----
<1> The `email` parameter is annotated by the `@Email` annotation.

Due to this annotation the `RxMicro Annotation Processor` will automatically generate a validator for `email` HTTP parameter:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-validation/validation-server-basic/src/test/java/io/rxmicro/examples/validation/server/basic/MicroServiceTest.java[tag=content,indent=0]
----
<1> When activating the `rxmicro.validation` module, all query parameters are automatically considered as required. +
_(Therefore the `RxMicro Annotation Processor` automatically adds a `required` validator for each parameter.
If the parameter should be `optional`, the model field should be annotated with the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-validation/src/main/java/io/rxmicro/validation/constraint/Nullable.java[`@Nullable`^] annotation.)_
<2> If request parameters are invalid, HTTP server automatically returns a status code `400` and JSON object of <<{rest-controller}#rest-controller-errors-model-inline,standard structure with detailed error description.>>
<3> If an HTTP request validation error occurs, the request handler isn't invoked from the REST controller.
<4> If the request parameters are valid, control is transferred to the request handler from the REST controller.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-validation/validation-server-basic
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
