:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]
:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== HTTP Responses Client Validation

After activation of the `rxmicro.validation` module in the `module-info.java` descriptor

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-client-basic/src/main/java/module-info.java[tags=content]
----
<1> `rxmicro.validation` is a module for request and response validation.

the developer can use <<validation-std-constraints-section, built-in constraints>> to validate HTTP request parameters:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-client-basic/src/main/java/io/rxmicro/examples/validation/client/basic/model/Response.java[tags=content]
----
<1> The `email` parameter is annotated by the `@Email` annotation.

After setting up the model class, this model must be used in the REST client:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-client-basic/src/main/java/io/rxmicro/examples/validation/client/basic/RESTClient.java[tags=content]
----

When converting the content of an HTTP response to the `Response` class object, the validator will be invoked automatically:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-client-basic/src/test/java/io/rxmicro/examples/validation/client/basic/RESTClientTest.java[tags=content]
----
<1> If the REST client receives a valid HTTP response, no errors will occur.
<2> If the `email` field is incorrect in the HTTP response, the REST client will return an error signal.
<3> If the HTTP response is incorrect, the `UnexpectedResponseException` class exception is returned with a detailed text message.
<4> *Since `CompletableFuture` when receiving an error signal ALWAYS returns the `CompletionException` class exception, to get the original exception class, which was thrown during the lazy evaluation, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-common/src/main/java/io/rxmicro/common/util/Exceptions.java#L120[`Exceptions.getRealThrowable`^] utility method!*

[NOTE]
====
Check out the following example to find out the features of the RxMicro framework for HTTP request validation in REST clients:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}validation-client-all-types[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}validation-client-all-types`^]
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}validation-client-basic
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
