:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]
:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== Creating Custom Constraints

If built-in constraints are not enough, the developer can create custom constraint.
To do so, the following steps must be taken:

. Create a constraint annotation.
. Implement a validator.

A validation annotation is an annotation that meets the following requirements:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-custom/src/main/java/io/rxmicro/examples/validation/server/custom/ExpectedZero.java[tag=content,indent=0]
----
<1> The annotation is only available at the compilation level.
<2> This annotation allows to validate class fields, class methods (`setters` and `getters`) and method parameters.
<3> The
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-validation/src/main/java/io/rxmicro/validation/base/ConstraintRule.java[`@ConstraintRule`^] annotation is used to indicate:
<4> data type;
<5> validator class.
<6> Each constraint annotation requires a required `boolean off() default false;` parameter, that allows You to disable the validator. +
_(This feature is useful for model inheritance when a parameter from a child class should not be validated and a parameter from a parent class should be validated!)_

Validator is a class that meets the following requirements:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-custom/src/main/java/io/rxmicro/examples/validation/server/custom/ExpectedZeroConstraintValidator.java[tag=content,indent=0]
----
<1> The validator class must implement the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-validation/src/main/java/io/rxmicro/validation/ConstraintValidator.java[`ConstraintValidator`^] interface parameterized by the data type. +
_(If constraint annotation can be applied to different data types, a separate validator class must be created for each data type.)_
<2> Validator must ignore `null` values. +
_(To check for `null` there is a predefined validator.)_
<3> If the parameter is incorrect, the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/error/ValidationException.java[`ValidationException`^] exception with a clear error message must be thrown.

Using a custom validator is no different from using a predefined validator:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-custom/src/main/java/io/rxmicro/examples/validation/server/custom/MicroService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-custom/src/test/java/io/rxmicro/examples/validation/server/custom/MicroServiceTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}validation-server-custom
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
