:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]
:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[validation-disable-section]]
=== Disabling Validation

To disable the generation of validators, you must perform one of the following steps:

. Delete the `rxmicro.validation` module from the `module-info.java` descriptor.
. Use `GenerateOption.DISABLED` options to disable specific categories of validators.
. Use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-validation/src/main/java/io/rxmicro/validation/DisableValidation.java[`@DisableValidation`^]
annotation to disable validators of a selected group of classes in the project.

==== Removing the `rxmicro.validation` module

The easiest and fastest way to disable the generation of validators for *all* classes in the current module is to remove the `rxmicro.validation` module from the `module-info.java` descriptor.

[IMPORTANT]
====
*After deleting the `rxmicro.validation` module DON'T FORGET to recompile the whole project for the changes to take effect: `mvn clean compile`!*
====

==== Using `GenerateOption.DISABLED` Option

To disable the generation of validators by category, it is necessary to use annotations:

* <<{rest-controller}#rest-controller-rest-server-generator-config-section,`@RestServerGeneratorConfig`>> (to set up the REST controllers).
* <<{rest-client}#rest-client-rest-client-generator-config-section,`@RestClientGeneratorConfig`>> (to set up the REST clients).

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-all/src/main/java/module-info.java[tag=content,indent=0]
----
<1> Validators for all models of HTTP requests in the current project won't be generated.
<2> Validators for all models of HTTP responses in the current project won't be generated.
<3> Validators for all models of HTTP requests in the current project won't be generated.
<4> Validators for all models of HTTP responses in the current project won't be generated.

[IMPORTANT]
====
*Upon activation of the `rxmicro.validation` module, by default RxMicro generates only HTTP request validators for REST controllers and HTTP response validators for REST clients!*

All other categories of validators must be manually activated using the `@RestServerGeneratorConfig` and `@RestClientGeneratorConfig` annotations!
====

[IMPORTANT]
====
*After changing the settings using the `@RestServerGeneratorConfig` and `@RestClientGeneratorConfig` annotations DON'T FORGET to recompile the whole project for the changes to take effect: `mvn clean compile`!*
====

==== Using `@DisableValidation` Annotation

The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-validation/src/main/java/io/rxmicro/validation/DisableValidation.java[`@DisableValidation`^]
annotation provides an opportunity to disable the generation of validators for the selected group of classes in the project:

. If a model class is annotated by this annotation, then *only* for this model class the validator won't be generated.
. If this annotation annotates the `package-info.java` class, then for *all classes from the specified package and all its subpackages* no validators will be generated.
. If this annotation annotates the `module-info.java` descriptor, then for *all classes in the current module* no validators will be generated. +
_(This behavior is similar to the removal of the `rxmicro.validation` module from the `module-info.java` descriptor.)_

[IMPORTANT]
====
*After adding the `@DisableValidation` annotation DON'T FORGET to recompile the whole project for the changes to take effect: `mvn clean compile`!*
====
