:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[validation-response-section]]
=== HTTP Responses Server Validation

In addition to validating HTTP requests, the RxMicro framework also provides the option to validate HTTP responses.

_(HTTP response validation can be useful for identifying errors in business task implementation algorithms.
For example, instead of returning an incorrect response model to a client, the microservice will throw an error.
This approach increases the speed of error search and debugging of the source code that performs the business task.)_

[IMPORTANT]
====
If current implementation of the business task doesn't contain any errors, then HTTP response validation will consume computing resources senselessly.
In this case, HTTP response validation must be disabled!

*By default the response validators are generated but not invoked!*

To activate the validation of responses it is necessary to set `enableAdditionalValidations` property:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/rest_controller/ActivateResponseValidators.java[tags=content,indent=0]
----
<1> Enables the response validators
====

The HTTP response model class can contain any built-in or custom constraint annotations:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-validation/validation-server-response/src/main/java/io/rxmicro/examples/validation/server/response/model/Response.java[tag=content,indent=0]
----
<1> In this example, the `message` field doesn't explicitly contain any constraint annotations.
But since to the `module-info.java` descriptor was added the `rxmicro.validation` module, then all model fields not marked with the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-validation/src/main/java/io/rxmicro/validation/constraint/Nullable.java[`@Nullable`^] annotation are automatically required.
_(In other words, such fields are implicitly marked by a virtual constraint annotation `@Required`.)_

To emulate an incorrect business value, `null` value is passed in the request handler to the `message` field:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-validation/validation-server-response/src/main/java/io/rxmicro/examples/validation/server/response/MicroService.java[tag=content,indent=0]
----

In case of invalid HTTP response, the RxMicro framework returns HTTP response with a status `500` and <<{rest-controller}#rest-controller-errors-model-inline, standard error model>>:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-validation/validation-server-response/src/test/java/io/rxmicro/examples/validation/server/response/MicroServiceTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-validation/validation-server-response
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
