:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[java-integration-unnamed-module-module-config]]
==== Module Configuration

Some RxMicro modules allow You to set the common configuration with `RxMicro Annotations`, which annotate the `module-info.java` module descriptor.
But for the `unnamed module`, the `module-info.java` module descriptor does not exist!

In such cases a virtual descriptor must be created:

[source,java]
----
@Retention(SOURCE)
@Target({})
public @interface ModuleInfo {
}
----

A virtual descriptor is a custom annotation that meets the following requirements:

. The name of the virtual descriptor is fixed and equal to: `ModuleInfo`.
. The annotation must be contained in the default package (`unnamed package`).
. The annotation should be available only during the compilation process: `@Retention(SOURCE)`.
. The annotation must contain an empty list of targets: `@Target({})`.

[TIP]
====
Since the virtual descriptor is available only during the compilation process, then during the `uber.jar` build process this annotation can be excluded from the resulting `jar`.

Therefore, <<java-integration-unnamed-module-uber-jar-maven-shade-plugin,when setting the `maven-shade-plugin`, the following setting was added>>:

[source,xml]
----
<filters>
    <filter>
        <artifact>*:*</artifact>
        <excludes>
            <exclude>ModuleInfo.*</exclude>
        </excludes>
    </filter>
</filters>
----
====

===== Configuration of the Code Generation Process for Rest Controller

The RxMicro framework provides the option to configure the code generation process for REST controllers.
For this purpose, the `@RestServerGeneratorConfig` annotation should be used to annotate the
<<rest-controller#rest-controller-rest-server-generator-config-section,`module-info.java` module descriptor>>.

For the `unnamed module` instead of the `module-info.java` module descriptor, use the `ModuleInfo` annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-unnamed-module/unnamed-module-rest-controller-generator/src/main/java/ModuleInfo.java[tags=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}unnamed-module-rest-controller-generator
include::../../___notes/full-source-code-of-example.adoc[]

include::../../___notes/recompile-after-change.adoc[]

<<<

===== Configuration of the Code Generation Process for Rest Client

The RxMicro framework provides the option to configure the code generation process for REST clients.
For this purpose, the `@RestClientGeneratorConfig` annotation should be used to annotate the
<<rest-client#rest-client-rest-client-generator-config-section,`module-info.java` module descriptor>>.

For the `unnamed module` instead of the `module-info.java` module descriptor, use the `ModuleInfo` annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-unnamed-module/unnamed-module-rest-client-generator/src/main/java/ModuleInfo.java[tags=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}unnamed-module-rest-client-generator
include::../../___notes/full-source-code-of-example.adoc[]

include::../../___notes/recompile-after-change.adoc[]

<<<

===== REST-based Microservice Metadata Configuration

The RxMicro framework provides the option to configure the REST-based microservice documentation generation process, using the annotations.
These annotations annotate the <<project-documentation#project-documentation-metadata-annotations-section,`module-info.java` module descriptor>>.

For the `unnamed module` instead of the `module-info.java` module descriptor, use the `ModuleInfo` annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-unnamed-module/unnamed-module-documentation-asciidoctor-metadata-annotations/src/main/java/ModuleInfo.java[tags=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}unnamed-module-documentation-asciidoctor-metadata-annotations
include::../../___notes/full-source-code-of-example.adoc[]

include::../../___notes/recompile-after-change.adoc[]
