:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== Ambiguity Resolving

If there are two or more implementations of the same interface in the current project module, the problem of ambiguity resolving may arise in the process of dependencies injection.
In the field with the interface type potentially can be injected an implementation of any of the child classes of this interface, that's why such a problem occurs.

In order to solve such problems definitively, the RxMicro framework uses the ambiguity resolving algorithm by default.

==== Default Ambiguity Resolving

If there are two or more implementations of the same interface in the current project module, then the RxMicro framework implicitly sets the name for each implementation.
This name corresponds to a simple class name starting with a small letter, for example:

* For the `io.rxmicro.examples.cdi.ProductionBusinessService` class, the name is equal to `productionBusinessService`.
* For the `io.rxmicro.examples.cdi.DevelopmentBusinessService` class, the name is equal to `developmentBusinessService`.
* For the `io.rxmicro.ProductionBusinessService` class, the name is equal to `productionBusinessService`.
* For the `ProductionBusinessService` class, the name is equal to `productionBusinessService`.

[IMPORTANT]
====
The ambiguity resolving problem may occur *only between classes implementing the same interface!*.

This means that if there are two following interfaces in the project:

* `package1.BusinessService` and
* `package2.BusinessService`;

and four implementation classes:

* `package1.impl.ProductionBusinessService implements package1.BusinessService`;
* `package1.impl.DevelopmentBusinessService implements package1.BusinessService`;
* `package2.impl.ProductionBusinessService implements package2.BusinessService`;
* `package2.impl.DevelopmentBusinessService implements package2.BusinessService`;

then despite the same names for different classes:

* `productionBusinessService` for `package1.impl.ProductionBusinessService` and `package2.impl.ProductionBusinessService`;
* `developmentBusinessService` for `package1.impl.DevelopmentBusinessService` and `package2.impl.DevelopmentBusinessService`;

no implementation errors will occur!
Everything will work correctly as the same component names are created for *different data types!*
====

Thus, for `ProductionBusinessService` and `DevelopmentBusinessService` implementation classes, the following names are set accordingly: `productionBusinessService` and `developmentBusinessService`:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-by-impl-classname-and-field-name/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/impl/classname/field/name/impl/ProductionBusinessService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-by-impl-classname-and-field-name/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/impl/classname/field/name/impl/DevelopmentBusinessService.java[tag=content,indent=0]
----

When injecting implementations, the RxMicro framework reads the name of the class or method parameter field.
If the names of the class fields correspond to the names of implementation components, the successful injection is performed:

[IMPORTANT]
====
If there is *only one implementation class*, in the current module, then regardless of the class field names or method parameters, the instance of this class will be successfully injected!

In other words, the ambiguity resolving algorithm is enabled by default *only if there are such ambiguities!*
====

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-by-impl-classname-and-field-name/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/impl/classname/field/name/BusinessServiceFacade.java[tag=content,indent=0]
----
<1> In the `productionBusinessService` field, the `ProductionBusinessService` class instance is injected.
<2> In the `developmentBusinessService` field, the `DevelopmentBusinessService` class instance is injected.

This behavior can be tested with the following test:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-by-impl-classname-and-field-name/src/test/java/io/rxmicro/examples/cdi/ambiguty/resolving/BusinessServiceFacadeTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-cdi/cdi-ambiguty-resolving-by-impl-classname-and-field-name
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

[[cdi-named]]
==== The `@Named` (`@Qualifier`) Annotation Usage

In case if the ambiguity resolving algorithm by default does not meet the needs of a business task, the developer can set up the implementation process using the following annotations: {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^] or
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^]:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-by-impl-classname-and-Named-annotation/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/impl/classname/named/field/BusinessServiceFacade.java[tag=content,indent=0]
----
<1> To inject the `ProductionBusinessService` class instance to the `businessService1` field, in the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^]
annotation parameter, You need to specify the `productionBusinessService` name. +
_(This is an implicit name that is set by the RxMicro framework for the `ProductionBusinessService` class!)_
<2> To inject the `DevelopmentBusinessService` class instance to the `businessService2` field, in the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^]
annotation parameter, You need to specify the `developmentBusinessService` name. +
_(This is an implicit name that is set by the RxMicro framework for the `DevelopmentBusinessService` class!)_

This behavior can be tested with the following test:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-by-impl-classname-and-Named-annotation/src/test/java/io/rxmicro/examples/cdi/ambiguty/resolving/BusinessServiceFacadeTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-cdi/cdi-ambiguty-resolving-by-impl-classname-and-Named-annotation
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

//-----------------------------------------------------------

An implicitly created name for an implementation class can be set explicitly using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^] or
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^] annotations:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-by-Named-implementation-and-Named-field/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/named/impl/named/field/impl/ProductionBusinessService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-by-Named-implementation-and-Named-field/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/named/impl/named/field/impl/DevelopmentBusinessService.java[tag=content,indent=0]
----

When using explicit names for implementation classes, it is necessary to specify these explicit names as the qualifier of an injection point:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-by-Named-implementation-and-Named-field/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/named/impl/named/field/BusinessServiceFacade.java[tag=content,indent=0]
----
<1> To inject the `ProductionBusinessService` class instance to the `businessService1` field, in the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^]
annotation parameter, You need to specify the `Production` name. +
_(This name is explicitly set for the `ProductionBusinessService` class, using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^] annotation!)_
<2> To inject the `DevelopmentBusinessService` class instance to the `businessService2` field, in the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^]
annotation parameter, You need to specify the `Development` name. +
_(This name is explicitly set for the `DevelopmentBusinessService` class, using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^] annotation!)_

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-cdi/cdi-ambiguty-resolving-by-Named-implementation-and-Named-field
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Custom Annotations Usage

When using string names for implementation classes and injection points, the developer may make a mistake.
Since the compiler does not check the specified names, the error can be detected only during runtime.

If such a situation is unacceptable, custom annotations should be used as qualifiers:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-using-custom-Named-annotation/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/using/custom/named/annotation/EnvironmentType.java[tag=content,indent=0]
----
<1> For a custom annotation to be defined by the RxMicro framework as a qualifier, it must be annotated by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^] or
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^] annotation with an empty string value.
<2> To control the component names with the compiler, it is recommended to use enumerations.

After creating the custom annotation that serves as a qualifier, it is necessary to annotate the implementation classes by it

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-using-custom-Named-annotation/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/using/custom/named/annotation/impl/ProductionBusinessService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-using-custom-Named-annotation/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/using/custom/named/annotation/impl/DevelopmentBusinessService.java[tag=content,indent=0]
----

and injection points:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-using-custom-Named-annotation/src/main/java/io/rxmicro/examples/cdi/ambiguty/resolving/using/custom/named/annotation/BusinessServiceFacade.java[tag=content,indent=0]
----

When using custom annotations, the result of ambiguity resolving will be the same as when using string names:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-ambiguty-resolving-using-custom-Named-annotation/src/test/java/io/rxmicro/examples/cdi/ambiguty/resolving/BusinessServiceFacadeTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-cdi/cdi-ambiguty-resolving-using-custom-Named-annotation
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
