:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[cdi-annotations-section]]
=== `RxMicro Annotations`

The RxMicro framework supports the following `RxMicro Annotations`:

.Supported `RxMicro Annotations`.
[cols="1,3"]
|===
|*Annotation*|*Description*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@Inject`^]
|Indicates the need to inject the component implementation into the annotated class field or method parameter.

_(Is a synonym of the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Autowired.java[`@Autowired`^]
annotation, and is recommended for developers who have used JEE or Google Guice as CDI implementation in their previous projects.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^]
|Allows <<cdi-named, to customize an injection point by specifying a string value or custom annotation.>>
This annotation can also be used to specify a component name.

_(Is a synonym of the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^]
annotation, and is recommended for developers who have used JEE or Google Guice as CDI implementation in their previous projects.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Autowired.java[`@Autowired`^]
|Indicates the need to inject the component implementation into the annotated class field or method parameter.

_(Is a synonym of the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@Inject`^]
annotation, and is recommended for developers who have used Spring DI as CDI implementation in their previous projects.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^]
|Allows <<cdi-named, to customize an injection point by specifying a string value or custom annotation.>>
This annotation can also be used to specify a component name.

_(Is a synonym of the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^]
annotation, and is recommended for developers who have used Spring DI as CDI implementation in their previous projects.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/PostConstruct.java[`@PostConstruct`^]
|Denotes <<cdi-post-construct-section, a method, that should be invoked automatically after all dependencies have been injected into the current component.>>

_(In its semantics, it completely corresponds to the https://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html[`@javax.annotation.PostConstruct`^] annotation.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Factory.java[`@Factory`^]
|Denotes <<cdi-factory-method-section, a factory method>> or <<cdi-factory-class-section, a factory, that creates instances of the specified class>>.

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Resource.java[`@Resource`^]
|Indicates <<cdi-resource-section, the need to inject the external resource>> into the annotated class field or method parameter.

// ---------------------------------------------------------------------------------------------------------------------
|===
