:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[cdi-factory-method-section]]
=== Factory Method

When using the dependency injection mechanisms, the RxMicro framework creates instances of the specified classes and injects references to them to injection points.
For successful implementation of this behavior, each class, the instance of which should be injected, must contain an accessible constructor without parameters or a constructor annotated by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@Inject`^] or
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Autowired.java[`@Autowired`^] annotation.

In other words, the RxMicro framework determines the instance of which class should be created and creates this instance automatically at the start of the CDI container.
If it is necessary to get more control over creation of the implementation instance, it is necessary to use the Factory Method template:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-factory-method/src/main/java/io/rxmicro/examples/cdi/factory/method/BusinessServiceFacade.java[tag=content,indent=0]
----
<1> The class must contain the static method annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Factory.java[`@Factory`^]annotation.
<2> The private constructor restricts the possibility of creating the instance of this class externally.
Thus, the instance of this class can only be created using the `create()` factory method.

If the RxMicro framework detects a method in the class, annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Factory.java[`@Factory`^]annotation, then this method is used instead of the constructor when creating the instance of this class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-factory-method/src/test/java/io/rxmicro/examples/cdi/factory/method/BusinessServiceFacadeTest.java[tag=content,indent=0]
----

The factory method must meet the following requirements:

* The method must be `static`.
* The method must be non-`native`.
* The method must not be `synchronized`.
* The method must return the class instance in which it is declared.
* The method must not contain parameters.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-cdi/cdi-factory-method
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
