:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[cdi-factory-class-section]]
=== Factory Class

The RxMicro framework поддерживает создание классов-фабрик, которые могут использоваться для создания объектов других типов.

Используя классы-фабрики возможно получить следующие преимущества:

* Создавать динамические классы.
_(Например, используя класс {JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/reflect/Proxy.html[`Proxy`^].)_
* Реализовать a `prototype` scope.

Для создания класса-фабрики необходимо:

* Создать класс, реализующий интерфейс {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/function/Supplier.html[`Supplier`^].
* Аннотировать данный класс аннотацией {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Factory.java[`@Factory`^].
* Реализовать метод `get`, который должен вернуть объект создаваемого класса.

Например для создания динамического класса, необходимо использовать следующий класс-фабрику:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-factory-class/src/main/java/io/rxmicro/examples/cdi/factoryclass/BusinessServiceFactoryImpl.java[tag=content,indent=0]
----

Внедрение объекта, создаваемого классом-фабрикой ничем не отличается от внедрения объекта, автоматически создаваемого by the RxMicro framework:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-factory-class/src/main/java/io/rxmicro/examples/cdi/factoryclass/BusinessServiceFacade.java[tag=content,indent=0]
----

При вызове метода `getValue` динамический класс возвращает предопределенное значение:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-factory-class/src/test/java/io/rxmicro/examples/cdi/factoryclass/BusinessServiceFacadeTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}cdi-factory-class
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
