:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[cdi-factory-class-section]]
=== Factory Class

The RxMicro framework supports creation of factory classes, that can be used to create instances of other types.

By using factory classes, it is possible to get the following benefits:

* Create dynamic classes.
_(For example, using the {JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/reflect/Proxy.html[`Proxy`^] class.)_
* Implement a `prototype` scope.

To create a factory class, it is necessary:

* Create a class implementing the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/function/Supplier.html[`Supplier`^] interface.
* Annotate this class by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Factory.java[`@Factory`^]annotation.
* Implement the `get` method, which should return the instance of the created class.

For example, to create a dynamic class, it is necessary to use the following factory class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-factory-class/src/main/java/io/rxmicro/examples/cdi/factoryclass/BusinessServiceFactoryImpl.java[tag=content,indent=0]
----

Injection of an instance created by the factory class does not differ from injection of an instance automatically created by the RxMicro framework:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-factory-class/src/main/java/io/rxmicro/examples/cdi/factoryclass/BusinessServiceFacade.java[tag=content,indent=0]
----

When invoking the `getValue` method, the dynamic class returns a predefined value:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-factory-class/src/test/java/io/rxmicro/examples/cdi/factoryclass/BusinessServiceFacadeTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-cdi/cdi-factory-class
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
