:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[cdi-optional-injection-section]]
=== Optional Injection

By default, all injection points are required.
Thus, if during the process of dependencies injection, the RxMicro framework does not find a suitable instance, an error will occur.

If the current project allows the situation when a suitable instance may be missing, then the `optional injection` mode should be used:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-optional-injection/src/main/java/io/rxmicro/examples/cdi/optional/injection/BusinessServiceFacade.java[tag=content,indent=0]
----
<1> When using the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@Inject`^] annotation, the `optional = true` parameter must be set to enable the `optional injection` mode.
<2> When using the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Autowired.java[`@Autowired`^] annotation, the `required = false` parameter must be set to enable the `optional injection` mode.

If the `optional injection` mode is enabled, the RxMicro framework uses the following injection algorithm:

. If the dependency is found, it will be successfully injected.
. If there's no dependency, nothing happens. +
_(In this case, the behaviour appears to be as if the field is not annotated by any annotation!)_

The correctness of this algorithm can be checked with the following test:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-optional-injection/src/test/java/io/rxmicro/examples/cdi/optional/injection/BusinessServiceFacadeTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}cdi-optional-injection
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
