:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[cdi-post-construct-section]]
=== `@PostConstruct`

If You need to run some code while creating a class instance, Java provides a special method for doing so, namely the constructor.
However, when using the dependency injection mechanisms, the dependencies are injected after creating an instance, and accordingly after invoking the constructor.
_(Except for the constructor injection mechanism!)_.
In order to run some code while creating an instance, but only after introducing all dependencies into this instance, the RxMicro framework provides a special
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/PostConstruct.java[`@PostConstruct`^] annotation.

Thus, if there is a class method, annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/PostConstruct.java[`@PostConstruct`^] annotation, then this method is automatically invoked after all dependencies are injected into the created instance of this class.

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-post-construct/src/main/java/io/rxmicro/examples/cdi/post/construct/BusinessService2Facade.java[tag=content,indent=0]
----
<1> After injection of the implementation class instance in the `businessService` field, the RxMicro framework will automatically invoke the `anyName` method, since this method is annotated by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/PostConstruct.java[`@PostConstruct`^] annotation.

For the convenience of developers, the RxMicro framework introduces an additional convention:

*If there is a method with the `postConstruct` name in the class, this method may not be annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/PostConstruct.java[`@PostConstruct`^] annotation!*

The method with the specified name will be invoked automatically after all dependencies are injected:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-post-construct/src/main/java/io/rxmicro/examples/cdi/post/construct/BusinessService1Facade.java[tag=content,indent=0]
----

Thus, for any method in the class to be defined by the RxMicro framework as the method to be invoked automatically after all dependencies are injected, it is necessary to:

* to annotate this method by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/PostConstruct.java[`@PostConstruct`^] annotation;
* or has the predefined `postConstruct` name.

The `postConstruct` method must meet the following requirements:

* This method should be a single method in the class.
* The method must not be `static`.
* The method must not be `abstract`.
* The method must be non-`native`.
* The method must not be `synchronized`.
* The method must not contain parameters.
* The method must return the `void` type.

The facts of invoking the `postConstruct` and `anyName` methods can be checked using the following tests:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-post-construct/src/test/java/io/rxmicro/examples/cdi/post/construct/BusinessService1FacadeTest.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-post-construct/src/test/java/io/rxmicro/examples/cdi/post/construct/BusinessService2FacadeTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-cdi/cdi-post-construct
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

[NOTE]
====
In many frameworks implementing the https://en.wikipedia.org/wiki/Dependency_injection[*Dependency Injection*^] design template, besides the `postConstruct` methods, there are also the `preDestroy` methods.
These methods are invoked automatically, and usually clear resources when deleting an instance from the CDI container.

For a microservice project that uses the RxMicro framework, there is no need for the `preDestroy` methods.
Since the instances are removed from the CDI container when the java process ends.
And upon completion of any process in the operating system, the operating system automatically clears *all* occupied resources!
====
