:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[cdi-rx-micro-component-injection-section]]
=== RxMicro Components Injection

==== Basic Usage

Besides custom classes, the RxMicro framework supports the RxMicro components injection.

For example, if a declarative REST client is declared in the project:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-rxmicro-component/src/main/java/io/rxmicro/examples/cdi/rxmicro/component/RESTClient.java[tag=content,indent=0]
----

then instead of getting an explicit reference to the implementation class instance using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/RestClientFactory.java#L47[`RestClientFactory.getRestClient`^], the developer can use the dependency injection mechanism:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-rxmicro-component/src/main/java/io/rxmicro/examples/cdi/rxmicro/component/BusinessServiceFacade.java[tag=content,indent=0]
----
<1> To get a reference to the REST client implementation class, the developer can use the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@Inject`^] annotation.
<2> Besides injecting REST clients, the RxMicro framework also supports the configuration injection. +
_(A list of all supported RxMicro components that can be injected is described in the <<cdi-rx-micro-component-injection-all-supported-components-section>>.)_

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}cdi-rxmicro-component
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

[[cdi-rx-micro-component-injection-all-supported-components-section]]
==== All Supported RxMicro Components

This section describes all supported RxMicro components that can be injected in any class using the injection mechanisms.

.All Supported RxMicro Components.
[cols="1,3"]
|===
|*Name*|*Feature*

|Config instance.
|Any class that extends the basic configuration class: {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Config.java[`Config`^].

_(For example: `MongoConfig`, `HttpClientConfig`, `HttpServerConfig`, etc.)_

|Mongo repository.
|The interface annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-mongo/src/main/java/io/rxmicro/data/mongo/MongoRepository.java[`@MongoRepository`^] annotation.

|Mongo client.
|Predefined type: {MONGO-ASYNC-REACTIVE_DOC}com/mongodb/reactivestreams/client/MongoClient.html[`com.mongodb.reactivestreams.client.MongoClient`^]

|PostgreSQL repository.
|The interface annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-sql-r2dbc-postgresql/src/main/java/io/rxmicro/data/sql/r2dbc/postgresql/PostgreSQLRepository.java[`@PostgreSQLRepository`^] annotation.

|R2DBC connection factory.
|Predefined type: {R2DBC-JAVADOC-ROOT-URL}io/r2dbc/spi/ConnectionFactory.html[`io.r2dbc.spi.ConnectionFactory`^].

|R2DBC connection pool.
|Predefined type: {R2DBC-JAVADOC-POOL-URL}io/r2dbc/pool/ConnectionPool.html[`io.r2dbc.pool.ConnectionPool`^].

|REST client.
|The interface annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/RestClient.java[`@RestClient`^] annotation.

|===

[TIP]
====
The source code of the project demonstrating all supported for injection RxMicro components is available at the following link:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}cdi-all-rxmicro-components[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}cdi-all-rxmicro-components`^]
====
