:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[cdi-singletons-section]]
=== All Beans are Singletons!

The RxMicro framework focuses on creating microservice projects.
One of the key features of microservices is their simplicity.
That's why `singleton` scope was chosen as the main and only one.

Thus, *all CDI components are `singletons`!*

It means that when starting a microservice project, *only one instance* of the component implementation class is created and injected into all necessary injection points.

[NOTE]
====
If it is necessary to inject a separate implementation class instance (`prototype` scope) to each injection point, then You must use  <<cdi-factory-class-section, the factory that creates instances of the given class>>!
====

This behavior can be checked with the following code:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-singletons/src/main/java/io/rxmicro/examples/cdi/singletons/BusinessServiceImpl.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-singletons/src/main/java/io/rxmicro/examples/cdi/singletons/BusinessServiceFacade.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-cdi/cdi-singletons/src/test/java/io/rxmicro/examples/cdi/singletons/BusinessServiceFacadeTest.java[tag=content,indent=0]
----
<1> Since the `BusinessServiceImpl` class implements two interfaces, the same implementation instance is injected when injecting different types of interfaces!

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-cdi/cdi-singletons
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
