:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[cdi-spring-style-section]]
=== Dependency Injection Using Spring Style

The developers with a rich experience in using Spring in their previous projects can instead of the following annotations:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@Inject`^] and
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^]
use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Autowired.java[`@Autowired`^] and
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^] annotations respectively, which are absolutely similar in features:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-spring-style/src/main/java/io/rxmicro/examples/cdi/spring/style/impl/ProductionBusinessService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-spring-style/src/main/java/io/rxmicro/examples/cdi/spring/style/impl/DevelopmentBusinessService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-spring-style/src/main/java/io/rxmicro/examples/cdi/spring/style/BusinessServiceFacade.java[tag=content,indent=0]
----
<1> To inject the `ProductionBusinessService` class instance in the `businessService1` field, it is necessary in the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^]
annotation parameter specify the `Production` name. +
_(This is the name that is set explicitly for the `ProductionBusinessService` class by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^] annotation!)_
<2> To inject the `DevelopmentBusinessService` class instance in the `businessService2` field, it is necessary in the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^]
annotation parameter specify the `Development` name. +
_(This is the name that is set explicitly for the `DevelopmentBusinessService` class by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^] annotation!)_

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}cdi-spring-style
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
