:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

==== Basic Rules

The RxMicro framework supports HTTP headers in request and response models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-headers/src/main/java/io/rxmicro/examples/rest/controller/headers/model/Request.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-headers/src/main/java/io/rxmicro/examples/rest/controller/headers/model/Response.java[tag=content,indent=0]
----
<1> The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/HeaderMappingStrategy.java[`@HeaderMappingStrategy`^]
annotation allows setting common conversion rules for all header names from HTTP to Java format and vice versa in the current model class. +
_(By default, the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-model/src/main/java/io/rxmicro/model/MappingStrategy.java#L59[`CAPITALIZE_WITH_HYPHEN`^] strategy is used.
The field name is used as the basic name, and then, following the rules of the specified strategy, the HTTP header name is generated.)_
<2> In order to declare a model field as the HTTP header field, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Header.java[`@Header`^] annotation.
<3> Using the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Header.java[`@Header`^]
annotation, it is possible to specify the HTTP header name, which does not correspond to the used strategy declared by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/HeaderMappingStrategy.java[`@HeaderMappingStrategy`^] annotation.

The RxMicro framework uses the following algorithm to define the HTTP header name for the specified model field:

. If the field is annotated by the `@Header` annotation with an explicit indication of the HTTP header name, the specified name is used;
. If no HTTP header name is specified in the `@Header` annotation, the RxMicro framework checks for the `@HeaderMappingStrategy` annotation above the model class;
. If the model class is annotated by the `@HeaderMappingStrategy` annotation, then the specified naming strategy is used. +
_(The field name is used as the basic name, and then, following the rules of the specified strategy, the HTTP header name is generated.)_
. If the `@HeaderMappingStrategy` annotation is missing, the model class field name is used as the HTTP header name.