:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

==== Basic Rules

The RxMicro framework supports HTTP parameters in request and response models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/model/Request.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/model/Response.java[tag=content,indent=0]
----
<1> The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ParameterMappingStrategy.java[`@ParameterMappingStrategy`^]
annotation allows setting common conversion rules for all parameter names from HTTP to Java format and vice versa in the current model class.
_(By default, the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-model/src/main/java/io/rxmicro/model/MappingStrategy.java#L34[`LOWERCASE_WITH_UNDERSCORED`^] strategy is used.
The field name is used as the basic name, and then, following the rules of the specified strategy, the HTTP parameter name is generated.)_
<2> In order to declare a model field as the HTTP parameter field, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Parameter.java[`@Parameter`^] annotation.
_(Unlike the `@Header` annotation, the `@Parameter` annotation is optional.
Thus, if the model field is not annotated by any annotation, then by default it is assumed that there is the `@Parameter` annotation above the model field.)_
<3>  Using the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Parameter.java[`@Parameter`^]
annotation, it is possible to specify the HTTP parameter name, which does not correspond to the used strategy declared by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ParameterMappingStrategy.java[`@ParameterMappingStrategy`^] annotation.

The RxMicro framework uses the following algorithm to define the HTTP parameter name for the specified model field:

. If the field is annotated by the `@Parameter` annotation with an explicit indication of the HTTP parameter name, the specified name is used;
. If no HTTP parameter name is specified in the `@Parameter` annotation, the RxMicro framework checks for the `@ParameterMappingStrategy` annotation above the model class;
. If the model class is annotated by the `@ParameterMappingStrategy` annotation, then the specified naming strategy is used.
_(The field name is used as the basic name, and then, following the rules of the specified strategy, the HTTP parameter name is generated.)_
. If the `@ParameterMappingStrategy` annotation is missing, the model class field name is used as the HTTP parameter name.

[IMPORTANT]
====
*Unlike the `@Header` annotation, the `@Parameter` annotation is optional!*

Thus, if the model field is not annotated by any annotation, then *by default it is assumed that there is the `@Parameter` annotation above the model field!*
====