[[cdi-annotations-section]]
=== `RxMicro Annotations`

RxMicro поддерживает следующие `RxMicro annotations`, которые используются для настроек модуля `rxmicro.cdi`.

.`RxMicro Annotations` for Customization of CDI.
[cols="1,3"]
|===
|*Аннотация*|*Описание*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@Inject`^]
|Указывает на необходимость внедрить реализацию компонента в аннотированное поле класса или параметр метода.

_(Является синонимом аннотации {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Autowired.java[`@Autowired`^]
и рекомендована к использованию разработчиками, которые в качестве реализации CDI в своих предыдущих проектах использовали JEE или Google Guice.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^]
|Позволяет <<cdi-named, кастомизировать точку внедрения, указав строковое значение или пользовательскую аннотацию.>>

_(Является синонимом аннотации {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^]
и рекомендована к использованию разработчиками, которые в качестве реализации CDI в своих предыдущих проектах использовали JEE или Google Guice.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Autowired.java[`@Autowired`^]
|Указывает на необходимость внедрить реализацию компонента в аннотированное поле класса или параметр метода.

_(Является синонимом аннотации {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@Inject`^]
и рекомендована к использованию разработчиками, которые в качестве реализации CDI в своих предыдущих проектах использовали Spring DI.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Qualifier.java[`@Qualifier`^]
|Позволяет <<cdi-named, кастомизировать точку внедрения, указав строковое значение или пользовательскую аннотацию.>>

_(Является синонимом аннотации {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Named.java[`@Named`^]
и рекомендована к использованию разработчиками, которые в качестве реализации CDI в своих предыдущих проектах использовали Spring DI.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/PostConstruct.java[`@PostConstruct`^]
|Указывает на <<cdi-post-construct-section, метод, который должен быть вызван автоматически после внедрения всех зависимостей в текущий компонент.>>

_(По своей семантике полностью соответсвует анотации https://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html[`@PostConstruct`^].)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Factory.java[`@Factory`^]
|Указывает на <<cdi-factory-method-section, фабричный метод>> или <<cdi-factory-class-section, фабрику создания объектов заданного класса>>.

// ---------------------------------------------------------------------------------------------------------------------
|===
