:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[cdi-basic-section]]
=== Basic Usage

Для использования модуля `rxmicro.cdi` в проекте, необходимо выполнить два шага:

* Подключить зависимость `rxmicro-cdi` в файл `pom.xml`:

[source,xml]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-basic/pom.xml[tag=content,indent=0]
----

* Добавить модуль `rxmicro.cdi` в дескриптор `module-info.java`:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-basic/src/main/java/module-info.java[tag=content,indent=0]
----

После подключения модуля `rxmicro.cdi` можно создавать бизнес сервис:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-basic/src/main/java/io/rxmicro/examples/cdi/basic/BusinessService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-basic/src/main/java/io/rxmicro/examples/cdi/basic/BusinessServiceImpl.java[tag=content,indent=0]
----

Для внедрения реализации бизнес сервиса, необходимо испрользовать аннотацию
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@Inject`^]:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-basic/src/main/java/io/rxmicro/examples/cdi/basic/RestController.java[tag=content,indent=0]
----
<1> Использование аннотации {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-cdi/src/main/java/io/rxmicro/cdi/Inject.java[`@io.rxmicro.cdi.Inject`^]
ничем принципиальным не отличается от использования аннотаций
https://docs.oracle.com/javaee/6/api/javax/inject/Inject.html[`@javax.inject.Inject`^] или
https://google.github.io/guice/api-docs/latest/javadoc/index.html?com/google/inject/Inject.html[`@com.google.inject.Inject`^].

Корректность внедрения может быть проверена с помощью <<testing#testing-rest-based-microservice-tests-section, теста REST-based микросервиса>>:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-basic/src/test/java/io/rxmicro/examples/cdi/basic/RestControllerTest.java[tag=content,indent=0]
----

Реализация бизнес сервиса может быть внедрена не только в REST контроллер, но и в любой компонент:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-basic/src/main/java/io/rxmicro/examples/cdi/basic/BusinessServiceFacade.java[tag=content,indent=0]
----

Так как внедрение выполняется в обычный компонент, то для тестирования необходимо использовать <<testing#testing-component-tests-section,подход к тестированию компонентов микросервиса>>:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-basic/src/test/java/io/rxmicro/examples/cdi/basic/BusinessServiceFacadeTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}cdi-basic
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
