:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[cdi-singletons-section]]
=== All Beans are Singletons!

The RxMicro framework ориентирован на создание микросервисных проектов.
Одним из ключевых особенностей микросервисов является их простота.
Именно поэтому в качестве основного и единственного scope был выбран `singleton` scope.

Таким образом *все CDI компоненты являются `singletons`!*

Это означает что в момент запуска микросервисного проекта создается *только один объект* класса реализации компонента и внедряется во все необходимые injection points.

[NOTE]
====
Если необходимо to each injection point внедрять отдельный объект класса реализации (`prototype` scope), то в этом случае необходимо использовать <<cdi-factory-class-section, фабрику, создающую объекты заданного класса>>!
====

Данное поведение может быть проверено с помощью следующего кода:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-singletons/src/main/java/io/rxmicro/examples/cdi/singletons/BusinessServiceImpl.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-singletons/src/main/java/io/rxmicro/examples/cdi/singletons/BusinessServiceFacade.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/cdi-singletons/src/test/java/io/rxmicro/examples/cdi/singletons/BusinessServiceFacadeTest.java[tag=content,indent=0]
----
<1> Так как класс `BusinessServiceImpl` реализует два интерфейса, то при внедрении разных с точки зрения интерфейсов типов внедряется один и тотже объект реализации!

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}cdi-singletons
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
