:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

=== Configuring the Project

Before writing the code of a REST-based microservice, You should configure `pom.xml` of Your project by performing the following steps:

. Define the versions of used libraries.
. Add the required dependencies to the `pom.xml`.
. Configure the `maven-compiler-plugin`.

==== Definition the Versions of the Used Libraries

To make further updating of library versions convenient, it is recommended to use `maven properties`:

[source,xml,subs="attributes+"]
----
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <rxmicro.version>{rxmicro-version}</rxmicro.version> <!--1-->
    <maven-compiler-plugin.version>{maven-compiler-plugin-version}</maven-compiler-plugin.version> <!--2-->
</properties>
----
<1> {MAVEN-REPO-SEARCH-ROOT}io.rxmicro[The latest stable version of the RxMicro framework^].
<2> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-compiler-plugin[The latest stable version of the `maven-compiler-plugin`^].

==== Adding the Required Dependencies

Before using RxMicro modules, the following dependencies must be added to the project:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-rest-server-netty</artifactId> <!--1-->
        <version>${rxmicro.version}</version>
    </dependency>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-rest-server-exchange-json</artifactId> <!--2-->
        <version>${rxmicro.version}</version>
    </dependency>
</dependencies>
----
<1> Library for building REST-based microservices based on HTTP server that uses https://netty.io/[Netty^];
<2> Library for converting Java model to https://www.json.org/[JSON^] format and vice versa;

[[quick-start-maven-compiler-plugin-settings-section]]
==== Configuring the `maven-compiler-plugin`

Since the RxMicro framework uses the {JDK-JAVA-COMPILER-DOC-ROOT-URL}javax/annotation/processing/Processor.html[Java annotation processors^], You need to set up `maven-compiler-plugin`:

[source,xml]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <release>11</release> <!--1-->
        <annotationProcessorPaths>
            <annotationProcessorPath>
                <groupId>io.rxmicro</groupId>
                <artifactId>rxmicro-annotation-processor</artifactId> <!--2-->
                <version>${rxmicro.version}</version>
            </annotationProcessorPath>
        </annotationProcessorPaths>
    </configuration>
    <executions>
        <execution>
            <id>source-compile</id>
            <goals>
                <goal>compile</goal>
            </goals>
            <configuration>
                <annotationProcessors>
                    <annotationProcessor>
                        io.rxmicro.annotation.processor.RxMicroAnnotationProcessor <!--3-->
                    </annotationProcessor>
                </annotationProcessors>
                <generatedSourcesDirectory>
                    ${project.build.directory}/generated-sources/ <!--4-->
                </generatedSourcesDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
----
<1> The RxMicro framework requires a Java compiler of v11 or higher;
<2> The annotation processor library, that will handle all `RxMicro Annotations`;
<3> The annotation processor class, that handles the launch configuration;
<4> Location of the generated Java classes by the `RxMicro Annotation Processor`;

==== The Final Version of `pom.xml` File

After all the above changes, the final version of the `pom.xml` file should look like:

[source,xml,subs="attributes+"]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.rxmicro.examples</groupId>
    <artifactId>quick-start</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <rxmicro.version>{rxmicro-version}</rxmicro.version>
        <maven-compiler-plugin.version>{maven-compiler-plugin-version}</maven-compiler-plugin.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <release>11</release>
                        <annotationProcessorPaths>
                            <annotationProcessorPath>
                                <groupId>io.rxmicro</groupId>
                                <artifactId>rxmicro-annotation-processor</artifactId>
                                <version>${rxmicro.version}</version>
                            </annotationProcessorPath>
                        </annotationProcessorPaths>
                    </configuration>
                    <executions>
                        <execution>
                            <id>source-compile</id>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                            <configuration>
                                <annotationProcessors>
                                    <annotationProcessor>
                            io.rxmicro.annotation.processor.RxMicroAnnotationProcessor
                                    </annotationProcessor>
                                </annotationProcessors>
                                <generatedSourcesDirectory>
                                    ${project.build.directory}/generated-sources/
                                </generatedSourcesDirectory>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.rxmicro</groupId>
            <artifactId>rxmicro-rest-server-netty</artifactId>
            <version>${rxmicro.version}</version>
        </dependency>
        <dependency>
            <groupId>io.rxmicro</groupId>
            <artifactId>rxmicro-rest-server-exchange-json</artifactId>
            <version>${rxmicro.version}</version>
        </dependency>
    </dependencies>
</project>
----
