:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

=== The Project at the Github

The REST-based `HelloWorldMicroService` microservice project is available at the following link:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}quick-start[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}quick-start`^].

[IMPORTANT]
====
The `pom.xml` configuration file is a reference configuration and can be copied to Your next project using the RxMicro framework.

*DON'T FORGET to remove the link to the parent project*:

[source,xml,subs="attributes+"]
----
<parent>
    <artifactId>examples</artifactId>
    <groupId>io.rxmicro</groupId>
    <version>{RXMICRO-VERSION}</version>
</parent>
----

*and add the `properties` section describing the versions of the libraries used*:

[source,xml,subs="attributes+"]
----
<properties>
    <rxmicro.version>{RXMICRO-VERSION}</rxmicro.version> <!--1-->

    <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version> <!--2-->
    <maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version> <!--3-->
    <maven-dependency-plugin.version>3.1.1</maven-dependency-plugin.version> <!--4-->
</properties>
----

<1> {MAVEN-REPO-SEARCH-ROOT}io.rxmicro/rxmicro[The latest stable version of the RxMicro framework^].
<2> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-compiler-plugin[The latest stable version of the `maven-compiler-plugin`^].
<3> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-surefire-plugin[The latest stable version of the `maven-surefire-plugin`^].
<4> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-dependency-plugin[The latest stable version of the `maven-dependency-plugin`^].
====
