:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== Automated Test

The RxMicro framework provides modules for effective writing of <<{testing}#tesing-section,any type of tests>>.
Among all supported test types, a REST-based microservice test is required for the current project.

==== Configuring the Project

Before writing a REST-based microservice test, You need to configure `pom.xml` of Your project by performing the following steps:

. Add the required dependencies to `pom.xml`.
. Configure the `maven-compiler-plugin`.
. Configure the `maven-surefire-plugin`.

===== Adding the Required Dependencies

Before using RxMicro modules for testing, You need to add the following dependencies to the project:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-test-junit</artifactId> <!--1-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-http-client-jdk</artifactId> <!--2-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-rest-client-exchange-json</artifactId> <!--3-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
----
<1> Unit testing library based on the https://junit.org/junit5/[JUnit 5^] framework
<2> HTTP client library based on the https://developer.oracle.com/java/jdk-http-client.html[`java.net.http`^] JDK module;
<3> Library for Java model conversion to https://www.json.org/[JSON^] format and vice versa on the HTTP client side;

The REST-based microservice testing process consists in launching the REST-based microservice and sending a request to the microservice via HTTP client. +
_(Therefore, in `maven` dependencies it's necessary to add the HTTP client library (`rxmicro-http-client-jdk`) and the library supporting the https://www.json.org/[JSON^]
format on the HTTP client side (`rxmicro-rest-client-exchange-json`))_. +
After receiving a response from the microservice, the response is compared to the expected one.

===== Configuring the `maven-compiler-plugin`

Since the RxMicro framework uses the {JDK-JAVA-COMPILER-DOC-ROOT-URL}javax/annotation/processing/Processor.html[Java annotation processors^], You need to configure `maven-compiler-plugin`:

[source,xml]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <release>11</release>
        <annotationProcessorPaths>
            <annotationProcessorPath>
                <groupId>io.rxmicro</groupId>
                <artifactId>rxmicro-annotation-processor</artifactId>
                <version>${rxmicro.version}</version>
            </annotationProcessorPath>
        </annotationProcessorPaths>
    </configuration>
    <executions>
        <execution>
            <id>source-compile</id>
            <goals>
                <goal>compile</goal>
            </goals>
            <configuration>
                <annotationProcessors>
                    <annotationProcessor>
            io.rxmicro.annotation.processor.RxMicroAnnotationProcessor
                    </annotationProcessor>
                </annotationProcessors>
                <generatedSourcesDirectory>
                    ${project.build.directory}/generated-sources/
                </generatedSourcesDirectory>
            </configuration>
        </execution>
        <execution>
            <id>test-compile</id> <!--1-->
            <goals>
                <goal>testCompile</goal>
            </goals>
            <configuration>
                <annotationProcessors>
                    <annotationProcessor>
            io.rxmicro.annotation.processor.RxMicroTestsAnnotationProcessor <!--2-->
                    </annotationProcessor>
                </annotationProcessors>
                <generatedTestSourcesDirectory>
                    ${project.build.directory}/generated-test-sources/ <!--3-->
                </generatedTestSourcesDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
----
<1> The tests require a separate configuration, so a new `execution` must be added.
<2> The annotation processor class that handles test configuration.
<3> Location of Java-generated classes by the test annotation processor.

[NOTE]
====
To learn more about how the `RxMicro Annotation Processor` works in the test environment, please go to the following section: <<{testing}#testing-how-it-works-section>>.
====

===== Configuring the `maven-surefire-plugin`

include::../___shared/maven-surefire-plugin-configuration.adoc[]

==== Creating a Test Class

REST-based microservice test is a one class containing one test method:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/quick-start/src/test/java/io/rxmicro/examples/quick/start/HelloWorldMicroServiceTest.java[tag=content]
----
<1> The `RxMicro Test Annotation` indicating which microservice should be run for testing.
<2> The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] is a basic HTTP client interface designed for use in tests.
This interface allows executing *blocking* requests to the microservice via the `HTTP` protocol.
This field is initialized automatically when running the test with `reflection`.
Upon initialization it refers to the test HTTP server that was automatically started for the test.
<3> Blocking request to the microservice.
<4> Comparing the contents of an HTTP body with an expected value.
<5> Comparing the HTTP status code with an expected value.

[NOTE]
====
For low-level and effective work with JSON format, the RxMicro framework provides a separate `rxmicro.json` module.

To get a common idea of the capabilities of this module, which are required when writing tests, go to the following section: <<{core}#core-rx-micro-json-section>>.
====

*In microservice tests it is recommended to compare the HTTP request body before comparing the HTTP status, when the microservice constantly returns a text error message!
(This will make it easier to understand the error in case it occurred during the testing.)*

*If the microservice returns ONLY the status when an error occurs, the HTTP body comparison should be skipped!*

[NOTE]
====
For further information on how to test REST-based microservices, go to the following section: <<{testing}#testing-rest-based-microservice-tests-section>>.
====

==== Starting the Test Class

To start the tests, You need to run the command:

[source,txt,subs="verbatim,quotes"]
----
*mvn* clean test
----

After starting, the console will display the following information:

[source,text,subs="verbatim,quotes"]
----
...
[INFO] Compiling 3 source files to ~/examples/quick-start/target/classes
[INFO]
[INFO] -------------------------------------------------------
[INFO]  *RX-MICRO ANNOTATIONS PROCESSING* # <1>
[INFO] -------------------------------------------------------
[INFO] Current environment context is:
  Current module:
    `examples.quick.start`
  Available RxMicro modules:
    ...
  Include packages: <none>
  Exclude packages: <none>
[INFO] Found the following REST controllers:
  GET / -> io.rxmicro.examples.quick.start.HelloWorldMicroService.sayHelloWorld()
[INFO] Generating java classes...
[INFO] All java classes generated successful in 0.398 seconds. # <2>
[INFO] -------------------------------------------------------
[INFO] Annotations processing completed successful.
...
[INFO] Compiling 1 source file to ~/examples/quick-start/target/test-classes
[INFO]
[INFO] -------------------------------------------------------
[INFO]  *RX-MICRO TEST ANNOTATIONS PROCESSING* # <3>
[INFO] -------------------------------------------------------
[INFO] Generating java classes...
[INFO] All java classes generated successful in 0.366 seconds. # <4>
[INFO] -------------------------------------------------------
[INFO] Annotations processing completed successful.
...
[INFO] -------------------------------------------------------
[INFO]  *T E S T S*
[INFO] -------------------------------------------------------
*opens* rxmicro.runtime/io.rxmicro.runtime.local to ALL-UNNAMED # <5>
*opens* rxmicro.runtime/io.rxmicro.runtime.local.error to ALL-UNNAMED # <5>
*opens* rxmicro.runtime/io.rxmicro.runtime.local.provider to ALL-UNNAMED # <5>
*opens* rxmicro.rest.server/io.rxmicro.rest.server.local.model to ALL-UNNAMED # <5>
*opens* rxmicro.rest.server/io.rxmicro.rest.server.local.component to ALL-UNNAMED # <5>
*opens* rxmicro.rest.server/io.rxmicro.rest.server.local.component.impl to ALL-UNNAMED
*opens* examples.quick.start/io.rxmicro.examples.quick.start to ALL-UNNAMED # <5>
*opens* examples.quick.start/rxmicro to ALL-UNNAMED # <5>
[INFO] Running *io.rxmicro.examples.quick.start.HelloWorldMicroServiceTest* # <6>
[INFO] i.r.r.s.n.i.c.NettyServer : Server started at 0.0.0.0:45853 using NETTY transport. # <7>
[INFO] i.r.h.c.j.i.JdkHttpClient : JdkHttpClient released # <8>
[INFO] i.r.r.s.n.i.c.NettyServer : Retrieved shutdown request ...
[INFO] i.r.r.s.n.i.c.NettyServer : Server stopped # <9>
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0 # <10>
[INFO]
[INFO] *BUILD SUCCESS*
[INFO] -------------------------------------------------------
----

<1> Starting of the `RxMicro Annotation Processor`.
<2> `RxMicro Annotation Processor` has successfully completed its work.
<3> Starting of the `RxMicro Tests Annotation Processor`.
<4> `RxMicro Tests Annotation Processor` has successfully completed its work.
<5> For the test configuration, missing exports were automatically added using the capabilities of the {JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Module.html[`java.lang.Module`^] class.
<6> REST-based microservice test starting.
<7> HTTP server has started automatically on random free port.
<8> The resources of the `BlockingHttpClient` component have been released.
<9> HTTP server has stopped successfully.

[NOTE]
====
For further information on how the `RxMicro Annotation Processor` works for the test environment, go to the following section: <<{testing}#testing-how-it-works-section>>.
====
