:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[java-integration-unnamed-module]]
=== Unnamed Modules Support

https://openjdk.java.net/projects/jdk9/[On September 21, 2017], Java 9 has introduced {WHAT-IS-JPMS-LINK}[`JPMS`^].

[TIP]
====
There are four types of modules in the {WHAT-IS-JPMS-LINK}[`JPMS`^]:

* *System Modules* - There are the Java SE and JDK modules. +
_(For example `java.base`, `java.logging`, `java.net.http`, etc)_
* *Application Modules* - The default modules, that are built using JPMS. +
They are `named` and defined in the compiled `module-info.class` file included in the assembled JAR.
* *Automatic Modules* - The modules that are created automatically from all unmodularized jar files at the module path.
The name of the modules will be derived from the name of the appropriate JAR files.
* *Unnamed Modules* - The modules that are created automatically if JAR files are loaded onto the classpath instead of the module path.
Unnamed modules disable the JPMS and allow to run any code that does not support the JPMS on Java 9 or higher.
====

Currently, the majority of existing frameworks and libraries are focused on https://openjdk.java.net/projects/jdk8/[JDK 8] and do not support {WHAT-IS-JPMS-LINK}[`JPMS`^].

To support compatibility with libraries that do not support {WHAT-IS-JPMS-LINK}[`JPMS`^], Java 9 provides the `unnamed modules` mechanism.

The feature of this mechanism is that the code written in Java 9 and higher does not use the `module-info.java` module descriptor, and uses `class-path` instead of `module-path`.
For integration with libraries that do not support {WHAT-IS-JPMS-LINK}[`JPMS`^], the RxMicro framework allows You to enable the `unnamed module` mode for the `RxMicro Annotation Processor`.

To enable this mode, You need to add the `RX_MICRO_BUILD_UNNAMED_MODULE` configuration parameter to the `maven-compiler-plugin` settings:

[source,xml]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <release>11</release>
        <!-- ... -->
        <compilerArgs>
            <arg>-ARX_MICRO_BUILD_UNNAMED_MODULE=true</arg> <!--1-->
        </compilerArgs>
    </configuration>
    <!-- ... -->
</plugin>
----

<1> The `RxMicro Annotation Processor` will use the `unnamed module` mode for the current microservice project.

<<<

include::unnamed-module/uber-jar.adoc[]

<<<

include::unnamed-module/module-config.adoc[]