:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[java-integration-unnamed-module]]
=== Unnamed Modules Support

https://openjdk.java.net/projects/jdk9/[21 September 2017] Java 9 ввела в использование https://www.oracle.com/corporate/features/understanding-java-9-modules.html[JPMS^].

[TIP]
====
There are four types of modules in the JPMS:

* *System Modules* - There are the Java SE and JDK modules. +
_(For example `java.base`, `java.logging`, `java.net.http`, etc)_
* *Application Modules* - The default modules, which are built using JPMS. +
They are `named` and defined in the compiled `module-info.class` file included in the assembled JAR.
* *Automatic Modules* - The modules which are created automatically from all unmodularized jar files at the module path.
The name of the modules will be derived from the name of the appropriate JAR files.
* *Unnamed Modules* - The modules which are created automatically if JAR files are loaded onto the classpath instead of the module path.
Unnamed modules disable the JPMS and allow to run any code which does not support the JPMS on Java 9 or higher.
====

Однако на сегодняшний день большая часть существующих фреймворком и библиотек ориентированы на https://openjdk.java.net/projects/jdk8/[JDK 8] и не поддерживают JPMS.

Для поддержки совместимости с библиотеками, которые не поддерживают JPMS, Java 9 предоставляет механизм `unnamed modules`.

Особенностью данного механизма является то, что код, написанный на Java 9 и выше не использует дескриптор модуля `module-info.java` и использует `class-path` вместо `module-path`.
Для интеграции с библиотеками, которые не поддерживают JPMS, the RxMicro framework позволяет активировать режим `unnamed module` для the `RxMicro Annotation Processor`.

Для активации данного режима, необходимо в настройках `maven-compiler-plugin` добавить конфигурационный параметр `RX_MICRO_BUILD_UNNAMED_MODULE`:

[source,xml]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <release>11</release>
        <!-- ... -->
        <compilerArgs>
            <arg>-ARX_MICRO_BUILD_UNNAMED_MODULE=true</arg> <!--1-->
        </compilerArgs>
    </configuration>
    <!-- ... -->
</plugin>
----

<1> The `RxMicro Annotation Processor` will use the `unnamed module` mode for the current microservice project.

<<<

include::unnamed-module/uber-jar.adoc[]

<<<

include::unnamed-module/module-config.adoc[]