:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

ifndef::test-template-owner[]
:db-link: https://rxmicro.io
:db-name: RxMicro DB
:docker-test-db-link: {RX-MICRO-DOCKER_HUB_ROOT}rxmicro-test-db
:docker-test-db-name: rxmicro/rxmicro-test-db
:shared-template-source-code: ../../../../../../examples/group-data-mongo/data-mongo-basic/src/test/java/io/rxmicro/examples/data/mongo/basic/DataRepositoryTestTemplate1.java
:personal-template-source-code: ../../../../../../examples/group-data-mongo/data-mongo-basic/src/test/java/io/rxmicro/examples/data/mongo/basic/DataRepositoryTestTemplate2.java
endif::[]

As a mechanism for preparing a database for testing (creating a database before starting the test and deleting a database after completing the test), it is most convenient to use https://www.docker.com/[`docker`^].

To start `docker` containers in the functional test it is convenient to use the https://www.testcontainers.org/[`Testcontainers`^] Java library:

[source,java]
----
include::{shared-template-source-code}[tag=content,indent=0]
----
<1> The {TESTCONTAINERS-JUNIT-DOC-ROOT-URL}org/testcontainers/junit/jupiter/Testcontainers.java[`@Testcontainers`^]
annotation activates the start and stop of the `docker` containers to be used in this test.
<2> Since the dynamic repository is a RxMicro component, for its testing You need to use <<testing#testing-component-tests-section,the microservice component testing approach>>.
<3> The {TESTCONTAINERS-JUNIT-DOC-ROOT-URL}org/testcontainers/junit/jupiter/Container.java[`@Container`^]
annotation indicates the `docker` container that will be used in this test.
As an image on the basis of which it is necessary to create the `docker` container, the {db-link}[`{db-name}`^] ready-made image with the
{docker-test-db-link}[`{docker-test-db-name}`^] test database is used.
<4> When starting the `docker` container, You need to open the standard port for {db-link}[`{db-name}`^].
<5> Using the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/WithConfig.java[`@WithConfig`^]
annotation, the configuration available only during the test is declared.
<6> Setting up the configuration to interact with the test database.
<7> Before running all tests, You must start the `docker` container.
<8> After starting the `docker` container, You need to read the random IP address and port that will be used when connecting to the running `docker` container.
<9> When testing <<testing#testing-component-tests-section,microservice components>>, it is necessary to specify a reference to the component in which the RxMicro framework will inject the tested component.
<10> After completing all the tests, You must stop the `docker` container.

The main advantage of this template is the speed of testing.
Since the `docker` container is created once before starting *all* test methods, the total runtime of all test methods is reduced.
The main disadvantage of this template is that if any test method changes the {db-link}[`{db-name}`^] state, the following test method may end with an error.

*Therefore, this functional test template should be used for queries to {db-link}[`{db-name}`^] that do not change the database state!*

If You need to test methods that change the {db-link}[`{db-name}`^] state, You should use another template:

[source,java]
----
include::{personal-template-source-code}[tag=content,indent=0]
----
<1> The {TESTCONTAINERS-JUNIT-DOC-ROOT-URL}org/testcontainers/junit/jupiter/Testcontainers.java[`@Testcontainers`^]
annotation activates the start and stop of the `docker` containers to be used in this test.
<2> Since the dynamic repository is a RxMicro component, for its testing You need to use <<testing#testing-component-tests-section,the microservice component testing approach>>
<3> The {TESTCONTAINERS-JUNIT-DOC-ROOT-URL}org/testcontainers/junit/jupiter/Container.java[`@Container`^]
annotation indicates the `docker` container that will be used in this test.
As an image on the basis of which it is necessary to create the `docker` container, the {db-link}[`{db-name}`^] ready-made image with the
{docker-test-db-link}[`{docker-test-db-name}`^] test database is used.
<4> When starting the `docker` container, You need to open the standard port for {db-link}[`{db-name}`^].
<5> Using the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/WithConfig.java[`@WithConfig`^]
annotation, the configuration available only during the test is declared.
<6> Setting up the configuration to interact with the test database.
<7> When testing <<testing#testing-component-tests-section,microservice components>>, it is necessary to specify a reference to the component in which the RxMicro framework will inject the tested component.
<8> After starting the `docker` container, You need to read the random IP address and port that will be used when connecting to the running `docker` container.

This template *for each test method* will create and drop the `docker` container, which may increase the total runtime of all test methods.

*Therefore, select the most appropriate functional test template based on the requirements of the tested functionality!*

[IMPORTANT]
====
The https://www.testcontainers.org/[`Testcontainers`^] library starts the `docker` container before running the test and stops the `docker` container automatically after completing the test!

So You should start and stop the `docker` container manually only if You want to use one `docker` container for *all* test methods!
====