:FRAGMENT_RELATIVE_DIR: ../../../../
include::../../../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../../../

[[data-postgresql-select-return-reactive-types-section]]
====== Reactive Types Support

PostgreSQL Data Repositories that generated by the RxMicro frameworks support the following return reactive types:

* If expected an asynchronous `0`-`1` result:
.. {REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono<MODEL>`^];
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<MODEL>`^];
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage<MODEL>`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Single.html[`Single<MODEL>`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Maybe.html[`Maybe<MODEL>`^].

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-data-r2dbc-postgresql/data-r2dbc-postgresql-select-return-reactive-types/src/main/java/io/rxmicro/examples/data/r2dbc/postgresql/select/returnreactivetypes/SelectSingleDataRepository.java[tag=content,indent=0]
----

* If expected an asynchronous `0`-`n` result:
.. {REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono<java.util.List<MODEL>>`^];
.. {REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Flux.html[`Flux<MODEL>`^];
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<java.util.List<MODEL>>`^];
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage<java.util.List<MODEL>>`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Single.html[`Single<java.util.List<MODEL>>`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Flowable.html[`Flowable<MODEL>`^].

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-data-r2dbc-postgresql/data-r2dbc-postgresql-select-return-reactive-types/src/main/java/io/rxmicro/examples/data/r2dbc/postgresql/select/returnreactivetypes/SelectManyDataRepository.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}data-r2dbc-postgresql-select-return-reactive-types
include::../../../../___notes/full-source-code-of-example.adoc[]

include::../../../../___notes/recompile-after-change.adoc[]
