:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[data-mongo-basic-section]]
=== Basic Usage

To use the `rxmicro.data.mongo` module in the project, the following two steps must be taken:

* Inject the `rxmicro.data.mongo` dependency to the `pom.xml` file:

[source,xml]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-mongo-basic/pom.xml[tag=content,indent=0]
----
<1> Besides the `rxmicro.data.mongo` dependency, it is also recommended to add the reactive programming library.

[NOTE]
====
Instead of adding a third-party reactive programming library, You can also use the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^] library built into the JDK, but often in practice the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^] library's features are not enough.

Therefore, it is recommended to use the {REACTOR-CORE-DOC-USER_GUIDE}[*Project Reactor*^] or the {RX-JAVA-USER-GUIDE}[*RxJava*^] library!
====

* Add the `rxmicro.data.mongo` module to the `module-info.java` descriptor:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-mongo-basic/src/main/java/module-info.java[tag=content,indent=0]
----
<1> When using a third-party reactive programming library, do not forget to add the corresponding module.

Once the `rxmicro.data.mongo` module is added, You can create a data model class and a dynamic repository:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-mongo-basic/src/main/java/io/rxmicro/examples/data/mongo/basic/model/Account.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-mongo-basic/src/main/java/io/rxmicro/examples/data/mongo/basic/DataRepository.java[tag=content,indent=0]
----
<1> In order for a standard interface to be recognized by the RxMicro framework as a dynamic repository for interaction with https://www.mongodb.com/[`Mongo DB`^],
this interface should be annotated with the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-mongo/src/main/java/io/rxmicro/data/mongo/MongoRepository.java[`@MongoRepository`^] annotation.
<2> The dynamic repository may contain methods that form a query to the https://www.mongodb.com/[`Mongo DB`^].
_(The query that used for a request for data uses the JSON format (Specialized request format for https://www.mongodb.com/[`Mongo DB`^]) and is specified in the annotation parameters.
For each operation supported by https://www.mongodb.com/[`Mongo DB`^], the RxMicro framework defines a separate annotation:
The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-mongo/src/main/java/io/rxmicro/data/mongo/operation/Find.java[`@Find`^] annotation describes the
https://docs.mongodb.com/manual/reference/method/db.collection.find/[`db.collection.find()`^]operation.)_

Since the dynamic repository is a RxMicro component, for its testing You need to use <<testing#testing-component-tests-section,the microservice component testing approach>>:

[NOTE]
====
The common approach recommended for testing dynamic repositories, that interact with https://www.mongodb.com/[`Mongo DB`^], is described in the <<data-mongo-test-templates-section>>.
====

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-mongo-basic/src/test/java/io/rxmicro/examples/data/mongo/basic/DataRepositoryTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}data-mongo-basic
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
