:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[data-mongo-partial-implementation-section]]
=== Partial Implementation

If the Mongo data repository generated by the `RxMicro Annotation Processor` contains errors, incorrect or non-optimized logic, the developer can use the `Partial Implementation` feature.

This feature allows You to implement methods for the Mongo data repository on Your own, instead of generating them by the RxMicro framework.

To activate this feature, You need to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-mongo/src/main/java/io/rxmicro/data/mongo/PartialImplementation.java[`@PartialImplementation`^]
annotation, and specify an abstract class that contains a partial implementation of method(s) for Mongo data repository:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-mongo-partial-implementation/src/main/java/io/rxmicro/examples/data/mongo/partial/implementation/DataRepository.java[tag=content,indent=0]
----
<1> Using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-mongo/src/main/java/io/rxmicro/data/mongo/PartialImplementation.java[`@PartialImplementation`^]
annotation, the `AbstractDataRepository` class is specified.

An `AbstractDataRepository` contains the following content:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-mongo-partial-implementation/src/main/java/io/rxmicro/examples/data/mongo/partial/implementation/AbstractDataRepository.java[tag=content,indent=0]
----

An abstract class that contains a partial implementation must meet the following requirements:

. The class must be an `abstract` one.
. The class must extend the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-mongo/src/main/java/io/rxmicro/data/mongo/detail/AbstractMongoRepository.java[`AbstractMongoRepository`^] one.
. The class must implement the Mongo data repository interface.
. The class must contain an implementation of all methods that are not generated automatically.

In terms of infrastructure, the repository methods generated and defined by the developer for Mongo data repository do not differ:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-mongo-partial-implementation/src/test/java/io/rxmicro/examples/data/mongo/partial/implementation/DataRepositoryTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}data-mongo-partial-implementation
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
