:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

==== Ambiguity Resolving

The alternative created by the developer can be injected by the RxMicro framework not only in the tested component, but also in any of its child components.

During such injection, the ambiguity problem may occur.

===== Ambiguity Resolving Demonstration

Let's assume there is some business service in the project:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-ambiguty-resolving/src/main/java/io/rxmicro/examples/testing/component/alternatives/ambiguty/resolving/BusinessService.java[tag=content,indent=0]
----

This business service is a dependency for three interdependent components: `Child`, `Parent`, `GrandParent`:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-ambiguty-resolving/src/main/java/io/rxmicro/examples/testing/component/alternatives/ambiguty/resolving/Child.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-ambiguty-resolving/src/main/java/io/rxmicro/examples/testing/component/alternatives/ambiguty/resolving/Parent.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-ambiguty-resolving/src/main/java/io/rxmicro/examples/testing/component/alternatives/ambiguty/resolving/GrandParent.java[tag=content,indent=0]
----

When invoking the `GrandParent.getValue` method, this method is invoked on the business services of all `Child`, `Parent` and `GrandParent` dependent components according to the dependency hierarchy:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-ambiguty-resolving/src/test/java/io/rxmicro/examples/testing/component/alternatives/ambiguty/resolving/GrandParent1Test.java[tag=content,indent=0]
----

When using an alternative, the behavior of the `GrandParent.getValue` method is changed:

[source,java]
[[GrandParent2Test-inline]]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-ambiguty-resolving/src/test/java/io/rxmicro/examples/testing/component/alternatives/ambiguty/resolving/GrandParent2Test.java[tag=content,indent=0]
----
<1> An alternative to the business service is created.
<2> Before testing, the behavior of the `getValue` method of created mock is programmed.
<3> As a result of the test, You can see that this alternative is injected into *all* `Child`, `Parent` and `GrandParent` dependent components.

include::update-final-field-tip.adoc[]

If You create 2 or more (no more than 3 in this test example) alternatives, then each alternative can be injected in a separate business component:

[source,java]
[[GrandParent3Test-inline]]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-ambiguty-resolving/src/test/java/io/rxmicro/examples/testing/component/alternatives/ambiguty/resolving/GrandParent3Test.java[tag=content,indent=0]
----
<1> The `grandParentBusinessService` alternative is injected into the `GrandParent` component, and the `businessService` alternative is injected into the `Child` component;

include::update-final-field-tip.adoc[]

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-ambiguty-resolving
include::../../___notes/full-source-code-of-example.adoc[]

===== Ambiguity Resolving Algorithm

To resolve ambiguities, the RxMicro framework uses the following algorithm:

. For each tested component, a search for injection candidates is performed.
. As a result, a map is formed with a user type as its key and a list of candidates for injection as its value.
*(The RxMicro framework does not support polymorphism rules when injecting alternatives.
Thus, the alternative of the `A` type can only be injected in the field with the `A` type)*.
. After receiving a map with candidates for injection, the RxMicro framework passes through this map.
. For each user type, a list of candidates and a list of alternatives is requested.
. If there is only one alternative and only one candidate for the user type, the RxMicro framework injects this alternative into the candidate field;
. If more than one alternative and only one candidate is found, the RxMicro framework will throw out an error;
. If there is more than one candidate and only one alternative, then:
.. The RxMicro framework analyzes the injection candidate field name:
... if the candidate field name matches the alternative field name, the RxMicro framework injects this alternative;
... if the candidate field name matches the value of the `name` parameter of the `@Alternative` annotation, the RxMicro framework injects this alternative;
... otherwise this candidate will be skipped;
.. if no alternative has been injected, the RxMicro framework injects this alternative in *all* candidate fields. +
_(This is the behavior that occurs in the <<GrandParent2Test-inline,`GrandParent2Test`>> test.)_
. If there is more than one candidate and more than one alternative, then:
.. The RxMicro framework analyzes the injection candidate field name:
... if the candidate field name matches the alternative field name, the RxMicro framework injects this alternative; +
_(In the <<GrandParent3Test-inline,`GrandParent3Test`>> test, the `grandParentBusinessService` alternative is injected in the `GrandParent` component field, because the names of the alternative and component fields are equal.)_;
... if the candidate field name matches the value of the `name` parameter of the `@Alternative` annotation, the RxMicro framework injects this alternative; +
_(In the <<GrandParent3Test-inline,`GrandParent3Test`>> test, the `businessService` alternative is injected in the `Child` component field, because the `name` parameter of the `@Alternative` annotation is equal to the `childBusinessService`._ _And in the `Child` class, the field name with the `BusinessService` type is also equal to the `childBusinessService`.)_
... otherwise this candidate will be skipped;
.. _(When more than one candidate and more than one alternative is found, it is possible that none of the alternatives will be injected.)_
