:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

==== CDI Beans Alternatives

If the developer uses the <<{cdi}#cdi-section,`rxmicro.cdi`>> module in the project, then *all* custom components are considered as beans and follow the injection algorithm for the alternatives of the RxMicro components.

_When using the `rxmicro.cdi` module, *You must always inject dependencies using the CDI mechanism only*:_

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-cdi/src/main/java/io/rxmicro/examples/testing/component/alternatives/cdi/ParentComponent.java[tag=content,indent=0]
----
<1> The `ParentComponent` class depends on the `ChildComponent` and `ChildComponentImpl` components. +
_(These dependencies are injected using the CDI mechanisms.)_

[TIP]
====
The above example is a demonstration of the features of alternatives of custom components if <<{cdi}#cdi-section,`rxmicro.cdi`>> module enabled.
That's why the `ChildComponentImpl` implementation is injected in the `ParentComponent` component.
In real projects, it's recommended to inject only interfaces to ensure greater flexibility.

_Please note that since the `ChildComponentImpl` class implements the `ChildComponent`  interface, and <<{cdi}#cdi-singletons-section, all CDI beans are singletons>>, the `childComponent` and `childComponentImpl` fields will contain references to the same `ChildComponentImpl` instance!_
====

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-cdi/src/main/java/io/rxmicro/examples/testing/component/alternatives/cdi/ChildComponentImpl.java[tag=content,indent=0]
----
<1> When creating the `ChildComponentImpl` instance, an information message is displayed in the console. +
_(This message is required to ensure that no real custom instance is created when CDI bean alternatives are used!)_

When testing, if no alternatives are created, the tested component uses the real custom component instances:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-cdi/src/test/java/io/rxmicro/examples/testing/component/alternatives/cdi/ParentComponent1Test.java[tag=content,indent=0]
----
<1> When invoking the `getEnvironment` method, the real instances of custom components are used.
<2> When starting the test, only one `ChildComponentImpl` class instance is created.

When testing, if alternatives are created, the tested component uses them instead of the real custom component instances:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-cdi/src/test/java/io/rxmicro/examples/testing/component/alternatives/cdi/ParentComponent2Test.java[tag=content,indent=0]
----
<1> When invoking the `getEnvironment` method, the alternatives of the real custom component instances are used.
<2> When starting the test, the `ChildComponentImpl` class instance is not created.

When using alternatives for complex components, it is possible to use alternatives together with real components:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-cdi/src/test/java/io/rxmicro/examples/testing/component/alternatives/cdi/ParentComponent3Test.java[tag=content,indent=0]
----
<1> When invoking the `getEnvironment` method, an alternative and a real instance are used.
<2> When starting the test, only one `ChildComponentImpl` class instance is created.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-component-alternatives-cdi
include::../../___notes/full-source-code-of-example.adoc[]
