:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

==== Components with Custom Constructors

In case the custom component does not contain an available constructor without parameters:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-withconstructor/src/main/java/io/rxmicro/examples/testing/component/alternatives/withconstructor/ParentComponent.java[tag=content,indent=0]
----
<1> The `ParentComponent` depends on the `ChildComponent`. +
_(This dependency is specified explicitly in the source code.)_
<2> When creating the `ParentComponent` class instance in the constructor, the value of the `prefix` parameter must be passed.

then the RxMicro framework won't be able to create an instance of this class.

*Therefore, the developer should create an instance of this class in one of the
following methods: {JUNIT5-DOC-ROOT-URL}api/org.junit.jupiter.api/org/junit/jupiter/api/BeforeEach.html[`@BeforeEach`^],
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeThisTest.java[`@BeforeThisTest`^] or
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeIterationMethodSource.java[`@BeforeIterationMethodSource`^]*:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-component-alternatives-withconstructor/src/test/java/io/rxmicro/examples/testing/component/alternatives/withconstructor/ParentComponentTest.java[tag=content,indent=0]
----
<1> The `ParentComponent` class instance is created inside the method annotated by the {JUNIT5-DOC-ROOT-URL}api/org.junit.jupiter.api/org/junit/jupiter/api/BeforeEach.html[`@BeforeEach`^] annotation.
<2> The `childComponent` alternative will be injected into the `ParentComponent` class instance after invoking the `beforeEach()` method and before the `Should_use_alternative()` test method.
<3> When testing the `getEnvironment` method, the alternative method is invoked instead of the real component one.

include::update-final-field-tip.adoc[]

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-simplest
include::../../___notes/full-source-code-of-example.adoc[]
