:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

==== Injection Algorithm for the Alternative of the RxMicro Component

To inject the alternative of the RxMicro component, the RxMicro framework uses the following algorithm:

. The alternative instance is created by the developer in the test code or by the testing framework automatically.
. Once all alternatives have been created, they are registered in the runtime container.
. Once all alternatives have been registered, the RxMicro framework creates an instance of the tested class.
. In the constructor or static section of the tested class, a request to the runtime container to get a reference to the RxMicro component is executed.
. Since the runtime container already contains an alternative instead of the real component, the alternative is injected into the instance of the tested class.
. After initialization, the instance of the tested class contains links to alternatives instead of the real RxMicro components.
