:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[testing-alternatives-usage-section]]
==== Alternative Usage

The alternative mechanism is a universal tool that can be applied to the simplest project, which doesn't use the `RxMicro Annotations`. +
Let's look at the project consisting of two components: the `ChildComponent` interface and the `ParentComponent` class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-alternatives-simplest/src/main/java/io/rxmicro/examples/testing/component/alternatives/simplest/ChildComponent.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-alternatives-simplest/src/main/java/io/rxmicro/examples/testing/component/alternatives/simplest/ParentComponent.java[tag=content,indent=0]
----
<1>  The `ParentComponent` class depends on the `ChildComponent`. +
_(This dependency specified explicitly in the source code.)_

When writing a unit test for the `ParentComponent`, it is necessary to replace the real `ChildComponent` with a mock.
Otherwise, it wouldn't be a unit test, but an integration one.

For this replacement, it is most convenient to use the alternative:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-alternatives-simplest/src/test/java/io/rxmicro/examples/testing/component/alternatives/simplest/ParentComponent1Test.java[tag=content,indent=0]
----
<1> The alternatives are supported by the RxMicro framework only during component unit tests or REST-based microservice tests.
Therefore, it must be declared that this test is a test of the `ParentComponent` component.
<2> The instance of the tested component will be created by the RxMicro framework automatically. +
_(The instance is created using the `reflection` mechanism, so the tested class must contain an available constructor without parameters.)_ +
In order to invoke any method of the tested component, a reference to that component is required.
Therefore, the RxMicro framework requires that the developer declares an uninitialized field of the tested component.
After starting the test, a reference to the instance of the tested component will be injected into this field using the `reflection` mechanism.
<3> In order to use the alternative mechanism, it is necessary to declare test field as  alternative by using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/Alternative.java[`@Alternative`^] annotation.
<4> Alternative is a test component with predefined behavior.
Therefore, it is necessary to define what value should be returned when invoking the `getValue` method.
<5> When testing the `getEnvironment` method, the alternative method is invoked instead of the real component one.

When using alternatives it is very convenient to use a dynamic class with programmable behavior.
For this purpose, it is very convenient to use the https://site.mockito.org/[Mockito^] framework:

[source,java]
[[InitMocks-inline]]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-alternatives-simplest/src/test/java/io/rxmicro/examples/testing/component/alternatives/simplest/ParentComponent2Test.java[tag=content,indent=0]
----

<1> To create a mock instance, it is necessary to use the {MOCKITO-DOC-ROOT-URL}org/mockito/Mock.html[`@Mock`^] annotation.
<2> In order for JUnit to handle all fields annotated by the {MOCKITO-DOC-ROOT-URL}org/mockito/Mock.html[`@Mock`^] annotation before invoking test methods, it is necessary to annotate the test class by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java[`@InitMocks`^] annotation.
<3> Before testing, it is necessary to program the behavior of the `getValue` method of the declared mock.
<4> When testing the `getEnvironment` method, the method from the alternative is invoked instead of the real component one.

[IMPORTANT]
====
When creating mock alternatives, the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java[`@InitMocks`^]
annotation should be over the `@RxMicroComponentTest` annotation (or `@RxMicroRestBasedMicroServiceTest` when writing REST-based microservice tests),
otherwise, *the alternative will be injected before creating a mock instance, (i.e. injection of the `null` instance), which will cause an error!*
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-simplest
include::../../___notes/full-source-code-of-example.adoc[]
