:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

==== Injection Algorithm for the Alternative of the Custom Component

To inject the alternative of the custom component, the RxMicro framework uses the following algorithm:

. The alternative instance is created by the developer in the test code or by the testing framework automatically.
. The RxMicro framework creates an instance of the tested class.
. In the constructor or static section of the tested class, instances of the real custom components are created.
. After initialization, the instance of the tested class contains references to the real custom components.
. After creating an instance of the tested class, the RxMicro framework injects the custom component alternatives using the  `reflection` mechanism. +
_(I.e. the alternatives replace the real instances already after creating an instance of the tested class.)_;
. After alternative injection, the instance of the tested class contains references to the alternatives of the RxMicro components instead of the real RxMicro components. +
_(The real component instances will be removed by the garbage collector later.)_;

Thus, the main difference of the injection algorithm for the custom component alternatives is that during the injection process, the real component instances are always created.

[IMPORTANT]
====
If the real component creates a reference to an external resource, then this resource *will not be* released automatically when injecting the alternative!
====

It is recommended to use the <<{cdi}#cdi-section,`rxmicro.cdi`>> module to create the custom component alternatives that work with external resources.

[IMPORTANT]
====
If the <<{cdi}#cdi-section,`rxmicro.cdi`>> module is used by the developer to create the custom component instances, then *all* custom components are injected using the algorithm of the RxMicro component alternative injection.
====
