:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[data-postgresql-basic-section]]
=== Basic Usage

To use the `rxmicro.data.sql.r2dbc.postgresql` module in the project, the following two steps must be taken:

* Inject the `rxmicro.data.sql.r2dbc.postgresql` dependency to the `pom.xml` file:

[source,xml]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-r2dbc-postgresql-basic/pom.xml[tag=content,indent=0]
----

* Add the `rxmicro.data.sql.r2dbc.postgresql` module to the `module-info.java` descriptor:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-r2dbc-postgresql-basic/src/main/java/module-info.java[tag=content,indent=0]
----

[IMPORTANT]
====
By default, the https://github.com/r2dbc/r2dbc-postgresql[reactive R2DBC PostgreSQL driver^] uses the {REACTOR-CORE-DOC-USER_GUIDE}[*Project Reactor*^] library,
so when adding the `rxmicro.data.sql.r2dbc.postgresql` module, the `reactor.core` module is automatically added and available for usage!
====

After adding the `rxmicro.data.sql.r2dbc.postgresql` module, You can create a data model class and dynamic repository:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-r2dbc-postgresql-basic/src/main/java/io/rxmicro/examples/data/r2dbc/postgresql/basic/entity/Account.java[tag=content,indent=0]
----
<1> The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data/src/main/java/io/rxmicro/data/ColumnMappingStrategy.java[`@ColumnMappingStrategy`^]
annotation sets the strategy of forming column names of the relational database table based on the analysis of the Java model class field names. +
_(Thus, the `firstName` field corresponds to the `first_name` column, and the `lastName` field corresponds to the `last_name` column.)_

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-r2dbc-postgresql-basic/src/main/java/io/rxmicro/examples/data/r2dbc/postgresql/basic/DataRepository.java[tag=content,indent=0]
----
<1> In order for a standard interface to be recognized by the RxMicro framework as a dynamic repository for interaction with https://www.postgresql.org/[`PostgreSQL DB`^],
this interface should be annotated by {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-sql-r2dbc-postgresql/src/main/java/io/rxmicro/data/sql/r2dbc/postgresql/PostgreSQLRepository.java[`@PostgreSQLRepository`^] annotation.
<2> The dynamic repository may contain methods that form a query to the https://www.postgresql.org/[`PostgreSQL DB`^]. +
_(The query that used for a request for data uses the https://en.wikipedia.org/wiki/SQL[`SQL`^] and is specified in the annotation parameters.)_

Since the dynamic repository is a RxMicro component, for its testing You need to use <<testing#testing-component-tests-section,the microservice component testing approach>>:

[NOTE]
====
The common approach recommended for testing dynamic repositories, that interact with https://www.postgresql.org/[`PostgreSQL DB`^], is described in the <<data-postgresql-test-templates-section>>.
====

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-r2dbc-postgresql-basic/src/test/java/io/rxmicro/examples/data/r2dbc/postgresql/basic/DataRepositoryTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}data-r2dbc-postgresql-basic
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
