:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[data-postgresql-partial-implementation-section]]
=== Partial Implementation

If the Postgre SQL data repository generated by the `RxMicro Annotation Processor` contains errors, incorrect or non-optimized logic, the developer can use the `Partial Implementation` feature.

This feature allows You to implement methods for the Postgre SQL data repository on Your own, instead of generating them by the RxMicro framework.

To activate this feature, You need to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-sql-r2dbc-postgresql/src/main/java/io/rxmicro/data/sql/r2dbc/postgresql/PartialImplementation.java[`@PartialImplementation`^]
annotation, and specify an abstract class that contains a partial implementation of method(s) for Postgre SQL data repository:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-data-r2dbc-postgresql/data-r2dbc-postgresql-partial-implementation/src/main/java/io/rxmicro/examples/data/r2dbc/postgresql/partial/implementation/DataRepository.java[tag=content,indent=0]
----
<1> Using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-sql-r2dbc-postgresql/src/main/java/io/rxmicro/data/sql/r2dbc/postgresql/PartialImplementation.java[`@PartialImplementation`^]
annotation, the `AbstractDataRepository` class is specified.

An `AbstractDataRepository` contains the following content:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-data-r2dbc-postgresql/data-r2dbc-postgresql-partial-implementation/src/main/java/io/rxmicro/examples/data/r2dbc/postgresql/partial/implementation/AbstractDataRepository.java[tag=content,indent=0]
----

An abstract class that contains a partial implementation must meet the following requirements:

. The class must be an `abstract` one.
. The class must extend the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-sql-r2dbc-postgresql/src/main/java/io/rxmicro/data/sql/r2dbc/postgresql/detail/AbstractPostgreSQLRepository.java[`AbstractPostgreSQLRepository`^] one.
. The class must implement the PostgreSQL data repository interface.
. The class must contain an implementation of all methods that are not generated automatically.

In terms of infrastructure, the repository methods generated and defined by the developer for Postgre SQL data repository do not differ:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-data-r2dbc-postgresql/data-r2dbc-postgresql-partial-implementation/src/test/java/io/rxmicro/examples/data/r2dbc/postgresql/partial/implementation/DataRepositoryTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-data-r2dbc-postgresql/data-r2dbc-postgresql-partial-implementation
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
