[[appendices-faq-section]]
=== Appendix A: FAQ

This section covers a list of possible questions that you can ask yourself when you use the RxMicro framework.

==== Does RxMicro modify my byte code?

No.
Your classes are your classes.
RxMicro does not transform classes or modify the Java byte code you write.
RxMicro produces additional classes only.

==== Can RxMicro be used for purposes other than Microservices?

Yes.
RxMicro is very modular and you can choose to use any module you need.

==== Why I receive `class not found` error?

When you use RxMicro framework you can receive one of the following errors:

* `Class rxmicro.$$RestControllerAggregatorImpl not found`;
* `Class rxmicro.$$RestClientFactoryImpl not found`;
* `Class rxmicro.$$RepositoryFactoryImpl not found`;
* `Class rxmicro.$$BeanFactoryImpl not found`;

These errors mean that `RxMicro Annotation Processor` does not generate the required additional classes.

To fix it, please verify that:

. `pom.xml` for your project contains <<{quick-start}#quick-start-maven-compiler-plugin-settings-section,the valid settings for `maven-compiler-plugin`>> and
. You executed command: `mvn clean compile`!

==== Why I receive `The Kotlin standard library is not found in the module graph` error?

Sometimes this issue occurs during the work with java code using IntelliJ IDEA.
To fix this issue it is necessary to rebuild your project: `Build` -> `Rebuild project`.

==== Why I receive `java.lang.NullPointerException: autoRelease couldn't be null` error during unit testing?

If you declare an alternative of the `HttpClientFactory` mock and don't configure it this error can happen.

To fix this issue it is necessary to configure the `@Mock` annotation:

[source,java]
----
@Alternative
@Mock(answer = Answers.RETURNS_DEEP_STUBS) // <1>
private HttpClientFactory httpClientFactory;
----
<1> Set `Answers.RETURNS_DEEP_STUBS` as answer value.



