:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[rest-controller-rqeuest-id-section]]
=== Идентификатор запроса

==== Базовые правила

Для отслеживания HTTP запроса при использовании микросервисной архитектуры, RxMicro предоставляет функцию идентификации HTTP запроса.

Если текущий запрос идентифицирован, то предоставленный уникальный идентификатор используется в процессе жизни текущего запроса.
Если запрос не идентифицирован, то RxMicro генерирует уникальный идентификатор, который в дальнейшем используется в процессе жизни текущего запроса.

Для хранения идентификатора запроса используется вспомогательный HTTP заголовок
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java#L187[`Request-Id`^].

Если идентификатор HTTP запроса необходим для бизнес логики, то необходимо создать отдельное поле в Java модели HTTP запроса:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-request-id/src/main/java/io/rxmicro/examples/rest/controller/request/id/model/Request.java[tag=content,indent=0]
----
<1> Для удобства вместо указания HTTP заголовка с помощью аннотации `@Header` и имени
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java#L187[`Request-Id`^]
<2> можно использовать специальную аннотацию {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestId.java[`@RequestId`^], которая является альтернативой конфигурации: `@Header(HttpHeaders.REQUEST_ID)`.

Объявив поле в Java модели HTTP запроса можно использовать его значение в обработчике:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-request-id/src/main/java/io/rxmicro/examples/rest/controller/request/id/MicroService.java[tag=content,indent=0]
----
<1> Вывод на консоль значения текущего идентификатора запроса.

Следующий тест описывает основные требования к поведению функции идентификации запроса:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-request-id/src/test/java/io/rxmicro/examples/rest/controller/request/id/MicroServiceTest.java[tag=content,indent=0]
----
<1> Для HTTP запросов без идентификатора RxMicro должен генерировать уникальный идентификатор автоматически.
_(Данный идентификатор может быть использован в теле обработчика HTTP запроса.)_
<2> Каждый HTTP ответ должен содержать обязательный HTTP заголовок
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java#L187[`Request-Id`^]
со значением сгенерированного идентификатора запроса. +
_(Если параметр конфигурации `RestServerConfig.returnGeneratedRequestId = false`, HTTP ответ не будет содержать заголовок `Request-Id`.)_
<3> Если текущий HTTP запрос уже содержит идентификатор, то RxMicro должен использовать его вместо генерации нового значения.
<4> Установленный клиентом идентификатор может быть использован в теле обработчика HTTP запроса.
<5> Каждый HTTP ответ должен содержать обязательный HTTP заголовок
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java#L187[`Request-Id`^]
со значением определенного клиентом идентификатора запроса. +
_(Если параметр конфигурации `RestServerConfig.returnGeneratedRequestId = false`, HTTP ответ не будет содержать заголовок `Request-Id`.)_

[IMPORTANT]
====
Для удобства тестирования, если микросервис запускается автоматически тестом, то каждому HTTP запросу присваивается тестовый идентификатор.

По умолчанию значение тестового идентификатора HTTP запросов равно:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/local/component/impl/TestRequestIdGenerator.java#L27[`TestRequestId`^].
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-request-id
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Поддерживаемые типы генераторов

RxMicro поддерживает следующие типы генераторов идентификатора HTTP запроса.

.Тип генератора HTTP запрос и его класс-реализация.
|===
|*Тип*|*Класс-реализация*|*Описание*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RequestIdGeneratorType.java#L25[`FASTER_BUT_UNSAFE`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/local/component/impl/FasterButUnSafeRequestIdGenerator.java#L35[`FasterButUnSafeRequestIdGenerator`^]
|*Генерирует уникальные идентификаторы только в рамках запуска одной `JVM`.*

Использует счетчик со случайным инкрементом.

(_Используется по-умолчанию_).

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RequestIdGeneratorType.java#L27[`SAFE_BUT_SLOWER`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/local/component/impl/SafeButSlowerRequestIdGenerator.java#L29[`SafeButSlowerRequestIdGenerator`^]
|*Генерирует уникальные идентификаторы независимо от запуска `JVM`.*

В качестве уникального значения использует
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/UUID.html#randomUUID()[`UUID.randomUUID()`^].

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RequestIdGeneratorType.java#L29[`FOR_TESTS_ONLY`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/local/component/impl/TestRequestIdGenerator.java#L25[`TestRequestIdGenerator`^]
|Рекомендован *только для тестового окружения*.

По умолчанию автоматически активируется для тестового окружения.
|===

Для изменения типа генератора идентификаторов запроса, необходимо использовать конфигурационный класс
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RestServerConfig.java[`RestServerConfig`^]:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-request-id/src/main/java/io/rxmicro/examples/rest/controller/request/id/Launcher.java[tag=content,indent=0]
----

<1> Установка значения `SAFE_BUT_SLOWER` в качестве типа генератора идентификаторов HTTP запросов.

<<<

==== Сравнение производительности типов генераторов

Исходный код теста производительности:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}benchmarks/benchmark-rxmicro-core/src/main/java/io/rxmicro/benchmark/rxmicro/core/server/RequestIdGeneratorBenchmark.java[tag=content,indent=0]
----

Результаты тестирования производительности:

[source,txt]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}benchmarks/_results/rxmicro-core-RequestIdGeneratorBenchmark.txt[]
----

[IMPORTANT]
====
Результаты тестирования показывают, что производительность компонента `FasterButUnSafeRequestIdGenerator` *в 6 раз лучше*, чем компонента `SafeButSlowerRequestIdGenerator`!
====
