:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[testing-BlockingHttpClient-settings-section]]
==== The `BlockingHttpClient` Settings

The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] component, which is used for writing REST-based microservices and integration tests, is configured by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClientSettings.java[`@BlockingHttpClientSettings`^] annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-integration-basic/src/test/java/io/rxmicro/examples/testing/integration/basic/MicroServiceIntegrationTestSettings.java[tag=content,indent=0]
----
<1> The `schema` parameter allows You to specify the HTTP protocol schema.
<2> The `host` parameter allows You to specify the remote host on which the microservice is running. +
_(This parameter allows performing integration testing for remote microservices.)_
<3> The `port` parameter allows You to specify the static connection port.
<4> The `randomPortProvider` parameter allows You to specify the dynamic connection port. +
_(The port will be read from the static final variable of the current class with the `SERVER_PORT` name.)_ +
_(The `port` and `randomPortProvider` parameters are mutually exclusive.)_
<5> The `versionValue` allows You to specify <<{rest-controller}#rest-controller-versioning-section,the microservice version>>.
<6> The `versionStrategy` parameter allows specifying <<{rest-controller}#rest-controller-versioning-section,the versioning strategy>>, which is used in the tested microservice.
<7> The `requestTimeout` parameter allows specifying the request timeout.
<8> The `followRedirects` parameter returns follow redirect option for the blocking HTTP client

