:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[testing-integration-tests-docker-section]]
==== The `docker` Usage

To perform the integration testing of microservices, it is convenient to use the `docker`.

This demonstration example uses the `docker` image: {RX-MICRO-DOCKER_HUB_ROOT}simple-hello-world[`rxmicro/simple-hello-world`^].

[TIP]
====
The source code of the project, on the basis of which this `docker` image was built, is available at the following link:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}docker-image-hello-world-microservice[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}docker-image-hello-world-microservice`^]
====

To start the `docker` containers in the integration test it is convenient to use the  https://www.testcontainers.org/[`Testcontainers`^] Java library:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-integration-docker/src/it/java/io/rxmicro/examples/testing/integration/docker/HelloWorldMicroService_IT.java[tag=content,indent=0]
----
<1> The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroIntegrationTest.java[`@RxMicroIntegrationTest`^]
annotation informs the RxMicro framework that this test is an integration test.
<2> The {TESTCONTAINERS-JUNIT-DOC-ROOT-URL}org/testcontainers/junit/jupiter/Testcontainers.java[`@Testcontainers`^]
annotation activates the start and stop of the `docker` containers to be used in this test.
<3> The {TESTCONTAINERS-JUNIT-DOC-ROOT-URL}org/testcontainers/junit/jupiter/Container.java[`@Container`^]
annotation indicates the `docker` container to be used in this test.
_(To start microservices in the `docker` containers the `docker-compose` utility is used.)_
<4> During the testing process, ensure that the tested microservice returns the `"Hello World!"` message.

[NOTE]
====
To start the REST-based microservice in the `docker` container, the following configuration file for the `docker-compose` utility is used:

[source,yaml]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-integration-docker/docker-compose.yml[]
----
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-integration-docker
include::../../___notes/full-source-code-of-example.adoc[]
