:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[testing-integration-tests-docker-section]]
==== Использование `docker`

Для выполнения интеграционного тестирования микросервисов удобно использовать `docker`.

Данный демонстрационный пример использует `docker` образ:
https://hub.docker.com/repository/docker/rxmicro/simple-hello-world[`rxmicro/simple-hello-world`^].

[TIP]
====
Исходный код проекта, на базе которого был собран данный `docker` образ, доступен по ссылке:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}docker-image-hello-world-microservice[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}docker-image-hello-world-microservice`^]
====

Для запуска `docker` контейнеров в интеграционном тесте удобно использовать Java библиотеку https://www.testcontainers.org/[`Testcontainers`^]:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-integration-docker/src/it/java/io/rxmicro/examples/testing/integration/docker/HelloWorldMicroService_IT.java[tag=content,indent=0]
----
<1> Аннотация {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroIntegrationTest.java[`@RxMicroIntegrationTest`^]
информирует the RxMicro framework о том, что данный тест является интеграционным тестом.
<2> Аннотация {TESTCONTAINERS-JUNIT-DOC-ROOT-URL}org/testcontainers/junit/jupiter/Testcontainers.java[`@Testcontainers`^]
активирует запуск и остановку `docker` контейнеров, которые будут использоваться в данном тесте.
<3> Аннотация {TESTCONTAINERS-JUNIT-DOC-ROOT-URL}org/testcontainers/junit/jupiter/Container.java[`@Container`^]
указывает на `docker` контейнер, который будет использован в данном тесте.
_(Для запуска микросервисов в `docker` контейнерах используется утилита `docker-compose`.)_
<4> В процессе тестирования убеждаемся, что тестируемый микросервис возвращает сообщение `"Hello World!"`.

[NOTE]
====
Для запуска REST-based микросервиса в `docker` контейнере используется следующий конфигурационный файл для утилиты `docker-compose`:

[source,yaml]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-integration-docker/docker-compose.yml[]
----
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-integration-docker
include::../../___notes/full-source-code-of-example.adoc[]
