// suppress inspection "AsciiDocLinkResolve" for whole file
:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

==== Logger Configuration
===== Using Configuration File

[[core-logger-config-file-inline]]
The main configuration file of the `java.logging` logger is the `jul.properties` classpath resource.

[NOTE]
====
If classpath contains the `jul.test.properties` resource, then this resource overrides *all* configurations of the `jul.properties` resource.

This function allows configuring the logger for a test environment.
====

The `jul.properties` classpath resource must contain a configuration http://tutorials.jenkov.com/java-logging/configuration.html[in the standard format for the `java.logging` module^].

Example of logger configuration:

[source,properties]
----
.level=INFO
io.rxmicro.config.level=DEBUG
----

[IMPORTANT]
====
The `rxmicro.logger` module supports all logging levels from the following sets: `{OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL}` and `{OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL}`.

Therefore, in the `jul.properties` configuration file You can use any logging level.
When activating the `java.logging` logger, the RxMicro framework automatically converts levels from a set of `{OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL}` into `{OFF, SEVERE, WARNING, INFO, FINE, FINEST, ALL}`.

This option makes it possible to use unsupported but widely used in other logging frameworks logging levels for the `java.logging` logger.
====

===== Using Environment Variables And Java System Properties

Besides configuration file (`jul.properties`) the `rxmicro.logger` module supports configuration using environment variables and java system properties.

If Your runtime contains an environment variable and (or) java system property with name that starts with `logger.` phrase, the `rxmicro.logger` module interprets it as configuration.
For example to enable `TRACE` logger level for `MicroServiceLauncher` it is necessary to provide one of the following configurations:

[source,bash]
----
export logger.io.rxmicro.rest.server.level=TRACE

java -p lib:. -m module/package.MicroServiceLauncher
----

or

[source,bash]
----
java -p lib:. -Dlogger.io.rxmicro.rest.server.level=TRACE -m module/package.MicroServiceLauncher
----

===== Default Reading Order of Config Sources.

By default, the `rxmicro.logger` module reads configuration sources in the following order (From the lowest to the highest priority):

* Default config.
* Configuration from the `jul.properties` classpath resource if the resource found.
* Configuration from the `jul.test.properties` classpath resource if the resource found.
* Configuration from the environment variables if any environment variable with `logger.` prefix found.
* Configuration from the java system properties if any java system property with `logger.` prefix found.
