:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[data-postgresql-partial-implementation-section]]
=== Partial Implementation

Если генерируемый by the `RxMicro Annotation Processor` PostgreSQL data repository содержит ошибки, некорректную или неоптимизированную логику, то разработчик может использовать the `Partial Implementation` feature.

Данная feature позволяет реализовывать методы обработки данных для PostgreSQL data repository самостоятельно, вместо того, чтобы они были сгененированы by the RxMicro framework.

Для активации данной feature необходимо с помощью аннотации
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-sql-r2dbc-postgresql/src/main/java/io/rxmicro/data/sql/r2dbc/postgresql/PartialImplementation.java[`@PartialImplementation`^]
указать абстрактный класс, который содержит реализацию методов обработки данных для PostgreSQL data repository:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-r2dbc-postgresql-partial-implementation/src/main/java/io/rxmicro/examples/data/r2dbc/postgresql/partial/implementation/DataRepository.java[tag=content,indent=0]
----
<1> C помощью аннотации
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-sql-r2dbc-postgresql/src/main/java/io/rxmicro/data/sql/r2dbc/postgresql/PartialImplementation.java[`@PartialImplementation`^]
указывается абстрактный класс `AbstractDataRepository`.

Абстрактный класс `AbstractDataRepository` содержит следующий контент:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-r2dbc-postgresql-partial-implementation/src/main/java/io/rxmicro/examples/data/r2dbc/postgresql/partial/implementation/AbstractDataRepository.java[tag=content,indent=0]
----

и должен удовлетворять следующим требованиям:

. Класс должен быть абстрактным.
. Класс должен наследоваться от класса
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-data-sql-r2dbc-postgresql/src/main/java/io/rxmicro/data/sql/r2dbc/postgresql/detail/AbstractPostgreSQLRepository.java[`AbstractPostgreSQLRepository`^].
. Класс должен реализовывать интерфейс of the PostgreSQL data repository.
. Класс должен содержать реализацию всех методов, которые не генерируются автоматически.

С точки зрения инфраструктуры генерируемые и определенные разработчиком методы обработки данных для PostgreSQL data repository ничем не отличаются:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/data-r2dbc-postgresql-partial-implementation/src/test/java/io/rxmicro/examples/data/r2dbc/postgresql/partial/implementation/DataRepositoryTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}data-r2dbc-postgresql-partial-implementation
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
