:FRAGMENT_RELATIVE_DIR: ../../../
include::../../../___fragment-settings.adoc[]

[[core-config-order-settings]]
===== Custom Reading Order of Config Sources.

To change the order of the configuration reading it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L121[`Configs.Builder.withOrderedConfigLoadSources`^] method:

[source,java]
----
public static void main(final String[] args) {
    new Configs.Builder()
            .withOrderedConfigLoadSources(
                    SEPARATE_CLASS_PATH_RESOURCE, // <1>
                    RXMICRO_CLASS_PATH_RESOURCE   // <2>
            )
            .build();
    start(MicroService.class, args);
}
----
<1> First, it is necessary to read the configuration from the `${name-space}.properties` classpath resource (In our case, it's a `http-server.properties`)
<2> and then from the `rxmicro.properties` classpath resource.

Thus, the order of the configuration reading from classpath resources has been changed in comparison with the
<<core-config-order-default-section, default order>>.

When starting the microservice, the settings from the `http-server.properties` classpath resource will be overwritten by the settings from the `rxmicro.properties` classpath resource:

[source,text]
----
2020-01-11 16:52:26.797 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at localhost:9090 using NETTY transport in 500 millis. # <1>
----
<1> HTTP server has started at `localhost:9090`.

[IMPORTANT]
====
The
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L118[`Configs.Builder.withOrderedConfigLoadSources`^]
method allows not only to change the order of reading the configuration sources, but also to activate/deactivate the sources.

*In the above example, the RxMicro framework will ignore any configuration sources except classpath resources!*
====

The
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L118[`Configs.Builder.withOrderedConfigLoadSources`^]
method is universal.

The RxMicro framework also provides other additional methods:

* {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L124[`Configs.Builder.withAllConfigLoadSources`^] - activation of all configuration types in the order given by the list:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/ConfigLoadSource.java[`ConfigLoadSource`^]

* {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L129[`Configs.Builder.withContainerConfigSources`^] - this combination is recommended for microservices operating in https://www.docker.com/[docker^] or https://kubernetes.io/[kubernetes^].

[TIP]
====
The
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L124[`Configs.Builder.withAllConfigLoadSources`^]
method was used to activate the reading of configurations from properties files in the <<core-config-properties-files-section>> subsection.

If You plan to use only `properties` files, it is recommended to specify only these types, excluding all other types:

[source,java]
----
public static void main(final String[] args) {
    new Configs.Builder()
            .withOrderedConfigLoadSources(
                    RXMICRO_FILE_AT_THE_HOME_DIR,    // <1>
                    RXMICRO_FILE_AT_THE_CURRENT_DIR, // <2>
                    SEPARATE_FILE_AT_THE_HOME_DIR,   // <3>
                    SEPARATE_FILE_AT_THE_CURRENT_DIR // <4>
            )
            .build();
    start(MicroService.class, args);
}
----
<1> Activation of configuration reading from the `$HOME/rxmicro.properties` file.
<2> Activation of configuration reading from the `rxmicro.properties` file in the current directory.
<3> Activation of configuration reading from the `$HOME/${name-space}.properties` files (for example, `http-server.properties`).
<4> ctivation of configuration reading from the `${name-space}.properties` files (for example, `http-server.properties`) in the current directory.

*The order of reading is set by the argument order of the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L118[`Configs.Builder.withOrderedConfigLoadSources`^]* method
====

[IMPORTANT]
====
*If You know exactly which configuration sources should be used by the microservice, ALWAYS specify them explicitly!*

*With this approach, at the microservice starting, the RxMicro framework won't try to search for non-existent sources, spending precious microseconds!*
====
