:FRAGMENT_RELATIVE_DIR: ../../../
include::../../../___fragment-settings.adoc[]

[[core-config-order-default-section]]
===== Default Reading Order of Config Sources.

By default, the RxMicro framework reads configuration sources
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L54[in the following order^]:

* Configuration using {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/DefaultConfigValue.java[`@DefaultConfigValue`^] annotations;
* Configuration using the `rxmicro.properties` classpath resource;
* Configuration using the separate (`${name-space}.properties`) classpath resource;
* Configuration using environment variables;
* Configuration using Java system variables;

Thus, if there are two classpath resources for a microservice:

The `rxmicro.properties` resource with the following content:

[source,properties]
----
http-server.port=9090
http-server.host=localhost
----

and the `http-server.properties` resource with the following content:

[source,properties]
----
port=9876
----

then the result will be as follows:

[source,text]
----
2020-01-11 16:52:26.797 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at localhost:9876 using NETTY transport in 500 millis. # <1>
----
<1> HTTP server has started at `localhost:9876`.

The configuration reading algorithm for the above example is as follows:

. By default, the HTTP server should start at `0.0.0.0:8080`.
. But in the `rxmicro.properties` classpath resource there is a different IP address and port: `localhost:9090`.
. If the `http-server.properties` classpath resource had not existed, the HTTP server would have run at `localhost:9090`.
. But in the `http-server.properties` classpath resource it is specified the `9876` port.
. Therefore, when starting, the IP address is inherited from the `rxmicro.properties` resource and the overridden port value is read from the `http-server.properties` resource. +
_(This behavior corresponds to the order of reading the default configurations.)_
