:FRAGMENT_RELATIVE_DIR: ../../../
include::../../../___fragment-settings.adoc[]

===== Logging the Config Reading Process

To debug the configuration reading process You can activate the <<core-logger-config-file-inline,logger>>:

[source,properties]
----
.level=INFO
io.rxmicro.config.level=DEBUG # <1>
----
<1> For all classes and subpackages of the `io.rxmicro.config` package activate the `DEBUG`(`FINE`) logging level.

After activating the logger, the start of the microservice with default settings will be as follows:

[source,text,subs="verbatim,quotes"]
----
[DEBUG] Discovering properties for 'rest-server' namespace from sources: [*DEFAULT_CONFIG_VALUES*, *RXMICRO_CLASS_PATH_RESOURCE*, *SEPARATE_CLASS_PATH_RESOURCE*, *ENVIRONMENT_VARIABLES*, *JAVA_SYSTEM_PROPERTIES*]

[DEBUG] Classpath resource not found: *rest-server.properties*

[DEBUG] All properties discovered for 'rest-server' namespace # <1>

[DEBUG] Discovering properties for 'http-server' namespace from sources: [*DEFAULT_CONFIG_VALUES*, *RXMICRO_CLASS_PATH_RESOURCE*, *SEPARATE_CLASS_PATH_RESOURCE*, *ENVIRONMENT_VARIABLES*, *JAVA_SYSTEM_PROPERTIES*]

[DEBUG] Discovered properties from *'rxmicro.properties'* classpath resource: [http-server.port=9090, http-server.host=localhost] # <2>

[DEBUG] Discovered properties from *'http-server.properties'* classpath resource: [port=9876] # <3>

[DEBUG] All properties discovered for 'http-server' namespace

[DEBUG] Discovering properties for 'netty-rest-server' namespace from sources: [*DEFAULT_CONFIG_VALUES*, *RXMICRO_CLASS_PATH_RESOURCE*, *SEPARATE_CLASS_PATH_RESOURCE*, *ENVIRONMENT_VARIABLES*, *JAVA_SYSTEM_PROPERTIES*]

[DEBUG] Classpath resource not found: *netty-rest-server.properties*

[DEBUG] All properties discovered for 'netty-rest-server' namespace # <4>

[INFO] Server started at *0.0.0.0:9876* using NETTY transport in 500 millis. # <5>
----
<1> There is no configuration customization for the `rest-server` namespace, so the default configuration will be used.
<2> Configuration reading for the `http-server` namespace from the `rxmicro.properties` classpath resource (Read values: `http-server.port=9090`, `http-server.host=localhost`).
<3> Configuration reading for the `http-server` namespace from the `http-server.properties` classpath resource (Read value: `port=9876`).
<4> There is no configuration customization for the `netty-rest-server` namespace, so the default configuration will be used.
<5> HTTP server has started at `localhost:9876`.

*Additional debugging information will show the order of reading the configuration sources and overriding the configuration parameter values!*
