:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

For a successful tests launch while building a project with `maven` it is necessary to update `maven-surefire-plugin`:

[source,xml]
----
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>${maven-surefire-plugin.version}</version> <!--1-->
    <configuration>
        <properties>
            <!-- https://junit.org/junit5/docs/5.5.1/api/org/junit/jupiter/api/Timeout.html -->
            <configurationParameters>
                junit.jupiter.execution.timeout.default = 60                <!--2-->
                junit.jupiter.execution.timeout.mode = disabled_on_debug    <!--3-->
                junit.jupiter.execution.parallel.enabled = false            <!--4-->
            </configurationParameters>
        </properties>
    </configuration>
</plugin>
----
<1> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-surefire-plugin[Last stable version of `maven-surefire-plugin`^]. +
_(The plugin version must be `2.22.1` or higher, otherwise `maven` will ignore the tests!.)_
<2> In case of an error in the code which uses reactive programming, an infinite function execution may occur.
In order to detect such cases, it is necessary to set a global timeout for all methods in the tests.
_(By default, timeout is set in seconds.
More detailed information on timeouts configuration is available {JUNIT5-DOC-ROOT-URL}user-guide/#writing-tests-declarative-timeouts[in official JUnit5 documentation^].)_
<3> While debugging, timeouts can be turned off.
<4> This property is useful for the tests debugging from IDE or `maven`. +
_(By setting this property the speed of test performance will decrease, so use this property for debugging only!)_
