:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-cors-section]]
=== `CORS` Support

The RxMicro framework supports the https://developer.mozilla.org/ru/docs/Web/HTTP/CORS[`Cross Origin Resource Sharing (CORS)`^].

To activate this function it is necessary to add the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/feature/EnableCrossOriginResourceSharing.java[`@EnableCrossOriginResourceSharing`^] annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-cors/src/main/java/io/rxmicro/examples/rest/controller/cors/MicroService.java[tag=content,indent=0]
----
<1> The https://developer.mozilla.org/ru/docs/Web/HTTP/CORS[`Cross Origin Resource Sharing (CORS)`^] feature is activated for *all* handlers of the specified REST controller.

When activating this feature, the RxMicro framework automatically adds a standard handler:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-cors/src/test/java/io/rxmicro/examples/rest/controller/cors/MicroServiceTest.java[tag=content,indent=0]
----
<1> The standard handler can handle `OPTIONS` requests with additional HTTP headers.

[NOTE]
====
For more information on the https://developer.mozilla.org/ru/docs/Web/HTTP/CORS[`Cross Origin Resource Sharing (CORS)`^] support, check out the following examples:

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-controller-cors/src/main/java/io/rxmicro/examples/rest/controller/cors/ComplexCORSMicroService.java[`ComplexCORSMicroService.java`^]

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-controller-cors/src/test/java/io/rxmicro/examples/rest/controller/cors/ComplexCORSMicroServiceTest.java[`ComplexCORSMicroServiceTest.java`^]
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-cors
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
