:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-errors-section]]
=== Exceptions Usage

Each reactive type of returned request handler result supports two states:

* Successful completion signal.
* Completion signal with an error.

The feature of a successful completion signal consists in its uniqueness, i.e. if such a signal has occurred, it ensures successful completion of the business task.
The feature of a completion signal with an error is that different types of errors may occur during the execution of the business task:

* validation error;
* data source connection error;
* computational algorithm error, etc.

It means that each request handler can return *only one successful result and several results with errors*.

So the RxMicro framework introduces the `error` concept.
An error means any unsuccessful result.

*For simplified error handling, the RxMicro framework recommends using HTTP status codes for each error category!*

In case the HTTP code status is not sufficient, the RxMicro framework recommends using an additional text description.

[[rest-controller-errors-model-inline]]
For this purpose, the RxMicro framework defines a standard JSON model which is returned in case of any error:

[source,json]
----
{
  "message": "Not Found"
}
----

Thus, in case of an error, the client determines the error category basing on HTTP status code analysis.
For more information, the client should analyze a text message.

<<<

==== Basic Class of Exceptions

When handling an HTTP request, the RxMicro framework defines the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/error/HttpErrorException.java[`HttpErrorException`^] base exception class.

*All custom exception types must extend this base class!*

[IMPORTANT]
====
For all child classes which extend the `HttpErrorException` class, when creating an exception instance *the stack trace is not filled*, as this information is redundant.

_(This behavior is achieved by using the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/RuntimeException.html#%3Cinit%3E(java.lang.String,java.lang.Throwable,boolean,boolean)[`protected RuntimeException(String, Throwable, boolean, boolean)`^] protected constructor.)_
====

<<<

==== Using the User Defined Exceptions

If the request handler must return an HTTP status code other than the successful one, a separate exception class must be created:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-errors/src/main/java/io/rxmicro/examples/rest/controller/errors/CustomNotFoundException.java[tag=content,indent=0]
----

<1> The custom exception class must extend the `HttpErrorException` class.
<2> Each class must define the static `int STATUS_CODE` field with a status code that identifies the error category.
_(This name is constant and is used by the <<{project-documentation}#project-documentation-custom-error-requirements,`rxmicro.documentation`>> module when building the project documentation.)_
<3> If You want to display a detailed message to the client, You need to add the constructor parameter. +
_(If You want to return to the client only the HTTP status without the HTTP body, then create a constructor without parameters.)_

[TIP]
====
*The RxMicro framework does not support `null` as a business value!*

So if the `null` value is passed to the exception constructor as a message, then the RxMicro framework will return an HTTP response without a message body! +
_(i.e. the `new CustomNotFoundException(null)` and `new CustomNotFoundException()` constructions are identical in terms of the RxMicro framework!)_
====

You can use two approaches to return an HTTP status code other than successful one:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-errors/src/main/java/io/rxmicro/examples/rest/controller/errors/MicroService.java[tag=content,indent=0]
----

<1> Use the reactive type method to generate a completion signal with an error.
<2> Create and throw an exception instance.

From the client's point of view, the two above-mentioned approaches are exactly the same:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-errors/src/test/java/io/rxmicro/examples/rest/controller/errors/MicroServiceTest.java[tag=content,indent=0]
----
<1> As a detailed error message, the message passed to the exception constructor is returned. +
_(The `jsonErrorObject("...")` utility method is synonymous with the `jsonObject("message", "...")` method.)_
<2> The returned status code equals the status code defined in the exception class in the `int STATUS_CODE` field.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-errors
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Error Signal Generation Methods

To return an HTTP response with an error it is necessary to use the appropriate reactive type method to generate the error signal.

.Error signal generation method.
|===
|*Reactive type*|*Static method*

|`CompletableFuture`
|{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html#failedFuture(java.lang.Throwable)[`CompletableFuture.failedFuture`^]

|`CompletionStage`
|{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html#failedStage(java.lang.Throwable)[`CompletableFuture.failedStage`^]

|`Mono`
|{REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html#error-java.lang.Throwable-[`Mono.error`^]

|`Completable`
|{RX-JAVA-DOC-ROOT-URL}io/reactivex/Completable.html#error-java.lang.Throwable-[`Completable.error`^]

|`Single`
|{RX-JAVA-DOC-ROOT-URL}io/reactivex/Single.html#error-java.lang.Throwable-[`Single.error`^]

|`Maybe`
|{RX-JAVA-DOC-ROOT-URL}io/reactivex/Maybe.html#error-java.lang.Throwable-[`Maybe.error`^]
|===

[TIP]
====
Using the error signal generation method instead of throwing an exception instance requires writing more code but saves processor resources!

So it's up to You to determine which method to use in Your project!
====

==== Predefined Classes of Exceptions

The RxMicro framework defines the following predefined exception classes:

.List of predefined exception classes.
[cols="3,1,6"]
|===
|*Exception class*|*Status code*|*Description*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/error/RedirectException.java[`RedirectException`^]
|`300..399`
|A base class to inform the client about the need to perform `redirect`.

_(Instead of using a base class, it is recommended to use one of the following child ones: `TemporaryRedirectException` or `PermanentRedirectException`.)_

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/error/TemporaryRedirectException.java[`TemporaryRedirectException`^]
|https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307[`307`^]
|A class that signals the need to perform <<rest-controller-redirect-section,`Temporary Redirect`.>>

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/error/PermanentRedirectException.java[`PermanentRedirectException`^]
|https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308[`308`^]
|A class that signals the need to perform <<rest-controller-redirect-section,`Permanent Redirect`.>>

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/error/ValidationException.java[`ValidationException`^]
|https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400[`400`^]
|A class signaling that the client has sent <<{validation}#validation-section,a bad request.>>

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/error/InternalHttpErrorException.java[`InternalHttpErrorException`^]
|https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500[`500`^]
|A class signaling that an internal error has occurred during execution.

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-validation/src/main/java/io/rxmicro/validation/UnexpectedResponseException.java[`UnexpectedResponseException`^]
|https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500[`500`^]
|A class signaling that the <<{validation}#validation-response-section,HTTP response, generated by the request handler, contains validation errors.>>

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http-client/src/main/java/io/rxmicro/http/client/HttpClientTimeoutException.java[`HttpClientTimeoutException`^]
|https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504[`504`^]
|A class signaling that the HTTP client didn't receive a response from the server in given time.

|===
