:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-headers-basic]]
=== HTTP Headers Support

include::../_rest/___http-headers-basic-rules.adoc[]

After creating model classes, it is necessary to create a request handler that uses the following models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-headers/src/main/java/io/rxmicro/examples/rest/controller/headers/SimpleUsageMicroService.java[tag=content,indent=0]
----
<1> If a separate model class has been created for an HTTP request, then this class must be passed to the method parameter that handles the HTTP request.
<2> Besides supporting HTTP request model classes, the RxMicro framework supports request handlers that accept HTTP headers as method parameters.
<3> To define a common naming strategy for all HTTP headers which are passed as method parameters, the request handler must be annotated by the `@HeaderMappingStrategy` annotation.
<4> To declare a method parameter as an HTTP header field, use the `@Header` annotation.
<5> Using the `@Header` annotation, it is possible to specify an HTTP header name that does not correspond to the strategy used, declared by the `@HeaderMappingStrategy` annotation.

include::../___notes/model-class-intead-of-method-parameters-note.adoc[tags=**;!path-variables;!params;!all]

Despite the different approaches to HTTP header handling support, from the client's point of view the two above-mentioned handlers are absolutely equal:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-headers/src/test/java/io/rxmicro/examples/rest/controller/headers/SimpleUsageMicroServiceTest.java[tag=content,indent=0]
----

<1> When performing a request to different URL Paths, the result is the same.
<2> The `Endpoint-Version` name corresponds to the `endpointVersion` field of the request model. +
_(This correspondence is formed basing on the default strategy use, which is defined by the `@HeaderMappingStrategy` annotation.)_
<3> The `UseProxy` name corresponds to the `useProxy` field of the request model, since this name is specified in the `@Header` annotation.
<4> After executing the request in the resulting HTTP response, the `Endpoint-Version` and `UseProxy` headers are equal to `v1` and `true` respectively.
_(The handler returns the same header values it received from an HTTP request.)_

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-headers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Supported Data Types

include::../_rest/___header-types.adoc[]

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-headers/src/main/java/io/rxmicro/examples/rest/controller/headers/ListHeaderMicroService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-headers/src/test/java/io/rxmicro/examples/rest/controller/headers/ListHeaderMicroServiceTest.java[tag=content,indent=0]
----

<1> If the HTTP header is a list of values, the list elements are transferred via the HTTP protocol as a string separated by the `|` symbol. +
_(For HTTP response headers it is possible to activate the <<rest-controller-headers-repeating,repeating headers mode.>>)_
<2> Besides transferring the list using a comma-separated string, the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] component also supports: +
an array of enumerations,
<3> an array of string values,
<4> a list of enumerations,
<5> a list of string values. +
_(The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^]
component converts these types to a comma-separated string automatically!)_
<6> Besides transferring HTTP headers as a comma-separated string, the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] component also supports repeatable HTTP headers with different values.
<7> All specified value types for the HTTP header, which is a list of values, are transferred as the `java.lang.Object` type.
_(The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^]
component automatically converts them to a comma-separated string and transfers via the HTTP protocol.)_
<8> The RxMicro framework converts different types to a list of enumerations and displays it in the console.

[[rest-controller-headers-static]]
==== Static HTTP headers

For setting of the static headers, the RxMicro framework provides the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/AddHeader.java[`@AddHeader`^] and
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/SetHeader.java[`@SetHeader`^] annotations:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-headers/src/main/java/io/rxmicro/examples/rest/controller/headers/StaticHeadersMicroService.java[tag=content,indent=0]
----
<1> If the HTTP header is set for the REST controller, it is added to the HTTP responses for each handler.
<2> If the HTTP header is set for the handler, it is added to the HTTP responses only for that handler.

From the client's point of view, static headers do not differ from any others:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-headers/src/test/java/io/rxmicro/examples/rest/controller/headers/StaticHeadersMicroServiceTest.java[tag=content,indent=0]
----

[NOTE]
====
In order to understand the differences between the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/AddHeader.java[`@AddHeader`^] and
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/SetHeader.java[`@SetHeader`^] annotations, take a look to the following example:

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-controller-headers/src/main/java/io/rxmicro/examples/rest/controller/headers/ComplexStaticHeadersMicroService.java[`ComplexStaticHeadersMicroService.java`^]

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-controller-headers/src/test/java/io/rxmicro/examples/rest/controller/headers/ComplexStaticHeadersMicroServiceTest.java[`ComplexStaticHeadersMicroServiceTest.java`^]
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-headers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

[[rest-controller-headers-repeating]]
==== Repeating HTTP headers

If the HTTP header of an HTTP response is a list of values, the list elements are transferred by default via the HTTP protocol as a string separated by the `|` symbol.

If You want the HTTP header to be repeated for each value, You need to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RepeatHeader.java[`@RepeatHeader`^] annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-headers/src/main/java/io/rxmicro/examples/rest/controller/headers/model/RepeatingHeadersResponse.java[tag=content,indent=0]
----

[NOTE]
====
*The use of the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RepeatHeader.java[`@RepeatHeader`^] annotation is supported for response models only!*

For request models it makes no sense, because the RxMicro framework converts any of the supported formats into a list of values.
====

As a result of converting the Java model to HTTP response, the result will be as follows:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-headers/src/test/java/io/rxmicro/examples/rest/controller/headers/RepeatingHeadersMicroServiceTest.java[tag=content,indent=0]
----
<1> By default, HTTP header list elements are transferred via the HTTP protocol as a string separated by the `|` symbol.
<2> If the field is annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RepeatHeader.java[`@RepeatHeader`^] annotation, then the header is repeated for each element of the list.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-headers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
