:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-params-basic]]
=== HTTP Parameters Handling 

include::../_rest/___http-params-basic-rules.adoc[]

After creating model classes, it is necessary to create an HTTP request handler that uses the following models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/SimpleUsageMicroService.java[tag=content,indent=0]
----
<1> If a separate model class has been created for an HTTP request, then this class must be passed by the method parameter that handles the HTTP request.
<2> Besides supporting HTTP request model classes, the RxMicro framework supports request handlers that accept HTTP request parameters as method parameters.
<3> To define a common naming strategy for all HTTP parameters which are passed as method parameters, the request handler must be annotated by the `@ParameterMappingStrategy` annotation.
<4> To declare a method parameter as an HTTP parameter field, You do not need to use any additional annotations.
<5> Using the `@Parameter` annotation, it is possible to specify an HTTP parameter name that does not correspond to the strategy used, declared by the `@ParameterMappingStrategy` annotation.

[IMPORTANT]
====
*Note that the RxMicro framework does not distinguish whether HTTP request parameters will be transferred to the handler using the start line or HTTP body!*

Therefore, if the parameters are the same, it is possible to use the same handler with the specified request model to handle both `GET` (parameters are transferred in the start line) and `POST` (parameters are transferred in the HTTP body) request.
====

include::../___notes/model-class-intead-of-method-parameters-note.adoc[tags=**;!path-variables;!headers;!all]

Despite the different approaches to HTTP parameter handling support, from the client's point of view the two above-mentioned handlers are absolutely equal to `GET` and `POST` requests respectively:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-params/src/test/java/io/rxmicro/examples/rest/controller/params/SimpleUsageMicroServiceTest.java[tag=content,indent=0]
----
<1> When performing a request to different URL Paths, the result is the same.
_(Despite the differences in parameter transfer for `GET` and `POST`requests.)_
<2> The `endpoint_version` name corresponds to the `endpointVersion` field of the request model.
_(This correspondence is formed basing on the default strategy use, which is defined by the `@ParameterMappingStrategy` annotation.)_
<3> The `use-Proxy` name corresponds to the `useProxy` field of the request model, since this name is specified in the `@Parameter` annotation.
<4> After executing the request in the resulting HTTP response, the `endpoint_version` and `use-Proxy` HTTP parameters are equal to `v1` and `true` respectively.
_(The handler returns the same header values it received from an HTTP request.)_

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-controller/rest-controller-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Supported Data Types

include::../_rest/___param-types.adoc[]

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/ListQueryParamMicroService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-params/src/test/java/io/rxmicro/examples/rest/controller/params/ListQueryParamMicroServiceTest.java[tag=content,indent=0]
----

<1> If the HTTP parameter is a list of values, the list elements are transferred via the HTTP protocol as a string separated by the `|` symbol.
<2> Besides transferring the list using a comma-separated string, the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] component also supports: +
an array of enumerations,
<3> an array of string values,
<4> a list of enumerations,
<5> a list of string values. +
_(The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^]
component converts these types to a comma-separated string automatically!)_
<6> Besides transferring HTTP parameters as a comma-separated string, the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] component also supports repeatable query params with different values.
<7> All specified value types for the HTTP parameter, which is a list of values, are transferred as the `java.lang.Object` type.
_(The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^]
component automatically converts them to a comma-separated string and transfers via the HTTP protocol.)_
<8> The RxMicro framework converts different types to a list of enumerations and displays it in the console.

<<<

==== Complex Model Support

Unlike HTTP headers, HTTP parameters can be transferred in the request body.

Therefore, besides primitives the RxMicro framework also supports nested JSON objects and arrays.

[TIP]
====
Therefore, the list of supported types includes the following types:

* `? extends Object` - custom class of the nested Java model;
* `java.util.List<? extends Object>` - list of the nested Java model custom classes;
* `java.util.Set<? extends Object>` - set of the nested Java model custom classes;
* `java.util.Map<String, ? extends Object>` - map of the nested Java model custom classes;
====

Nested Model Example:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/model/nested/NestedModel.java[tag=content,indent=0]
----

As well as examples of more complex Java models that use a nested model:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/model/ComplexRequest.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/model/ComplexResponse.java[tag=content,indent=0]
----

<1> Primitive JSON type field.
<2> Primitive JSON array type.
<3> Nested JSON object.
<4> JSON array of JSON nested objects.

After creating model classes, it is necessary to create a request handler that uses the following models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/ComplexModelMicroService.java[tag=content,indent=0]
----

Since the request is transferred in an HTTP body, the sent and received JSON objects must be the same:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-params/src/test/java/io/rxmicro/examples/rest/controller/params/ComplexModelMicroServiceTest.java[tag=content,indent=0]
----

[TIP]
====
For automatic conversion of Java types to JSON types, it is recommended to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/json/JsonFactory.java[`JsonFactory`^] test class from the `rxmicro-test-json` module.
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-controller/rest-controller-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
