:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-params-basic]]
=== Обработка HTTP параметров

include::../_rest/___http-params-basic-rules.adoc[]

После создания классов моделей, необходимо создать обработчик HTTP запросов, использующий данные модели:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/SimpleUsageMicroService.java[tag=content,indent=0]
----
<1> Если для HTTP запроса был создан отдельный класс модели, то этот класс необходимо передавать параметром метода, обрабатывающего HTTP запрос.
<2> Кроме поддержки классов модели HTTP запроса, RxMicro поддерживает обработчики запросов, принимающие HTTP параметры запросов в качестве параметров метода.
<3> Для определения общей стратегии именования всех HTTP параметров, которые передаются в качестве параметров метода обработчик запросов должен быть аннотирован аннотацией `@ParameterMappingStrategy`.
<4> Для того чтобы параметр метода объявить как поле HTTP параметра, не нужно использовать каких-либо дополнительных аннотаций.
<5> С помощью аннотации `@Parameter` возможно задать имя HTTP параметра, которое не соответствует используемой стратегии, объявленной с помощью аннотации `@ParameterMappingStrategy`.

[IMPORTANT]
====
*Обратите внимание, что RxMicro не различает каким способом будут переданы параметры HTTP запроса на обработчик: с помощью стартовой строки или HTTP тела!*

Поэтому если параметры одинаковые, то можно использовать один обработчик с заданной моделью запроса для обработки как `GET` (параметры передаются в стартовой строке) так и `POST` (параметры передаются в HTTP теле) запросов.
====

include::../___notes/model-class-intead-of-method-parameters-note.adoc[tags=**;!path-variables;!headers;!all]

Несмотря на различные подходы к поддержке обработки HTTP параметров, с клиентской точки зрения два вышеуказанных обработчика абсолютно равнозначны для `GET` и `POST` запросов соответственно:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/test/java/io/rxmicro/examples/rest/controller/params/SimpleUsageMicroServiceTest.java[tag=content,indent=0]
----
<1> При выполнении запроса к разным URL Paths результат одинаковый.
_(Несмотря на различия в передачи параметров для `GET` и `POST`запросов.)_
<2> Имя `endpoint_version` соответствует полю `endpointVersion` модели запроса.
_(Данное соответствие формируется на основании использования стратегии по умолчанию, задаваемой с помощью аннотации `@ParameterMappingStrategy`.)_
<3> Имя `use-Proxy` соответствует полю `useProxy` модели запроса, так как в аннотации `@Parameter` задано именно это имя.
<4> После выполнения запроса в результирующем HTTP ответе HTTP параметры `endpoint_version` и `use-Proxy` равны соответственно `v1` и `true`.
_(Обработчик возвращает теже самые значения заголовков, что были им получены из HTTP запроса.)_

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Поддерживаемые типы данных

include::../_rest/___param-types.adoc[]

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/ListQueryParamMicroService.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/test/java/io/rxmicro/examples/rest/controller/params/ListQueryParamMicroServiceTest.java[tag=content,indent=0]
----

<1> Если HTTP параметр является списком значений, то элементы списка передаются по протоколу HTTP в виде строки, разделенной символом `|`.
<2> Кроме передачи списка с помощью строки разделенной запятыми, компонент
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] поддерживает также массив перечислений,
<3> массив строковых значений,
<4> список перечислений,
<5> список строковых значений.
<6> Кроме передачи HTTP параметров в виде строки, разделенной запятыми, компонент
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] также поддерживает повторяемые query params с разными значениями.
<7> Все указанные типы значений для HTTP параметра, который является списком значений, передаются в виде типа `java.lang.Object`.
_(Компонент {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^]
автоматически их преобразует в строку, разделенной запятыми и отправляет по протоколу HTTP.)_
<8> The RxMicro framework преобразует разные типы в список перечислений и отображает его в консоль.

<<<

==== Поддержка сложных моделей

В отличие от HTTP заголовков HTTP параметры могут передаваться в теле запроса.

Поэтому кроме примитивов RxMicro поддерживает также и вложенные JSON объекты и массивы.

[TIP]
====
Именно поэтому в списке поддерживаемых типов указаны следующие типы:

* `? extends Object` - пользовательский класс вложенной Java модели;
* `java.util.List<? extends Object>` - список пользовательских классов вложенной Java модели;
====

Пример вложенной модели:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/model/nested/NestedModel.java[tag=content,indent=0]
----

А также примеры более сложных Java моделей, использующих вложенную модель:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/model/ComplexRequest.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/model/ComplexResponse.java[tag=content,indent=0]
----

<1> Поле примитивного JSON типа.
<2> JSON массив примитивного типа.
<3> Вложенный JSON объект.
<4> JSON массив вложенных JSON объектов.

После создания классов моделей, необходимо создать обработчик запросов, использующий данные модели:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/main/java/io/rxmicro/examples/rest/controller/params/ComplexModelMicroService.java[tag=content,indent=0]
----

Так как запрос теперь передается в HTTP теле, то отправляемый и получаемый JSON объекты должны быть равны:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-params/src/test/java/io/rxmicro/examples/rest/controller/params/ComplexModelMicroServiceTest.java[tag=content,indent=0]
----

[TIP]
====
Чтобы автоматически конвертировать Java типы в JSON типы, рекомендуется использовать тестовый класс
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/json/JsonFactory.java[`JsonFactory`^] из модуля `rxmicro-test-json`.
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
