:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-internals-basic-section]]
=== Support of Internal Data Types

==== Basic Rules

The RxMicro framework works with internal data.
Due to this, the developer can extract additional information about the HTTP request and gain more control over the generated HTTP response.

To work with internal data, it is necessary to create request and response models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-internals/src/main/java/io/rxmicro/examples/rest/controller/internals/model/Request.java[tag=content,indent=0]
----
<1> To extract the remote address of the client connection, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RemoteAddress.java[`@RemoteAddress`^] annotation.
<2> To extract the current `URL path`, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestUrlPath.java[`@RequestUrlPath`^] annotation. +
_(This feature is useful for request logging using `path-variables`.)_
<3> To extract the current HTTP method, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestMethod.java[`@RequestMethod`^] annotation. +
_(This feature is useful for request logging when one handler supports different HTTP methods.)_
<4> To extract the HTTP protocol version, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpVersion.java[`HttpVersion`^] type.
<5> To extract all HTTP headers, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java[`HttpHeaders`^] type.
<6> To extract the request body content as a byte array, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestBody.java[`@RequestBody`^] annotation.

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-internals/src/main/java/io/rxmicro/examples/rest/controller/internals/model/Response.java[tag=content,indent=0]
----
<1> To override the HTTP status code, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ResponseStatusCode.java[`@ResponseStatusCode`^] annotation.
<2> To set the HTTP protocol version, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpVersion.java[`HttpVersion`^] type. +
_(Currently only `1.0` and `1.1` HTTP versions are supported.)_
<3> To set all HTTP headers, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java[`HttpHeaders`^] type.
<4> To set the response body content as a byte array, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ResponseBody.java[`@ResponseBody`^] annotation.

After creating model classes, it is necessary to create an HTTP request handler that uses the following models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-internals/src/main/java/io/rxmicro/examples/rest/controller/internals/MicroService.java[tag=content,indent=0]
----

After creating the REST controller, let's check that everything works:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-internals/src/test/java/io/rxmicro/examples/rest/controller/internals/MicroServiceTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-internals
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Supported Internal Data Types

.Supported internal data types for a request model.
|===
|*Java type*|*RxMicro Annotation*|*Is the annotation required?*|*Description*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/detail/model/HttpRequest.java[`HttpRequest`^]
|None
|-
|HTTP request model

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpVersion.java[`HttpVersion`^]
|None
|-
|HTTP protocol version

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java[`HttpHeaders`^]
|None
|-
|HTTP header model

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/net/SocketAddress.html[`SocketAddress`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RemoteAddress.java[`@RemoteAddress`^]
|*No*
|Remote client address

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/String.html[`String`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RemoteAddress.java[`@RemoteAddress`^]
|*Yes*
|Remote client address

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/String.html[`String`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestUrlPath.java[`@RequestUrlPath`^]
|*Yes*
|URL Path of the current request

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/String.html[`String`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestMethod.java[`@RequestMethod`^]
|*Yes*
|HTTP request method

|`byte[]`
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestBody.java[`@RequestBody`^]
|*Yes*
|HTTP request body content
|===

[TIP]
====
Currently only `1.0` and `1.1` HTTP versions are supported.
====

.Supported internal data types for a response model.
|===
|*Java type*|*RxMicro Annotation*|*Is the annotation required?*|*Description*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpVersion.java[`HttpVersion`^]
|None
|-
|HTTP protocol version

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java[`HttpHeaders`^]
|None
|-
|HTTP header model

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Integer.html[`Integer`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ResponseStatusCode.java[`@ResponseStatusCode`^]
|*Yes*
|HTTP response status code

|`byte[]`
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ResponseBody.java[`@ResponseBody`^]
|*Yes*
|HTTP response body content
|===
