:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-internals-basic-section]]
=== Поддержка служебных типов данных

==== Базовые правила

RxMicro поддерживает работу со служебными данными.
Благодаря такой поддержки разработчик имеет возможность извлечь дополнительные сведения об HTTP запросе и получает больший контроль над генерируемым HTTP ответом.

Для работы со служебными данными в запросе необходимо создать модели запроса и ответа:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-internals/src/main/java/io/rxmicro/examples/rest/controller/internals/model/Request.java[tag=content,indent=0]
----
<1> Для извлечения удаленного адреса клиентского подключения необходимо использовать аннотацию
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RemoteAddress.java[`@RemoteAddress`^].
<2> Для извлечения текущего `URL path` необходимо использовать аннотацию
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestUrlPath.java[`@RequestUrlPath`^]. +
_(Данная возможность полезна при логировании запросов с использованием `path-variables`.)_
<3> Для извлечения текущего HTTP метода необходимо использовать аннотацию
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestMethod.java[`@RequestMethod`^]. +
_(Данная возможность полезна при логировании запросов в случае когда один обработчик поддерживает разные HTTP методы.)_
<4> Для извлечения версии протокола HTTP, необходимо использовать тип
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpVersion.java[`HttpVersion`^].
<5> Для извлечения всех HTTP заголовков, необходимо использовать тип
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java[`HttpHeaders`^].
<6> Для извлечения содержимого тела запроса в виде массива байт, необходимо использовать аннотацию
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestBody.java[`@RequestBody`^].

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-internals/src/main/java/io/rxmicro/examples/rest/controller/internals/model/Response.java[tag=content,indent=0]
----
<1> Для переопределения HTTP статус кода необходимо использовать аннотацию
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ResponseStatusCode.java[`@ResponseStatusCode`^].
<2> Для установки версии протокола HTTP, необходимо использовать тип
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpVersion.java[`HttpVersion`^]. +
_(На данный момент поддерживаются только HTTP версии: `1.0` и `1.1`.)_
<3> Для установки всех HTTP заголовков, необходимо использовать тип
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java[`HttpHeaders`^].
<4> Для установки содержимого тела ответа в виде массива байт, необходимо использовать аннотацию
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ResponseBody.java[`@ResponseBody`^].

После создания классов моделей, необходимо создать обработчик HTTP запросов, использующий данные модели:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-internals/src/main/java/io/rxmicro/examples/rest/controller/internals/MicroService.java[tag=content,indent=0]
----

После создания REST контроллера, проверяем что все работает:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-internals/src/test/java/io/rxmicro/examples/rest/controller/internals/MicroServiceTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-internals
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Поддерживаемые служебные типы данных

.Поддерживаемые служебные типы данных для модели запроса.
|===
|*Java тип*|*RxMicro аннотация*|*Аннотация обязательна?*|*Описание*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/detail/model/HttpRequest.java[`HttpRequest`^]
|Отсутствует
|-
|Модель HTTP запроса

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpVersion.java[`HttpVersion`^]
|Отсутствует
|-
|Версия HTTP протокола

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java[`HttpHeaders`^]
|Отсутствует
|-
|Модель HTTP заголовков

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/net/SocketAddress.html[`SocketAddress`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RemoteAddress.java[`@RemoteAddress`^]
|*Нет*
|Адрес удаленного клиента

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/String.html[`String`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RemoteAddress.java[`@RemoteAddress`^]
|*Да*
|Адрес удаленного клиента

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/String.html[`String`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestUrlPath.java[`@RequestUrlPath`^]
|*Да*
|URL Path текущего запроса

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/String.html[`String`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestMethod.java[`@RequestMethod`^]
|*Да*
|Метод HTTP запроса

|`byte[]`
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestBody.java[`@RequestBody`^]
|*Да*
|Содержимое HTTP тела запроса
|===

[TIP]
====
На данный момент поддерживаются только HTTP версии: `1.0` и `1.1`.
====

.Поддерживаемые служебные типы данных для модели ответа.
|===
|*Java тип*|*RxMicro аннотация*|*Аннотация обязательна?*|*Описание*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpVersion.java[`HttpVersion`^]
|Отсутствует
|-
|Версия HTTP протокола

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpHeaders.java[`HttpHeaders`^]
|Отсутствует
|-
|Модель HTTP заголовков

|{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Integer.html[`Integer`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ResponseStatusCode.java[`@ResponseStatusCode`^]
|*Да*
|HTTP статус код ответа

|`byte[]`
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/ResponseBody.java[`@ResponseBody`^]
|*Да*
|Содержимое HTTP тела ответа
|===
