:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-not-found-section]]
=== `Not Found` Logic

The RxMicro framework supports `Not Found` Logic for HTTP request handlers.

To activate this feature it's necessary to return a reactive type that supports <<{core}#core-reactive-bussiness-process-result-types-section,optional result>>:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-notfound/src/main/java/io/rxmicro/examples/rest/controller/notfound/NotFoundMicroService.java[tag=content,indent=0]
----
<1> When using `CompletableFuture`/`CompletionStage` it is necessary to use the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/Optional.html[`java.util.Optional`^] contract, since the `CompletableFuture`/`CompletionStage` reactive types do not support optional result by default.
<2> Unlike `CompletableFuture`/`CompletionStage`, the `Mono` reactive type supports optional result.
<3> Unlike `CompletableFuture`/`CompletionStage`, the `Maybe` reactive type also supports optional result.

When handling requests, the RxMicro framework checks the handler result:

* If the handler returns a response model, RxMicro will convert it to an HTTP response with the `200` status and JSON representation of this model.
* If the handler returns an empty result, RxMicro generates an HTTP response with the `404` and the standard `"Not Found"` error message.

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-notfound/src/test/java/io/rxmicro/examples/rest/controller/notfound/NotFoundMicroServiceTest.java[tag=content,indent=0]
----
<1> In case there is a result, the result is returned in JSON format, and the HTTP response status is `200`.
<2> If there is no result, a standard error message is returned, and the HTTP response status is `404`.

The RxMicro framework provides an option to customize the `Not Found` message:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-notfound/src/main/java/io/rxmicro/examples/rest/controller/notfound/CustomizeNotFoundMicroService.java[tag=content,indent=0]
----
<1> The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/NotFoundMessage.java[`@NotFoundMessage`^]
annotation allows You to specify a message that will be displayed to the client in case of missing result instead of the standard `"Not Found"` message.

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-notfound/src/test/java/io/rxmicro/examples/rest/controller/notfound/CustomizeNotFoundMicroServiceTest.java[tag=content,indent=0]
----
<1> If there is no result, the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/NotFoundMessage.java[`@NotFoundMessage`^] message, which is set by the annotation, is returned.
<2> The HTTP status is `404`. +
(_The RxMicro framework does not allow overriding the HTTP status for `Not Found` logic!_)

[NOTE]
====
For more control over the HTTP response generated in case of an error, use <<rest-controller-errors-section,exception>> instead of `Not Found` Logic feature!
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-notfound
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
