:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-redirect-section]]
=== Redirecting of Requests

The RxMicro framework supports request redirection:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-redirect/src/main/java/io/rxmicro/examples/rest/controller/redirect/MicroService.java[tag=content,indent=0]
----
<1> To redirect a request, You need to return the `PermanentRedirectException` instance, indicating a new URL Path.
<2> Once the HTTP response with request redirection is returned, the HTTP client will automatically repeat the request to a new URL Path.

[NOTE]
====
*If temporary redirection is required, the `TemporaryRedirectException` class must be used instead of the `PermanentRedirectException` class!*
====

[IMPORTANT]
====
The predefined redirection classes (`TemporaryRedirectException` and `PermanentRedirectException`) return the
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307[`307`^] and
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308[`308`^] HTTP statuses.

*According to the HTTP protocol rules, the HTTP method is preserved at such redirection!*
====

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-redirect/src/test/java/io/rxmicro/examples/rest/controller/redirect/MicroServiceTest.java[tag=content,indent=0]
----
<1> By default, the predefined HTTP client, that is used to perform test requests to the microservice, does not support redirection.
Therefore, automatic redirection must be activated using the <<testing.adoc#testing-BlockingHttpClient-settings-section,`@BlockingHttpClientSettings(followRedirects = ENABLED)` setting>>.
<2> The `PUT` request to the `/put1` URL Path is performed.
<3> Consequently, the `MicroService.put` handler is automatically performed after the `MicroService.redirect` handler.

[NOTE]
====
Besides using the `PermanentRedirectException`/`TemporaryRedirectException` exceptions, a custom model class or the
<<rest-controller-set-status-code-section,`@SetStatusCode`>> and <<rest-controller-headers-static,`@SetHeader`>> annotation composition can be used for redirection:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-redirect/src/main/java/io/rxmicro/examples/rest/controller/redirect/MicroService2.java[tag=content,indent=0]
----
<1> Using a custom model class with the `Location` header.
<2> Using the <<rest-controller-set-status-code-section,`@SetStatusCode`>> and <<rest-controller-headers-static,`@SetHeader`>> annotation composition.

*FYI:* The `RedirectResponse` model class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-redirect/src/main/java/io/rxmicro/examples/rest/controller/redirect/model/RedirectResponse.java[tag=content,indent=0]
----
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-redirect
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
