:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-rqeuest-id-section]]
=== Request ID

==== Basic Rules

To track an HTTP request when using a microservice architecture, the RxMicro framework provides an HTTP request identification feature.

If the current request is identified, the provided unique id is used during the life-cycle of the current request.
If the request is not identified, the RxMicro framework generates a unique id, which is further used in the life-cycle of the current request.

To store the request id, the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpStandardHeaderNames.java#L400[`Request-Id`^] HTTP additional header is used.

If the HTTP request id is necessary for business logic, a separate field in the HTTP request Java model must be created:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-request-id/src/main/java/io/rxmicro/examples/rest/controller/request/id/model/Request.java[tag=content,indent=0]
----
<1> For convenience, instead of specifying an HTTP header using the `@Header` annotation and the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpStandardHeaderNames.java#L400[`Request-Id`^] name,
<2> the special {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RequestId.java[`@RequestId`^] annotation can be used, which is an alternative to the `@Header(HttpHeaders.REQUEST_ID)` configuration.

Having declared a field in the HTTP request Java model, You can use its value in the handler:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-request-id/src/main/java/io/rxmicro/examples/rest/controller/request/id/MicroService.java[tag=content,indent=0]
----
<1> Displaying the value of the current request id in the console.

The following test describes the basic requirements for the behavior of the request id function:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-request-id/src/test/java/io/rxmicro/examples/rest/controller/request/id/MicroServiceTest.java[tag=content,indent=0]
----
<1> For HTTP requests without id, the RxMicro framework must generate a unique id automatically.
_(This id can be used in the HTTP request handler body.)_
<2> Each HTTP response must contain the required
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpStandardHeaderNames.java#L400[`Request-Id`^]
HTTP header with the value of the generated request id. +
_(If the configuration parameter `RestServerConfig.returnGeneratedRequestId = false`, the HTTP response will not contain the `Request-Id` header.)_
<3> If the current HTTP request already contains an id, the RxMicro framework must use it instead of generating a new value.
<4> The id set by the client can be used in the HTTP request handler body.
<5> Each HTTP response must contain the required
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpStandardHeaderNames.java#L400[`Request-Id`^]
HTTP header with a client specified request id value. +
_(If the configuration parameter `RestServerConfig.returnGeneratedRequestId = false`, the HTTP response will not contain the `Request-Id` header.)_

[IMPORTANT]
====
For ease of testing, if the microservice is launched automatically by a test, then a test id is assigned to each HTTP request.
By default, the value of the HTTP request test id is equal to
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/local/component/impl/TestRequestIdGenerator.java#L32[`TestRequestId`^].
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-controller/rest-controller-request-id
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Supported Generator Types

The RxMicro framework supports the following types of HTTP request id generators.

.Generator name and its implementation class.
|===
|*Type*|*Implementation class*|*Description*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RequestIdGeneratorType.java#L36[`FASTER_BUT_UNSAFE`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/local/component/impl/FasterButUnSafeRequestIdGenerator.java[`FasterButUnSafeRequestIdGenerator`^]
|*Generates unique IDs only within the framework of starting one `JVM`.*

Uses a random increment counter.

(_Used by default_).

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RequestIdGeneratorType.java#L43[`SAFE_BUT_SLOWER`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/local/component/impl/SafeButSlowerRequestIdGenerator.java[`SafeButSlowerRequestIdGenerator`^]
|*Generates unique IDs independently of starting the `JVM`.*

As a unique value uses the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/UUID.html#randomUUID()[`UUID.randomUUID()`^].

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RequestIdGeneratorType.java#L50[`FOR_TESTS_ONLY`^]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/local/component/impl/TestRequestIdGenerator.java[`TestRequestIdGenerator`^]
|Recommended *for test environment only*.

By default, it is automatically activated for test environment.
|===

To change the request id generator type, You must use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RestServerConfig.java[`RestServerConfig`^] configuration class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-request-id/src/main/java/io/rxmicro/examples/rest/controller/request/id/Launcher.java[tag=content,indent=0]
----

<1> Setting the `SAFE_BUT_SLOWER` value as a generator type of HTTP request ids.

<<<

==== Comparing the Performance of Generator Types

Performance test source code:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}benchmarks/benchmark-rxmicro-core/src/main/java/io/rxmicro/benchmark/rxmicro/core/server/RequestIdGeneratorBenchmark.java[tag=content,indent=0]
----

Performance test results:

[source,txt]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}benchmarks/_results/rxmicro-core-RequestIdGeneratorBenchmark.txt[]
----

[IMPORTANT]
====
Test results show that the performance of the `FasterButUnSafeRequestIdGenerator` component *is 6 times better*, than that of the `SafeButSlowerRequestIdGenerator` component!
====
