:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

=== Требования к реализации REST Controller

==== Требования к классу REST Controller

REST Controller - это Java класс:

[source,java]
----
import io.rxmicro.rest.method.GET;

final class MicroService {

    @GET("/")
    void requestHandler() {

    }
}
----

который должен удовлетворять следующим требованиям:

. Класс должен наследоваться от `java.lang.Object`.
. Класс не должен быть абстрактным.
. Класс не должен быть вложенным.
. Класс должен содержать публичный конструктор без параметров. +
_(Если в проекте используется модуль <<{cdi}#{cdi-section},`rxmicro.cdi`>> данное требование неактуально!)_

[TIP]
====
Класс REST Controller должен быть `public` только если содержит метод: `public static void main(final String[] args)`.

В противном случае класс может быть непубличным.
====

<<<

==== Требования к обработчикам HTTP запроса

Обработчик HTTP запроса - метод, который должен удовлетворять следующим требованиям:

. Метод должен быть неприватным.
. Метод должен быть неабстрактным.
. Метод должен быть нестатическим.
. Метод должен быть несинхронизированным.
. Метод должен быть ненативным.
. Метод должен быть аннотирован хотя бы одной из следующих аннотаций:
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/GET.java[`GET`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/POST.java[`POST`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/PUT.java[`PUT`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/DELETE.java[`DELETE`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/PATCH.java[`PATCH`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/HEAD.java[`HEAD`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/OPTIONS.java[`OPTIONS`^].
. Метод должен возвращать тип `void` или один из реактивных типов:
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture`^];
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage`^];
.. {REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Completable.html[`Completable`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Single.html[`Single`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Maybe.html[`Maybe`^].
. Если метод возвращает реактивный тип, то данный тип должен быть параметризован классом модели ответа.
(Вспомогательные типы `java.lang.Void` и `java.util.Optional` также поддерживаются.
_(см. <<{core}#core-reactive-bussiness-process-reactive-class-mapping-table>>)_).

include::../_rest/___note-Flux-Flowable.adoc[]

:target: микросервисов
include::../_rest/___requirements-param-types.adoc[]

include::../_rest/___note-reactive-libs.adoc[]
