:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

=== REST Controller Implementation Requirements.

==== REST Controller Class Requirements.

REST Controller is a Java class:

[source,java]
----
import io.rxmicro.rest.method.GET;

final class MicroService {

    @GET("/")
    void requestHandler() {

    }
}
----

that must meet the following requirements:

. The class must extend the `java.lang.Object` one.
. The class couldn't be an `abstract` one.
. The class couldn't be a nested one.
. The class must contain an accessible (not private) constructor without parameters. +
_(The last requirement can be ignored if Your project depends on <<{cdi}#{cdi-section},`rxmicro.cdi`>> module.)_

[TIP]
====
A REST Controller class must be a public one, only if it contains the method: `public static void main(final String[] args)`.
Otherwise, a REST Controller class can be nonpublic.
====

<<<

==== HTTP Request Handler Requirements.

HTTP request handler is a method, that must meet the following requirements:

. The method couldn't be a `private` one.
. The method couldn't be an `abstract` one.
. The method couldn't be a `synchronized` one.
. The method couldn't be a `static` one.
. The method couldn't be a `native` one.
. The method must be annotated by at least one of the following annotations:
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/GET.java[`GET`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/POST.java[`POST`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/PUT.java[`PUT`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/DELETE.java[`DELETE`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/PATCH.java[`PATCH`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/HEAD.java[`HEAD`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/OPTIONS.java[`OPTIONS`^].
. The method must return a `void` type or one of the following reactive types:
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture`^];
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage`^];
.. {REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Completable.html[`Completable`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Single.html[`Single`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Maybe.html[`Maybe`^].
. If the method returns a reactive type, that this type must be parametrized by a HTTP response model type.
(The additional types such as `java.lang.Void` and `java.util.Optional` are supported also.
_(Read more: <<{core}#core-reactive-bussiness-process-reactive-class-mapping-table>>)_).

include::../_rest/___note-Flux-Flowable.adoc[]

:target: microservices
include::../_rest/___requirements-param-types.adoc[]

include::../_rest/___note-reactive-libs.adoc[]
