:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-rest-server-generator-config-section]]
=== Конфигурирование процесса генерации кода

RxMicro предоставляет возможность конфигурировать процесс генерации кода для REST контроллеров.
Для этих целей необходимо использовать аннотацию
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RestServerGeneratorConfig.java[`@RestServerGeneratorConfig`^]
, с помощью которой аннотируется дескриптор модуля `module-info.java`:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-generator/src/main/java/module-info.java[tags=content,indent=0]
----
<1> Параметр `exchangeFormat` позволяет задавать формат обмена сообщениями с клиентом. +
_(По умолчанию используется формат обмена сообщениями, который добавлен в дескриптор `module-info.java`.
Если в дескриптор `module-info.java` добавлены несколько модулей, поддерживающих формат обмена сообщениями, то с помощью параметра `exchangeFormat` необходимо указать, какой именно модуль нужно использовать для REST контроллеров.)_
<2> Параметр `generateRequestValidators` позволяет включать/отключать опцию генерации валидаторов HTTP запроса для всех обработчиков в проекте. +
_(Значение `AUTO_DETECT` означает, что валидаторы будут сгенерированы только в том случае, если разработчик добавит модуль <<{validation}#validation-section, `rxmicro.validation`>> в дескриптор `module-info.java`.)_
<3> Параметр `generateResponseValidators` позволяет включать/отключать опцию генерации валидаторов HTTP ответа для всех обработчиков в проекте. +
_(Значение `DISABLED` означает, что валидаторы не будут генерироваться процессором аннотаций.)_
