:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-rest-server-generator-config-section]]
=== Configuring the Code Generation Process

The RxMicro framework provides an ability to configure the code generation process for REST controllers.
For this purpose, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/server/RestServerGeneratorConfig.java[`@RestServerGeneratorConfig`^]
annotation, that annotates the `module-info.java` module descriptor:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-generator/src/main/java/module-info.java[tags=content,indent=0]
----
<1> The `exchangeFormat` parameter allows You to specify a format for message exchange with a client. +
_(By default, it is used the message exchange format added to the `module-info.java` descriptor.
If several modules supporting the message exchange format are added to the `module-info.java` descriptor, then using the `exchangeFormat` parameter, You need to specify which module should be used for REST controllers.)_
<2> The `generateRequestValidators` parameter allows enabling/disabling the option of generating HTTP request validators for all handlers in the project.
_(The `AUTO_DETECT` value means that validators will be generated only if the developer adds the <<{validation}#validation-section, `rxmicro.validation`>> module to the `module-info.java` descriptor.)_
<3> The `generateResponseValidators` parameter allows enabling/disabling the option of generating HTTP response validators for all handlers in the project.
_(The `DISABLED` value means that validators won't be generated by the `RxMicro Annotation Processor`.)_
