:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== Return Types

include::../_rest/___http-handler-return-types.adoc[]

<<<

==== Supported Return Types for HTTP Response without Body

The RxMicro framework supports the following return result types for an HTTP response without body:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-handlers/src/main/java/io/rxmicro/examples/rest/controller/handlers/RestControllerWithoutBody.java[tag=content,indent=0]
----
<1> The `void` type is supported mainly for test purposes. +
_(The `void` type can also be applied when the request handler does not use any <<core.adoc#core-dont-block-current-thread,blocking operations>>.
In cases where the request handler uses <<core.adoc#core-dont-block-current-thread,blocking operations>>, one of the reactive types must be used instead of the `void` type.)_
<2> The {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<Void>`^]
type is recommended when using the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^] library.
<3> Instead of the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<Void>`^] type, can also be used the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage<Void>`^] type.
<4> When using the {REACTOR-CORE-DOC-USER_GUIDE}[*Project Reactor*^] library, only the
{REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono<Void>`^] type can be used.
<5> When using the {RX-JAVA-USER-GUIDE}[*RxJava*^] library, only the
{RX-JAVA-DOC-ROOT-URL}io/reactivex/Completable.html[`Completable`^] type can be used.

All the above mentioned handlers return an HTTP response without body:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-handlers/src/test/java/io/rxmicro/examples/rest/controller/handlers/RestControllerWithoutBodyTest.java[tag=content,indent=0]
----
<1> When testing all `RestControllerWithoutBody` class handlers, each handler returns an HTTP response without body.

include::../___notes/model-class-intead-of-method-parameters-note.adoc[tags=**;!path-variables;!headers;!params]

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-handlers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Supported Return Types for HTTP Response with Body

The RxMicro framework supports the following return result types for an HTTP response with body:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-handlers/src/main/java/io/rxmicro/examples/rest/controller/handlers/RestControllerWithBody.java[tag=content,indent=0]
----
<1> The {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<MODEL>`^]
type is recommended when using the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^] library.
<2> Instead of the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<MODEL>`^] type, can also be used the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage<MODEL>`^] type.
<3> When using the {REACTOR-CORE-DOC-USER_GUIDE}[*Project Reactor*^] library, only the
{REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono<MODEL>`^] type can be used.
<4> When using the {RX-JAVA-USER-GUIDE}[*RxJava*^] library, the
{RX-JAVA-DOC-ROOT-URL}io/reactivex/Single.html[`Single<MODEL>`^] or
{RX-JAVA-DOC-ROOT-URL}io/reactivex/Maybe.html[`Maybe<MODEL>`^] can be used.

include::../_rest/___note-reactive-parametrized-types.adoc[]

All the above mentioned handlers return an HTTP response with body:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-handlers/src/test/java/io/rxmicro/examples/rest/controller/handlers/RestControllerWithBodyTest.java[tag=content,indent=0]
----
<1> When testing all `RestControllerWithBody` class handlers, each handler returns an HTTP response containing a JSON object, with the `Hello World!` message.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-handlers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
