:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== Routing of Requests

The RxMicro framework поддерживает маршрутизацию запросов на основании HTTP метода, URL Path и HTTP тела:

<<<

==== Routing of Requests Based on HTTP Method

The RxMicro framework позволяет обрабатывать одинаковые HTTP запросы, отличающиеся *только* HTTP методом разными обработчиками:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-routing/src/main/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingHTTPMethod.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-routing/src/test/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingHTTPMethodTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-routing
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Routing of Requests Based on URL Path

The RxMicro framework позволяет обрабатывать HTTP запросы на разные URL Paths разными обработчиками:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-routing/src/main/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingUrlPath.java[tag=content,indent=0]
----
<1> Кроме статических URL Paths, the RxMicro framework также поддерживает и <<rest-controller-path-variables-basic,`path variables`.>>

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-routing/src/test/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingUrlPathTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-routing
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Routing of Requests Based on HTTP Body

Некоторые HTTP методы позволяют передавать параметры запроса как в стартовой строке так и в теле запроса.

Поэтому the RxMicro framework кроме стандартных типов маршрутизации также поддерживает маршрутизацию на основании наличия HTTP тела:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-routing/src/main/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingHttpBody.java[tag=content,indent=0]
----
<1> Обработчик запроса, параметры которого передаются в стартовой строке
<2> Обработчик запроса, параметры которого передаются в теле запроса.

[NOTE]
====
Для HTTP методов `GET`, `HEAD`, `OPTIONS` и `DELETE` параметры запроса *всегда* передаются в стартовой строке.

Для HTTP методов `POST`, `PUT` и `PATCH` параметры запроса могут передаваться как в стартовой строке так и в теле запроса.
_(Для конфигурации типа передачи параметров используется опция `httpBody`.)_
====

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-routing/src/test/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingHttpBodyTest.java[tag=content,indent=0]
----
<1> Передача параметров в стартовой строке.
<2> Передача параметров в теле запроса в виде JSON объекта.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-routing
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
