:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== Routing of Requests

The RxMicro framework supports request routing based on HTTP method, URL Path and HTTP body:

<<<

==== Routing of Requests Based on HTTP Method

The RxMicro framework allows handling identical HTTP requests, differing *only* in HTTP method, by different handlers:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-routing/src/main/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingHTTPMethod.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-routing/src/test/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingHTTPMethodTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-routing
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Routing of Requests Based on URL Path

The RxMicro framework allows handling HTTP requests on different URL Paths by different handlers:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-routing/src/main/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingUrlPath.java[tag=content,indent=0]
----
<1> In addition to static URL Paths, the RxMicro framework also supports <<rest-controller-path-variables-basic,`path variables`.>>

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-routing/src/test/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingUrlPathTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-routing
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Routing of Requests Based on HTTP Body

Some HTTP methods allows transferring request parameters both in the start line and in the request body.

Therefore, in addition to standard routing types, the RxMicro framework also supports routing based on the HTTP body availability:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-routing/src/main/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingHttpBody.java[tag=content,indent=0]
----
<1> The request handler with parameters transferred in the start line.
<2> The request handler with parameters transferred in the request body.

[NOTE]
====
For the `GET`, `HEAD`, `OPTIONS` and `DELETE` HTTP methods, the request parameters are *always* transferred in the start line.

For the `POST`, `PUT` and `PATCH` HTTP methods, the request parameters can be transferred both in the start line and in the request body.
_(To configure the parameter transfer type, the `httpBody` option is used.)_
====

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-routing/src/test/java/io/rxmicro/examples/rest/controller/routing/RoutingUsingHttpBodyTest.java[tag=content,indent=0]
----
<1> Parameter transfer in the start line.
<2> Parameter transfer in the request body as JSON object.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-controller-routing
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
