:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-controller-versioning-section]]
=== Versioning of REST Controllers

The RxMicro framework supports versioning of REST Controllers using two strategies:

* Versioning based on HTTP header analysis with the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpStandardHeaderNames.java#L406[`Api-Version`^] name.
* Versioning based on URL Path fragment analysis.

<<<

==== Versioning Based on HTTP Header Analysis

The RxMicro framework allows creating identical REST controllers that differ only in version:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-versioning-header/src/main/java/io/rxmicro/examples/rest/controller/versioning/header/OldMicroService.java[tag=content,indent=0]
----
<1> REST controller of the old `v1` version, using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Version.java#L89[`Version.Strategy.HEADER`^] strategy;

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-versioning-header/src/main/java/io/rxmicro/examples/rest/controller/versioning/header/NewMicroService.java[tag=content,indent=0]
----
<1> REST controller of the new `v2` version, using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Version.java#L89[`Version.Strategy.HEADER`^] strategy;

include::../___notes/note-same-request-handlers-with-diff-versions.adoc[]

The correct selection of the appropriate REST controller handler can be checked with the following test:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-versioning-header/src/test/java/io/rxmicro/examples/rest/controller/versioning/header/MicroServiceTest.java[tag=content,indent=0]
----
<1> The <<{testing}#testing-rest-based-microservice-tests-section,`@RxMicroRestBasedMicroServiceTest`>> annotation allows You to run several REST controllers in test mode.
<2> The test runs the `PATCH` request to a URL Path: `/`.
<3> To specify the handler version, the standard
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http/src/main/java/io/rxmicro/http/HttpStandardHeaderNames.java#L406[`Api-Version`^] HTTP header is used.

include::../___notes/note-blocking-http-client-version.adoc[]

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-controller/rest-controller-versioning-header
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Versioning Based on URL Path Fragment Analysis

The RxMicro framework allows creating identical REST controllers that differ only in version:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-versioning-url-path/src/main/java/io/rxmicro/examples/rest/controller/versioning/url/path/OldMicroService.java[tag=content,indent=0]
----
<1> REST controller of the old `v1` version, using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Version.java#L70[`Version.Strategy.URL_PATH`^] strategy;

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-versioning-url-path/src/main/java/io/rxmicro/examples/rest/controller/versioning/url/path/NewMicroService.java[tag=content,indent=0]
----
<1> REST controller of the new `v2` version, using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Version.java#L70[`Version.Strategy.URL_PATH`^] strategy;

include::../___notes/note-same-request-handlers-with-diff-versions.adoc[]

The correct selection of the appropriate REST controller handler can be checked with the following test:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-controller/rest-controller-versioning-url-path/src/test/java/io/rxmicro/examples/rest/controller/versioning/url/path/MicroServiceTest.java[tag=content,indent=0]
----
<1> The <<{testing}#testing-rest-based-microservice-tests-section,`@RxMicroRestBasedMicroServiceTest`>> annotation allows You to run several REST controllers in test mode.
<2> The test runs the `PATCH` request to different URL Paths;

include::../___notes/note-blocking-http-client-version.adoc[]

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-controller/rest-controller-versioning-url-path
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
