// suppress inspection "AsciiDocLinkResolve" for whole file
:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[core-json-rxmicro-json-module-usage]]
==== `rxmicro.json` Module Usage

To write <<{testing}#testing-section,tests>> correctly, it is necessary to have a common idea about the `rxmicro.json` module.

Let's look at a microservice that returns the result in JSON object format:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/json/src/main/java/io/rxmicro/examples/json/MicroService.java[tag=content,indent=0]
----

The `Response` class - Java model of HTTP response in JSON format:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/json/src/main/java/io/rxmicro/examples/json/Response.java[tag=content,indent=0]
----
<1> Nested JSON object.
<2> JSON numeric array.
<3> String data type.
<4> Integer numeric data type.
<5> Floating-point numeric data type.
<6> Logical data type.

The `Child` class - Java model of the nested JSON object:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/json/src/main/java/io/rxmicro/examples/json/Child.java[tag=content,indent=0]
----

[TIP]
====
For simplicity, each response model field is immediately initialized with test data.
====

As a result, the microservice returns the following JSON object:

[source,json]
----
{
  "child": {
    "integer": 20
  },
  "values": [
    25,
    50,
    75,
    100
  ],
  "string": "text",
  "integer": 10,
  "decimal": 0.1234,
  "logical": true
}
----

While writing <<{testing}#testing-rest-based-microservice-tests-section,REST-based microservice test>> or <<{testing}#testing-integration-tests-basic-section,integration test>>, it is necessary to compare the expected JSON response with the one returned by REST-based microservice.
_(The response returned by the microservice is available through the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http-client/src/main/java/io/rxmicro/http/client/ClientHttpResponse.java#L75[`ClientHttpResponse.getBody()`^]method)_:

[source,java]
----
@RxMicroRestBasedMicroServiceTest(MicroService.class)
final class MicroServiceTest {
    //..
    @Test
    void Should_return_Response() {
        final ClientHttpResponse response = httpClient.get("/").join();
        final Object actualBody = response.getBody(); // <1>
        // ...
    }
}
----
<1>  The `ClientHttpResponse.getBody()` method returns the HTTP response body.
Since the REST-based microservice returns a JSON object, this method returns the result as the <<core-json-type-mapping,`java.util.Map<String, Object>`>> object.

Therefore, to compare JSON objects, You need to create the `java.util.Map<String, Object>` object containing the expected properties of the JSON object:

[source,java]
----
@RxMicroRestBasedMicroServiceTest(MicroService.class)
final class MicroServiceTest {
    //..
    @Test
    void Should_return_Response() {
        final ClientHttpResponse response = httpClient.get("/").join();
        final Object actualBody = response.getBody(); // <1>
        final Object expectedBody = Stream.of(
                Map.entry("child", Map.of(
                        "integer", new io.rxmicro.json.JsonNumber("20")
                )),
                Map.entry("values", List.of(
                        new io.rxmicro.json.JsonNumber("25"),
                        new io.rxmicro.json.JsonNumber("50"),
                        new io.rxmicro.json.JsonNumber("75"),
                        new io.rxmicro.json.JsonNumber("100")
                )),
                Map.entry("string", "text"),
                Map.entry("integer", new io.rxmicro.json.JsonNumber("10")),
                Map.entry("decimal", new io.rxmicro.json.JsonNumber("0.1234")),
                Map.entry("logical", true)
        ).collect(Collectors.toMap(
                Map.Entry::getKey,
                Map.Entry::getValue,
                (u, v) -> u, LinkedHashMap::new
        )); // <2>
        assertEquals(expectedBody, actualBody); // <3>
    }
}
----
<1> A JSON object returned by microservice.
<2> Expected JSON object.
<3> Comparison of JSON objects using the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Object.html#equals(java.lang.Object)[`java.lang.Object.equals()`^] method.

[IMPORTANT]
====
According to the https://tools.ietf.org/html/rfc7159#page-6[JSON specification^], the property order in JSON object is undefined.

Thus, the following JSON objects:

[source,json]
----
{
    "firstname" : "David",
    "lastname" : "Smith"
}
----

and

[source,json]
----
{
    "lastname" : "Smith",
    "firstname" : "David"
}
----

are considered to be the same.

*The RxMicro framework always arranges JSON object properties!*

*Thus, the order of JSON properties always corresponds to the order of fields in the Java model!*

This allows You to compare JSON objects in the form of  `java.util.Map<String, Object>` using the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Object.html#equals(java.lang.Object)[`java.lang.Object.equals()`^] method.
====

[NOTE]
====
If Your microservice returns the JSON object with unordered properties, use
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/json/JsonFactory.java[`JsonFactory.orderedJsonObject(Object jsonObject)`^]
method to sort properties before comparison!
====

For convenient creation of the expected JSON object, it is recommended to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/json/JsonFactory.java[`JsonFactory`^] utility class.
This class arranges JSON properties and automatically converts all
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Number.html[`java.lang.Number`^] types into the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-json/src/main/java/io/rxmicro/json/JsonNumber.java[`io.rxmicro.json.JsonNumber`^] type:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/json/src/test/java/io/rxmicro/examples/json/MicroServiceTest.java[tag=content,indent=0]
----
<1> A JSON object returned by microservice.
<2> Expected JSON object.
<3> Comparison of JSON objects using the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Object.html#equals(java.lang.Object)[`java.lang.Object.equals()`^] method.
<4> To create JSON object, it is recommended to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/json/JsonFactory.java[`JsonFactory.jsonObject`^] method.
<5> To create JSON array, it is recommended to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/json/JsonFactory.java[`JsonFactory.jsonArray`^] method.

[NOTE]
====
The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http-client/src/main/java/io/rxmicro/http/client/ClientHttpResponse.java[`ClientHttpResponse`^]
interface besides `body()` method also contains `bodyAsBytes()` and `bodyAsString()` ones.

Therefore in the test You can compare JSON objects by comparing their string representation or using a third-party Java library that supports the JSON format.
(For example, https://github.com/stleary/JSON-java[`JSON-java`^], https://javaee.github.io/jsonp/[`Java API for JSON Processing`^], etc.)

*Thus, the RxMicro framework recommends using the `rxmicro.json` module to compare JSON objects, but at the same time provides an opportunity to use any other JSON framework!*
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-common/json
include::../../___notes/full-source-code-of-example.adoc[]
