===== Конфигурирование с помощью classpath ресурсов

*RxMicro* поддерживает общий и отдельные classpath ресурсы для внешней по отношении к исходному коду микросервиса конфигурации.

Единственным поддерживаемым форматом classpath ресурса является формат `properties` файлов.

====== Конфигурирование с помощью отдельного classpath ресурса

Если в classpath текущего проекта находится ресурс `http-server.properties` с содержимым:

[source,properties]
----
port=9090 # <1>
----
<1> Пользовательский порт для HTTP сервера.

то RxMicro при считывании конфигурации класса `HttpServerConfig` считает данный ресурс:

[source,text]
----
2020-01-11 12:44:27.518 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at 0.0.0.0:9090 using NETTY transport in 500 millis. # <1>
----
<1> HTTP сервер запустился на порту `9090` вместо стандартного `8080`.

include::___tip_namespace.adoc[]

====== Конфигурирование с помощью общего classpath ресурса

Если в classpath текущего проекта находится ресурс `rxmicro.properties` с содержимым:

[source,properties]
----
http-server.port=9090 # <1>
----
<1> Пользовательский порт для HTTP сервера.

то RxMicro при считывании конфигурации класса `HttpServerConfig` считает данный ресурс:

[source,text]
----
2020-01-11 12:44:27.518 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at 0.0.0.0:9090 using NETTY transport in 500 millis. # <1>
----
<1> HTTP сервер запустился на порту `9090` вместо стандартного `8080`.

include::___tip_rxmicro_resource.adoc[]

Так как ресурс `rxmicro.properties` является общим ресурсом для *любой* конфигурации, необходимо при указании настроек, указывать пространство имен.

include::___note_common_and_special_resource_difference.adoc[]
