:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../../

==== Пользовательские конфигурации

Разработчик может использовать модуль конфигурации для пользовательских конфигураций.

Для этого необходимо создать отдельный класс:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/config-custom/src/main/java/io/rxmicro/examples/config/custom/BusinessServiceConfig.java[tag=content,indent=0]
----

[IMPORTANT]
====
Пользовательский класс конфигураций должен удовлетворять следующим требованиям:

. Класс должен быть публичным.
. Класс должен содержать публичный конструктор без параметров.
. Класс должен наследовать абстрактный класс
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Config.java[`Config`^].
. Для установки значений свойств класс должен содержать https://www.w3schools.com/java/java_encapsulation.asp[`setters`^]. +
_(Только те поля, которые будут содержать `setters` могут быть проинициализированы!)_
====

Так как данный класс будет создаваться и инициализироваться классами из модулей `rxmicro.runtime` и `rxmicro.config` автоматически, необходимо экспортировать пакет данным модулям в дескрипторе `module-info.java`. +
_(Это требования https://www.oracle.com/corporate/features/understanding-java-9-modules.html[модульной системы Java^].)_

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/config-custom/src/main/java/module-info.java[tag=content,indent=0]
----
<1> Разрешаем доступ к публичным классам из пакета `io.rxmicro.example.config.custom` модулю `rxmicro.runtime`.
<2> Разрешаем доступ к публичным классам из пакета `io.rxmicro.example.config.custom` модулю `rxmicro.config`.

После указанных изменений класс пользовательских конфигураций доступен для использования:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/config-custom/src/main/java/io/rxmicro/examples/config/custom/MicroService.java[tag=content,indent=0]
----

Флаг `production` теперь может быть установлен используя любой тип конфигурирования, например с помощью classpath ресурса `business-service.properties`:

[source,properties]
----
production=false
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}config-custom
include::../../___notes/full-source-code-of-example.adoc[]

include::../../___notes/recompile-after-change.adoc[]