[[testing-alternatives-section]]
=== Альтернативы

Для эффективного модульного тестирования RxMicro поддерживает механизм альтернатив.

*Альтернативы* - это тестовые компоненты, почти всегда являющиеся моками, с заранее определенным поведением, которые внедряются фреймворком RxMicro в тестируемые классы.
Альтернативы являются мощным механизмом для написания модульных тестов.

RxMicro поддерживает альтернативы только для <<{testing}#testing-rest-based-microservice-tests-section,тестов REST-based микросервиса>> и <<{testing}#testing-component-tests-section,модульных тестов компонента>>.

При разработке микросервисного проекта выделяют два типа компонентов:

* _RxMicro компонент_ - это класс, который является часть фреймворка RxMicro (например `HttpClientFactory`) или класс, генерируемый процессором аннотаций (Data Repository, Rest client, etc).
* _Пользовательский компонент_ - это класс написанный разработчиком и который является частью микросервисного проекта.

У этих двух типов компонентов разные жизненные циклы:

* Объекты RxMicro компонентов создаются в сгенерированных процессором аннотаций классах и регистрируются в RxMicro runtime container.
Когда необходимо получить ссылку на RxMicro компонент, пользовательский класс запрашивает ее в RxMicro runtime container.
* Объекты пользовательских компонентов создаются разработчиком в коде самостоятельно.

Из-за отличия в жизненных циклах двух типов компонентов RxMicro также поддерживает два типа альтернатив:

* *альтернативы RxMicro компонентов*;
* *альтернативы пользовательских компонентов*.

Эти типы альтернатив отличаются алгоритмами внедрения в тестируемый класс.

<<<

include::_alternatives/rxmicro-component-injection-algorythm.adoc[]

<<<

include::_alternatives/user-component-injection-algorythm.adoc[]

<<<

include::_alternatives/simplest-example.adoc[]

<<<

include::_alternatives/component-with-constructor.adoc[]

<<<

include::_alternatives/ambiguity-resolving.adoc[]

<<<

include::_alternatives/cdi-support.adoc[]