:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[testing-alternatives-section]]
=== Альтернативы

Для эффективного модульного тестирования the RxMicro framework поддерживает механизм альтернатив.

*Альтернативы* - это тестовые компоненты, почти всегда являющиеся моками, с заранее определенным поведением, которые внедряются by the RxMicro framework в тестируемые классы.
Альтернативы являются мощным механизмом для написания модульных тестов.

The RxMicro framework поддерживает альтернативы только для <<{testing}#testing-rest-based-microservice-tests-section,тестов REST-based микросервиса>> и <<{testing}#testing-component-tests-section,модульных тестов компонента>>.

При разработке микросервисного проекта выделяют два типа компонентов:

* _RxMicro компонент_ - это класс, который является частью of the RxMicro framework (например `HttpClientFactory`) или класс, генерируемый процессором аннотаций (Data Repository, Rest client, etc).
* _Пользовательский компонент_ - это класс написанный разработчиком и который является частью микросервисного проекта.

У этих двух типов компонентов разные жизненные циклы:

* Объекты of the RxMicro components создаются в сгенерированных процессором аннотаций классах и регистрируются в runtime container.
Когда необходимо получить ссылку на RxMicro component, пользовательский класс запрашивает ее в runtime container.
* Объекты пользовательских компонентов создаются разработчиком в коде самостоятельно.

Из-за отличия в жизненных циклах двух типов of the RxMicro components также поддерживает два типа альтернатив:

* *альтернативы of the RxMicro components*;
* *альтернативы пользовательских компонентов*.

Эти типы альтернатив отличаются алгоритмами внедрения в тестируемый класс.

<<<

include::_alternatives/rxmicro-component-injection-algorythm.adoc[]

<<<

include::_alternatives/user-component-injection-algorythm.adoc[]

<<<

include::_alternatives/simplest-example.adoc[]

<<<

include::_alternatives/component-with-constructor.adoc[]

<<<

include::_alternatives/ambiguity-resolving.adoc[]

<<<

include::_alternatives/cdi-support.adoc[]
