:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../../

==== Применение знаний о модуле `rxmicro.json`

Для корректного написания <<{testing}#testing-section,тестов>> необходимо общее представление о модуле `rxmicro.json`.

Рассмотрим пример микросервиса, возвращающего результат в формате JSON объекта:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/json/src/main/java/io/rxmicro/examples/json/MicroService.java[tag=content,indent=0]
----

Класс `Response` - Java модель HTTP ответа в JSON формате:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/json/src/main/java/io/rxmicro/examples/json/Response.java[tag=content,indent=0]
----
<1> Вложенный JSON объект.
<2> JSON массив числового типа.
<3> Строковый тип данных.
<4> Числовой тип данных целого типа.
<5> Числовой тип данных типа с плавающей точкой.
<6> Логический тип данных.

Класс `Child` - Java модель вложенного JSON объекта:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/json/src/main/java/io/rxmicro/examples/json/Child.java[tag=content,indent=0]
----

[TIP]
====
Для упрощения каждое поле модели ответа, сразу же инициализируется тестовыми данными.
====

В результате микросервис возвращает следующий JSON объект:

[source,json]
----
{
  "child": {
    "integer": 20
  },
  "values": [
    25,
    50,
    75,
    100
  ],
  "string": "text",
  "integer": 10,
  "decimal": 0.1234,
  "logical": true
}
----

В процессе написания <<{testing}#testing-rest-based-microservice-tests-section,теста REST-based микросервиса>> или <<{testing}#testing-integration-tests-basic-section,интеграционного теста>> необходимо сравнить ожидаемый JSON ответ с тем, что возвращает REST-based микросервис.
_(Возвращаемый микросервисом ответ доступен с помощью метода:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http-client/src/main/java/io/rxmicro/http/client/ClientHttpResponse.java#L38[`ClientHttpResponse.body()`^])_:

[source,java]
----
@RxMicroRestBasedMicroServiceTest(MicroService.class)
final class MicroServiceTest {
    //..
    @Test
    void Should_return_Response() {
        final ClientHttpResponse response = httpClient.get("/").join();
        final Object actualBody = response.body(); // <1>
        // ...
    }
}
----
<1>  Метод `ClientHttpResponse.body()` возвращает тело HTTP ответа.
Так как REST-based микросервис возвращает JSON объект, то данный метод возвращает результат в виде объекта <<core-json-type-mapping,`java.util.Map<java.lang.String, java.lang.Object>`>>.

Поэтому, чтобы сравнить JSON объекты, необходимо создать объект `java.util.Map<java.lang.String, java.lang.Object>`, содержащий ожидаемые свойства JSON объекта:

[source,java]
----
@RxMicroRestBasedMicroServiceTest(MicroService.class)
final class MicroServiceTest {
    //..
    @Test
    void Should_return_Response() {
        final ClientHttpResponse response = httpClient.get("/").join();
        final Object actualBody = response.body(); // <1>
        final Object expectedBody = Stream.of(
                Map.entry("child", Map.of(
                        "integer", new io.rxmicro.json.JsonNumber("20")
                )),
                Map.entry("values", List.of(
                        new io.rxmicro.json.JsonNumber("25"),
                        new io.rxmicro.json.JsonNumber("50"),
                        new io.rxmicro.json.JsonNumber("75"),
                        new io.rxmicro.json.JsonNumber("100")
                )),
                Map.entry("string", "text"),
                Map.entry("integer", new io.rxmicro.json.JsonNumber("10")),
                Map.entry("decimal", new io.rxmicro.json.JsonNumber("0.1234")),
                Map.entry("logical", true)
        ).collect(Collectors.toMap(
                Map.Entry::getKey,
                Map.Entry::getValue,
                (u, v) -> u, LinkedHashMap::new
        )); // <2>
        assertEquals(expectedBody, actualBody); // <3>
    }
}
----
<1> Возвращаемый микросервисом JSON объект.
<2> Ожидаемый JSON объект.
<3> Сравнение JSON объектов с помощью метода
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Object.html#equals(java.lang.Object)[`java.lang.Object.equals()`^].

[IMPORTANT]
====
Согласно https://tools.ietf.org/html/rfc7159#page-6[JSON спецификации^], в JSON объекте порядок свойств неопределен.

Т.е. JSON объекты:

[source,json]
----
{
    "firstname" : "David",
    "lastname" : "Smith"
}
----

и

[source,json]
----
{
    "lastname" : "Smith",
    "firstname" : "David"
}
----

считаются одинаковыми.

*RxMicro всегда упорядочивает свойства JSON объекта!*

*Таким образом порядок JSON свойств всегда соответствует порядку полей в Java модели!*

Благодаря этому Вы можете сравнивать JSON объекты представленные в виде `java.util.Map<java.lang.String, java.lang.Object>` с помощью метода
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Object.html#equals(java.lang.Object)[`java.lang.Object.equals()`^].
====

Для удобства создания ожидаемого JSON объекта, рекомендуется использовать утилитный класс
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/json/JsonFactory.java[`JsonFactory`^].
Данный класс упорядочивает JSON свойства и автоматически конвертирует все
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Number.html[`java.lang.Number`^] типы в тип
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-json/src/main/java/io/rxmicro/json/JsonNumber.java[`io.rxmicro.json.JsonNumber`^]:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/json/src/test/java/io/rxmicro/examples/json/MicroServiceTest.java[tag=content,indent=0]
----
<1> Возвращаемый микросервисом JSON объект.
<2> Ожидаемый JSON объект.
<3> Сравнение JSON объектов с помощью метода
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Object.html#equals(java.lang.Object)[`java.lang.Object.equals()`^].
<4> Для создания JSON объекта, рекомендуется использовать метод:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/json/JsonFactory.java[`JsonFactory.jsonObject`^].
<5> Для создания JSON массива, рекомендуется использовать метод:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/json/JsonFactory.java[`JsonFactory.jsonArray`^].

[NOTE]
====
Интерфейс {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http-client/src/main/java/io/rxmicro/http/client/ClientHttpResponse.java[`ClientHttpResponse`^]
кроме метода `body()` также содержит методы `bodyAsBytes()` и `bodyAsString()`.

Поэтому в тесте Вы можете сравнивать JSON объекты, сравнивая их строковое представление или используя стороннюю Java библиотеку, поддерживающую JSON формат.
(Например https://github.com/stleary/JSON-java[`JSON-java`^], https://javaee.github.io/jsonp/[`Java API for JSON Processing`^], и др.)

*Таким образом RxMicro рекомендует использовать модуль `rxmicro.json` для сравнения JSON объектов, но в тоже же время предоставляет Вам возможность использовать любом другой JSON фреймворк!*
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}json
include::../../___notes/full-source-code-of-example.adoc[]
