:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

=== HTTP Requests Server Validation

После активации модуля `rxmicro.validation` в дескрипторе `module-info.java`

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-basic/src/main/java/module-info.java[tag=content,indent=0]
----
<1> `rxmicro.validation` - модуль валидации запросов и ответов.

разработчик может использовать <<validation-std-constraints-section, built-in constraints>> для валидации параметров HTTP запроса:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-basic/src/main/java/io/rxmicro/examples/validation/server/basic/MicroService.java[tag=content,indent=0]
----
<1> Параметр `email` аннотирован аннотацией `@Email`.

Благодаря данной аннотации процессор аннотаций автоматически сгенерирует валидатор для HTTP параметра `email`:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-basic/src/test/java/io/rxmicro/examples/validation/server/basic/MicroServiceTest.java[tag=content,indent=0]
----
<1> При активации модуля `rxmicro.validation` все параметры запроса автоматически считаются обязательными. +
_(Поэтому the `RxMicro Annotation Processor` автоматически добавляет `required` валидатор для каждого параметра.
Если параметр должен быть `optional`, необходимо поле модели аннотировать аннотацией
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-validation/src/main/java/io/rxmicro/validation/constraint/Nullable.java[`@Nullable`^].)_
<2> Если параметры запросы некорректные, HTTP сервер автоматически возвращает статус код `400` и JSON объект <<{rest-controller}#rest-controller-errors-model-inline,стандартной структуры с детальным описанием ошибки.>>
<3> При возникновении ошибки валидации HTTP запроса, обработчик запроса из REST контроллера не вызывается.
<4> Если параметры запроса корректные, то управление передается обработчику запросов из REST контроллера.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}validation-server-basic
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
