:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]
:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

=== HTTP Responses Client Validation

После активации модуля `rxmicro.validation` в дескрипторе `module-info.java`

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-client-basic/src/main/java/module-info.java[tags=content]
----
<1> `rxmicro.validation` - модуль валидации запросов и ответов.

разработчик может использовать <<validation-std-constraints-section, built-in constraints>> для валидации полей HTTP ответа:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-client-basic/src/main/java/io/rxmicro/examples/validation/client/basic/model/Response.java[tags=content]
----
<1> Параметр `email` аннотирован аннотацией `@Email`.

После настройки класса модели, данную модель необходимо использовать в REST клиенте:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-client-basic/src/main/java/io/rxmicro/examples/validation/client/basic/RESTClient.java[tags=content]
----

В процессе преобразования содержимого HTTP ответа в объект класса `Response`, автоматически будет вызываться валидатор:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-client-basic/src/test/java/io/rxmicro/examples/validation/client/basic/RESTClientTest.java[tags=content]
----
<1> Если REST client будет получать валидный HTTP ответ, то никаких ошибок не возникнет.
<2> Если поле `email` будет некорректным в HTTP ответе, то REST client вернет сигнал ошибки.
<3> В случае некорректности HTTP ответа, возвращается исключение класса `UnexpectedResponseException` с детальным текстовым сообщением.
<4> *Так как `CompletableFuture` в случае получения сигнала об ошибке ВСЕГДА возвращает исключение класса `CompletionException`, то для получения исходного класса исключения, который был выброшен в процессе отложенного вычисления необходимо использовать утилитный метод
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-common/src/main/java/io/rxmicro/common/util/Exceptions.java#L79[`Exceptions.getRealThrowable`^]!*

[NOTE]
====
Для ознакомления с возможностями of the RxMicro framework для валидации HTTP запросов в REST клиентах, рекомендуем обратится к примеру:

{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}validation-client-all-types[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}validation-client-all-types`^]
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}validation-client-basic
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
