:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[validation-response-section]]
=== HTTP Responses Server Validation

Кроме валидации HTTP запросов RxMicro также предоставляет возможность валидировать HTTP ответы.

_(Валидация HTTP ответов может быть полезна для выявления ошибок в алгоритмах реализации бизнес задачи.
Например вместо возвращения клиенту некорректной модели ответа микросервис будет выбрасывать ошибку.
При таком подходе увеличивается скорость поиска ошибок и отладки исходного кода, выполняющего бизнес задачу.)_

[IMPORTANT]
====
Если текущая реализация бизнес задачи не содержит каких-либо ошибок, то валидация HTTP ответов будет бессмысленно расходовать вычислительные ресурсы.
В таком случае валидация HTTP ответов должна быть деактивирована!
====

*По умолчанию RxMicro не генерирует валидаторы ответов!*

Чтобы информировать the `RxMicro Annotation Processor` о необходимости генерации валидаторов HTTP ответа, необходимо использовать аннотацию <<{rest-controller}#rest-controller-rest-server-generator-config-section,`@RestServerGeneratorConfig`>>:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-response/src/main/java/module-info.java[tag=content,indent=0]
----
<1> Параметр `generateResponseValidators` позволяет включать/отключать опцию генерации валидаторов HTTP ответа для всех обработчиков в проекте. +
_(Значение `AUTO_DETECT` означает, что валидаторы будут сгенерированы только в том случае, если разработчик добавит модуль `rxmicro.validation` в дескриптор `module-info.java`.
Так как данный модуль добавлен, то the `RxMicro Annotation Processor` сгенерирует валидаторы для HTTP ответа.)_

Класс модели HTTP ответа может содержать любые built-in or custom constraint annotations:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-response/src/main/java/io/rxmicro/examples/validation/server/response/model/Response.java[tag=content,indent=0]
----
<1> В данном примере поле `message` не содержит никаких constraint annotations явно.
Но из-за того что в дескрипторе `module-info.java` добавлен модуль `rxmicro.validation`, то все поля модели не помеченные аннотацией
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-validation/src/main/java/io/rxmicro/validation/constraint/Nullable.java[`@Nullable`^] автоматически являются обязательными.
_(Т.е. такие поля неявно помечаются виртуальной constraint annotation `@Required`.)_

Для эмуляции некорректного бизнес значения, в обработчике запроса передается `null` значение в поле `message`:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-response/src/main/java/io/rxmicro/examples/validation/server/response/MicroService.java[tag=content,indent=0]
----

В случае невалидности HTTP ответа, RxMicro возвращает HTTP ответ со статусом `500` и <<{rest-controller}#rest-controller-errors-model-inline, стандартной моделью ошибки>>:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/validation-server-response/src/test/java/io/rxmicro/examples/validation/server/response/MicroServiceTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}validation-server-response
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
