:FRAGMENT_RELATIVE_DIR:
include::___fragment-settings.adoc[]

*RxMicro* - это современный, JVM-based, full stack framework, спроектированный для разработки распределенных реактивных приложений, использующих микросервисную архитектуру.

The RxMicro framework предоставляет разработчикам удобный инструмент, который позволяет сконцентрироваться на написании бизнес логики приложения.
А рутинные и стандартные операции без которых запуск приложения невозможен делегировать фреймворку.

The RxMicro framework - маленький и легковесный.
Несмотря на то что the RxMicro framework разработан для создания микросервисов, разработчик может с легкостью использовать отдельные *RxMicro* модули для разработки любого типа приложения используя реактивный подход.

The RxMicro framework - фреймворк, который использует https://en.wikipedia.org/wiki/Reactive_programming[реактивный подход к программированию^] в качестве основного и *единственного* подхода при проектировании микросервисов.

*Какие-либо блокирующие операции не поддерживаются!*

[IMPORTANT]
====
При разработке проекта via the RxMicro framework, используйте только *неблокирующие драйверы* для взаимодействия с базами данных, сетевыми соединениями и файлами.
В противном случае Ваш проект будет работать *очень медленно* и не сможет обслужить огромное число запросов от клиентов.
====

<<<

include::_introduction/features.adoc[]

<<<

include::_introduction/benefits.adoc[]

<<<

include::_introduction/requirements.adoc[]
