:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[rxmicro-annotation-processor-options-section]]
=== `RxMicro Annotation Processor` Options

The `RxMicro Annotation Processor` supports the following options:

.Options supported by the `RxMicro Annotation Processor`.
|===
|*Option*|*Description* |*Type* |*Default value*

|`RX_MICRO_MAX_JSON_NESTED_DEPTH`
|maximum stack size for recursive invocations when analyzing models containing JSON nested objects.
|`positive int`
|`20`

|`RX_MICRO_LOG_LEVEL`
|`RxMicro Annotation Processor` logging level.
|Enum {`OFF`, `INFO`, `DEBUG`}
|`INFO`

|`RX_MICRO_DOC_DESTINATION_DIR`
|the resulting directory <<{project-documentation}#project-documentation-section,for generated documentation>>.
|`String`
|Asciidoc: `./src/main/asciidoc`

|`RX_MICRO_BUILD_UNNAMED_MODULE`
|the <<{java-integration}#java-integration-unnamed-module,`unnamed module`>> support for a microservice project.
|`boolean`
|`false`

|`RX_MICRO_DOC_ANALYZE_PARENT_POM`
|This option allows analyzing parent `pom.xml` if child `pom.xml` does not contain required property.
|`boolean`
|`true`

|`RX_MICRO_STRICT_MODE`
|Activates additional validation rules during compilation process.

*The RxMicro team strong recommends enabling the strict mode for your production code.*
|`boolean`
|`false`
|===

These options are set using the compiler arguments in `maven-compiler-plugin`:

[source,xml]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <release>11</release>
        <compilerArgs>
            <arg>-ARX_MICRO_MAX_JSON_NESTED_DEPTH=20</arg>
            <arg>-ARX_MICRO_LOG_LEVEL=INFO</arg>
            <arg>-ARX_MICRO_DOC_DESTINATION_DIR=./src/main/asciidoc</arg>
            <arg>-ARX_MICRO_BUILD_UNNAMED_MODULE=false</arg>
            <arg>-ARX_MICRO_DOC_ANALYZE_PARENT_POM=true</arg>
            <arg>-ARX_MICRO_STRICT_MODE=false</arg>
        </compilerArgs>
    </configuration>
</plugin>
----

[IMPORTANT]
====
Note that it is necessary to add the `-A` prefix before setting the value of the option.

The common format is as follows: `-A${name}=${value}`.
For example: `-ARX_MICRO_LOG_LEVEL=OFF`
====
