:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== Base Model

Java applications use `java.lang.Object.toString()` method very often for debug purposes.
Thus a developer must override this method for all model classes in his(her) project.

To help with overriding of this method for all model classes the RxMicro framework introduces the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-common/src/main/java/io/rxmicro/common/model/BaseModel.java[`BaseModel`^] class.
This class uses the `reflection` to generate string representation of the model class on fly.

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/base_model/CustomModel.java[tag=content,indent=0]
----

[IMPORTANT]
====
The `reflection` mechanism is slow one, so use the generated string representation of the model class only for debug purposes!
====

[NOTE]
====
According to {WHAT-IS-JPMS-LINK}[`JPMS`^] requirements all `reflection` access must be configured at the `module-info.java` descriptor using `opens` instructions.
It means that for correct usage the `BaseModel` feature, it is necessary to add the following instruction:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/base-model/src/main/java/module-info.java[tag=content,indent=0]
----

where `io.rxmicro.examples.base.model.model.package4` is the package that contains custom model classes.

But the `BaseModel` feature is designed for debug purposes, so required `opens` instructions are added automatically via generated <<core-how-it-works-environment-customizer,`$$EnvironmentCustomizer`>> class if You do not add these instructions manually!
So You can use the `BaseModel` feature without any `module-info.java` modifications for Your project!
====
