:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[core-dont-block-current-thread]]
=== Don't Block Current Thread!

In modern computer architecture, IO operations are the slowest ones.
As a result, when using
https://en.wikipedia.org/wiki/Multithreading_(computer_architecture)[multithreading programming model^], the use of CPU and RAM is extremely inefficient.
For a single-user monolithic application such inefficiency is imperceptible.
But for a multi-user distributed application with a much higher number of IO operations, this problem generates huge financial costs for additional hardware and coordination between client data streams (Read more: https://en.wikipedia.org/wiki/C10k_problem[C10k problem^]).

Therefore, the https://en.wikipedia.org/wiki/Event-driven_architecture[Event-driven architecture (EDA)^] is used for efficient use of the hardware resources of a multi-user distributed application.

The most popular Java framework that uses Event-driven architecture for IO operations is https://netty.io[Netty^].
To write efficient programs using Netty, it is necessary to comply with certain rules and restrictions.
The most important of these is the following requirement: *Don't block current thread!*

The RxMicro framework is a framework that runs on Netty.
Therefore, all requirements for applications that utilize Netty also cover the RxMicro framework.

==== Prohibited Operations

Consequently, when writing microservice applications based on the RxMicro framework, the following operations are *prohibited*:

* Data reading from a socket or file in a blocking style using `java.io.InputStream` and child classes.
* Data writing to a socket or file in a blocking style using `java.io.OutputStream` and child classes.
* Interaction with a database using of the blocking driver (all `JDBC` drivers).
* Waiting on a lock or a monitor (`java.util.concurrent.locks.Lock`, `Object.wait`).
* Putting the thread into sleep mode (`Thread.sleep`, `TimeUnit.sleep`).
* Any other https://en.wikipedia.org/wiki/Blocking_(computing)[*blocking operations*^].

==== Recommended Approach

The absence of blocking operations in the microservice allows handling many concurrent connections, using a small number of threads and, as a result, to effectively use hardware resources of the computer.

Therefore, when designing microservices via the RxMicro framework, You must follow by the following rule:

*When implementing a microservice, if the result can be obtained immediately, it must be returned immediately.*

*Otherwise, You must return
https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#specification[Publisher^] or
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[CompletableFuture^], which will generate the result later.*
