:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== Strings Formatting

While developing a software product it is necessary to format strings.

For this purpose, Java provides different approaches:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/format/Problem.java[tag=content,indent=0]
----
<1> To generate an SQL query, You need to use `$1` placeholder. +
_(This placeholder depends on the used {R2DBC-SPEC-ROOT-URL}#statements.parameterized[R2DBC driver^].
For postgresql, it's a `$1` symbol.)_
<2> To generate a logging message, You need to use `{}` placeholder. +
_(This placeholder depends on the logging library used.
For SLF4J, it's a `{}` symbol.)_
<3> To generate an error message, You need to use `%s` placeholder from a separate utility class, for example
{JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/String.html#format(java.lang.String,java.lang.Object...)[`String.format`^].

While writing the code, a developer can easily confuse the required placeholder.

*To avoid such a problem, the RxMicro framework recommends using the universal `?` placeholder*

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/format/Solution.java[tag=content,indent=0]
----
<1> To generate an SQL query, You need to use `?` placeholder.
<2> To generate a logging message, You need to use `?` placeholder.
<3> To generate an error message, You need to use `?` placeholder.
