:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== Logger

https://en.wikipedia.org/wiki/Data_logger[*Logger*^] is an integral component of any software system.

The RxMicro framework provides the `rxmicro.logger` module for logging important events during the work of microservices.

Creation and usage of a logger in the source code is no different from http://www.java-logging.com/[other logging frameworks^]:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/logger/src/main/java/io/rxmicro/examples/logger/MicroService.java[tag=content,indent=0]
----
<1> Logger creation for the current microservice class.
<2> Logging of a message with `INFO` message.

The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-logger/src/main/java/io/rxmicro/logger/Logger.java[`Logger`^] interface is an abstraction over the real logger.

At the moment, there is only one implementation of this interface that delegates logging to the
https://docs.oracle.com/javase/10/core/java-logging-overview.htm[`java.logging`^] module.

[[core-logger-config-file-inline]]
The main configuration file of the `java.logging` logger is the `jul.properties` classpath resource.

[NOTE]
====
If classpath contains the `jul.test.properties` resource, then this resource overrides *all* configurations of the `jul.properties` resource.

This function allows configuring the logger for a test environment.
====

The `jul.properties` classpath resource must contain a configuration http://tutorials.jenkov.com/java-logging/configuration.html[in the standard format for the `java.logging` module^].

Example of logger configuration:

[source,properties]
----
.level=INFO
io.rxmicro.config.level=DEBUG
----

[IMPORTANT]
====
The `rxmicro.logger` module supports all logging levels from the following sets: `{OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL}` and `{OFF, SEVERE, CONFIG, INFO, FINE, FINEST, ALL}`.

Therefore, in the `jul.properties` configuration file You can use any logging level.
When activating the `java.logging` logger, the RxMicro framework automatically converts levels from a set of `{OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL}` into `{OFF, SEVERE, CONFIG, INFO, FINE, FINEST, ALL}`.

This option makes it possible to use unsupported but widely used in other logging frameworks logging levels for the `java.logging` logger.
====

By default the `INFO` logging level is activated for the logger, and the `ConsoleHandler` appender, which outputs all logging information into `System.out`.

[TIP]
====
The `rxmicro.logger` module contains only the basic functions necessary for logging.

If these functions are not enough You can use any other logging framework:
http://logback.qos.ch/[`Logback`^],
https://logging.apache.org/log4j/2.x/[`Apache Log4j 2`^] and others.
====
