:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

=== Native Transports

RxMicro uses https://netty.io/[`Netty`^] to perform asynchronous non-blocking IO operations.
To increase productivity, `Netty` allows the use of https://netty.io/wiki/native-transports.html[`native transports`^].

To enable `native transports` feature, add one of the following dependencies:

[source,xml]
----
<dependency>
    <groupId>io.rxmicro</groupId>
    <artifactId>rxmicro-netty-native-linux</artifactId>
    <version>${rxmicro.version}</version>
</dependency>
----

[source,xml]
----
<dependency>
    <groupId>io.rxmicro</groupId>
    <artifactId>rxmicro-netty-native-osx</artifactId>
    <version>${rxmicro.version}</version>
</dependency>
----

[source,xml]
----
<dependency>
    <groupId>io.rxmicro</groupId>
    <artifactId>rxmicro-netty-native</artifactId>
    <version>${rxmicro.version}</version>
</dependency>
----

[source,xml]
----
<dependency>
    <groupId>io.rxmicro</groupId>
    <artifactId>rxmicro-netty-native-all</artifactId>
    <version>${rxmicro.version}</version>
</dependency>
----

* The `rxmicro-netty-native-linux` dependency adds the `netty-transport-native-epoll` artifact;
* The `rxmicro-netty-native-osx` dependency adds the `netty-transport-native-kqueue` artifact;
* The `rxmicro-netty-native` dependency activates `native transports` for the current platform:
** in case of the `Linux` current platform, the `netty-transport-native-epoll` artifact is added;
** in case of the `OSX` current platform, the `netty-transport-native-kqueue` artifact is added;
** otherwise `native transports` is not activated for the current platform;
* the `rxmicro-netty-native-all` dependency adds the `netty-transport-native-epoll` and `netty-transport-native-kqueue` artifacts.

[TIP]
====
Adding a dependency to the microservice project:

[source,xml]
----
<dependency>
    <groupId>io.rxmicro</groupId>
    <artifactId>rxmicro-netty-native-linux</artifactId>
    <version>${rxmicro.version}</version>
</dependency>
----

instead of

[source,xml]
----
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-transport-native-epoll</artifactId>
    <version>${netty.version}</version>
    <classifier>linux-x86_64</classifier>
</dependency>
----

allows to use the `Netty native transports` library version compatible with all other `Netty` libraries used by the RxMicro framework.

Therefore, the *`rxmicro-netty-native-...` modules don't contain any logic.* *They just add `Netty native transports` libraries of the correct version.*
====

If `native transports` has been successfully activated, the information message about the start of the HTTP server will display the corresponding type of transport.

[source,text,subs="verbatim,quotes"]
----
2020-02-02 20:14:11.707 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at 0.0.0.0:8080 using *EPOLL* transport in 500 millis. # <1>
----
<1> The `using EPOLL transport` message format means that `Netty` will use the `netty-transport-native-epoll` library.

[source,text,subs="verbatim,quotes"]
----
2020-02-02 20:14:11.707 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at 0.0.0.0:8080 using *KQUEUE* transport in 500 millis. # <1>
----
<1> The `using KQUEUE transport` message format means that `Netty` will use the `netty-transport-native-kqueue` library.
