:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[core-reactive-libraries-support]]
=== Reactive Libraries Support

The RxMicro framework supports the following reactive programming libraries:

- {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^]:
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[CompletableFuture^],
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[CompletionStage^];
- {REACTOR-CORE-DOC-USER_GUIDE}[*Project Reactor*: Mono, Flux^];
- {RX-JAVA-USER-GUIDE}[*RxJava*: Completable, Single, Maybe, Flowable^];

[[core-reactive-bussiness-process-result-types-section]]
==== Expected Business Process Results

When writing reactive programs, the following 4 expected results of any business process are possible:

. It is important to complete the business process, but the result is missing or unimportant.
. The business process returns the result in a single instance or nothing.
. The business process returns the required result in a single instance.
. The business process returns the result as `(0 .. n)` object stream.

When writing a business service using reactive libraries, it is recommended to comply with the following agreements:

[[core-reactive-bussiness-process-reactive-class-mapping-table]]
.Which class from a reactive library must be choose?
|===
|*Reactive Library*|*java.util.concurrent* |*Project Reactor* |*RxJava3*

|*Without result*
|CompletableFuture<Void>
CompletionStage<Void>
|Mono<Void>
|Completable

|*Optional result*
|CompletableFuture<Optional<MODEL>>
CompletionStage<Optional<MODEL>>
|Mono<MODEL>
|Maybe<MODEL>

|*Required result*
|CompletableFuture<MODEL>
CompletionStage<MODEL>
|Mono<MODEL>
|Single<MODEL>

|*Stream result*
|CompletableFuture<List<MODEL>>
CompletionStage<List<MODEL>>
|Flux<MODEL>, Mono<List<MODEL>>
|Flowable<MODEL>, Single<List<MODEL>>
|===

[TIP]
====
*The following types of results `Flux<MODEL>` and `Mono<List<MODEL>>`, as well as `Flowable<MODEL>`, `Single<List<MODEL>>` are not absolutely equivalent!*

For the `Flux<MODEL>` and `Flowable<MODEL>` types, the result handler can be invoked before all data is received from a data source, e.g. from a database.

Whereas for `Mono<List<MODEL>>` and `Single<List<MODEL>>`
the result handler is invoked *only* after *all* the data is received from the data source!
====

==== Recommendations for Choosing a Library

General recommendation for choosing a reactive programming library when using the RxMicro framework:

. If Your microservice contains simple logic, You can use the lightweight and Java-provided
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^] library, represented by the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture`^] class and the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage`^] interface.
. If Your microservice contains more complex logic, to describe which You need to use
http://reactivex.io/documentation/operators.html[complex operators^], it is recommended to choose *Project Reactor* or *RxJava*.
. When choosing between the *Project Reactor* and *RxJava* follow the recommendations:
.. If You are more familiar with the *Project Reactor*, then use it, otherwise use *RxJava*.
.. If You need `r2dbc` based reactive SQL repositories (`rxmicro.data.sql.r2dbc` module), then use the *Project Reactor*. +
_(Since `r2dbc` drivers already use the *Project Reactor*.)_

Thus, when writing microservices via the RxMicro framework, You can use any Java reactive programming library that You prefer!

[NOTE]
====
*FYI* All libraries support a blocking getting of the result:

[source,java]
----
public final class BlockingGetResult {

    public static void main(final String[] args) {
        final String blockingResult1 =
                CompletableFuture.completedFuture("Hello")
                        .join();

        final String blockingResult2 =
                Mono.just("Hello")
                        .block();

        final String blockingResult3 =
                Single.just("Hello")
                        .blockingGet();

        System.out.println(blockingResult1);
        System.out.println(blockingResult2);
        System.out.println(blockingResult3);
    }

}
----

The main need in blocking getting of the result, using reactive programming, arises at Unit testing implementation.
Since the main popular frameworks for unit testing (https://junit.org/junit5/[`JUnit`^], https://testng.org/[`TestNG`^], etc.) use the usual thread (blocking) programming model.
====
