:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[testing-alternatives-section]]
=== Alternatives

For efficient unit testing, the RxMicro framework supports the mechanism of alternatives.

*Alternatives* are test components, usually being mocks with predefined behaviors, that are injected by the RxMicro framework into the tested classes.
Alternatives are a powerful mechanism for writing unit tests.

The RxMicro framework supports alternatives only for <<{testing}#testing-rest-based-microservice-tests-section,REST-based microservice tests>> and <<{testing}#testing-component-tests-section,component unit tests>>.

When developing a microservice project, two types of components are distinguished:

* _RxMicro component_ - a class that is part of the RxMicro framework (for example, `HttpClientFactory`) or a class generated by the annotation processor (Data Repository, Rest client, etc).
* _Custom component_ - a developer-written class that is part of a microservice project.

These two types of components have different life cycles:

* The instances of the RxMicro components are created in the classes generated by the `RxMicro Annotation Processor`, and are registered in the runtime container.
When a reference to the RxMicro component is required, the custom class requests it in the runtime container.
* The instances of custom components are created independently by the developer in the code.

Due to the difference in life cycles between the two types of the RxMicro components, the RxMicro framework also supports two types of alternatives:

* *alternatives of the RxMicro components*;
* *alternatives of custom components*.

These types of alternatives differ in the algorithms of injection into the tested class.

<<<

include::_alternatives/rxmicro-component-injection-algorythm.adoc[]

<<<

include::_alternatives/user-component-injection-algorythm.adoc[]

<<<

include::_alternatives/simplest-example.adoc[]

<<<

include::_alternatives/component-with-constructor.adoc[]

<<<

include::_alternatives/ambiguity-resolving.adoc[]

<<<

include::_alternatives/cdi-support.adoc[]
