:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[testing-annotations-section]]
=== `RxMicro Test Annotations`

RxMicro поддерживает дополнительные `RxMicro Test annotations`, расширяющие возможности тестовых фреймворков https://junit.org/junit5/[JUnit 5^] и https://site.mockito.org/[Mockito^]
и добавляющие дополнительные функции, необходимые для эффективного написания всех поддерживаемых видов тестов.

[TIP]
====
RxMicro поддерживает два типа аннотаций:

* `RxMicro annotations`, используемые процессором аннотаций в процессе компиляции и соответственно доступные *только в процессе компиляции*.
* `RxMicro Test annotations`, используемые тестирующим фреймворком в процессе запуска тестов и соответственно доступные, используя механизм `reflection`.

Данные типы аннотаций не взаимодополняющие друг друга!
Каждый из указанных типов предназначен для выполнения своих задач.

*Поэтому при написании тестов будьте внимательны и не используйте `RxMicro annotations`, т.к. они недоступны тестовому фреймворку!*
====

.Supported `RxMicro Test Annotations`
[cols="1,3"]
|===
|*Аннотация*|*Описание*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/Alternative.java[`@Alternative`^]
|Объявляет поле тестового класса <<{testing}#testing-alternatives-section,альтернативой>>.

_RxMicro поддерживает альтернативы только для <<{testing}#testing-rest-based-microservice-tests-section,тестов REST-based микросервиса>> и <<{testing}#testing-component-tests-section,модульных тестов компонента>>._

[[testing-annotations-WithConfig-inline]]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/WithConfig.java[`@WithConfig`^]
|Объявляет *статическое* поле тестового класса конфигурацией, которую перед запуском теста необходимо зарегистрировать в менеджере конфигураций.

_Данная аннотация позволяет объявлять конфигурацию с <<{core}#core-config-java-classes-section,помощью Java классов>>._
_(Определенная таким образом конфигурация доступна только в процессе выполнения теста.)_

Исходный код проекта, использующего аннотацию `@WithConfig`, доступен по ссылке:

{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-microservice-with-config[`testing-microservice-with-config`^]

_RxMicro поддерживает тестовую конфигурацию только для <<{testing}#testing-rest-based-microservice-tests-section,тестов REST-based микросервиса>> и <<{testing}#testing-component-tests-section,модульных тестов компонента>>._

[[testing-annotations-SetConfigValue-inline]]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/SetConfigValue.java[`@SetConfigValue`^]
|Прозволяет переопределить значение по умолчанию для любой конфигурации, доступной только для тестового окружения.

_Данная аннотация позволяет объявлять конфигурацию с <<{core}#core-config-annotations-section,помощью аннотаций>>._
_(Определенная таким образом конфигурация доступна только в процессе выполнения теста.
Т.е. данная аннотация является аналогом аннотации {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/DefaultConfigValue.java[`DefaultConfigValue`^]!)_

_RxMicro поддерживает тестовую конфигурацию только для <<{testing}#testing-rest-based-microservice-tests-section,тестов REST-based микросервиса>> и <<{testing}#testing-component-tests-section,модульных тестов компонента>>._

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClientSettings.java[`@BlockingHttpClientSettings`^]
|Позволяет <<{testing}#testing-BlockingHttpClient-settings-section,настраивать компонент>>
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] для выполнения HTTP запросов в тестах.

_(Данная аннотация применима только к полям с типом
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^].)_

_RxMicro поддерживает компонент `BlockingHttpClient` только для <<{testing}#testing-rest-based-microservice-tests-section,тестов REST-based микросервиса>> и <<{testing}#RxMicroIntegrationTest-Section,интеграционных тестов REST-based микросервисов>>._

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroRestBasedMicroServiceTest.java[`@RxMicroRestBasedMicroServiceTest`^]
|Объявляет тестовый класс <<{testing}#testing-rest-based-microservice-tests-section,тестом REST-based микросервиса>>.

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroComponentTest.java[`@RxMicroComponentTest`^]
|Объявляет тестовый класс <<{testing}#testing-component-tests-section,модульным тестом компонента>>.

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroIntegrationTest.java[`@RxMicroIntegrationTest`^]
|Объявляет тестовый класс <<{testing}#testing-integration-tests-section,интеграционным тестом REST-based микросервисов>>.

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeTest.java[`@BeforeTest`^]
|Используется для указания метода, который должен быть вызван by the RxMicro framework <<{testing}#testing-before-test-section,перед выполнением тестового метода>>.

_RxMicro поддерживает аннотацию `@BeforeTest` только для <<{testing}#testing-rest-based-microservice-tests-section,тестов REST-based микросервиса>> и <<{testing}#testing-component-tests-section,модульных тестов компонента>>._

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeIterationMethodSource.java[`@BeforeIterationMethodSource`^]
|Используется для указания методов, которые должны быть вызваны by the RxMicro framework перед <<{testing}#testing-before-test-section,выполнением каждой итерации параметризованного теста>>.

_RxMicro поддерживает аннотацию `@BeforeIterationMethodSource` только <<{testing}#testing-rest-based-microservice-tests-section,для тестов REST-based микросервиса>> и <<{testing}#testing-component-tests-section,модульных тестов компонента>>._

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java[`@InitMocks`^]
|Информирует тестовый фреймворк о необходимости <<{testing}#InitMocks-inline,создать моки и внедрить их в поля тестового класса>>, аннотированные с помощью аннотации
{MOCKITO-DOC-ROOT-URL}org/mockito/Mock.html[`@Mock`^].

_(Использование аннотации {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java[`@InitMocks`^]
предпочтительнее, чем аналогичной конструкции
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java#L34[`@ExtendWith(MockitoExtension.class)`^].)_
|===
