:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[testing-annotations-section]]
=== `RxMicro Test Annotations`

The RxMicro framework supports additional `RxMicro Test annotations`, that extend the features of the https://junit.org/junit5/[JUnit 5^] and https://site.mockito.org/[Mockito^]
test frameworks and add additional features required for efficient writing of all supported test types.

[TIP]
====
The RxMicro framework supports two types of annotations:

* The `RxMicro Annotations` used by the `RxMicro Annotation Processor` during the compiling and therefore available *only during the compilation process*.
* The `RxMicro Test Annotations` used by the test framework during the test run and therefore available using the `reflection` mechanism.

These types of annotations do not complement each other!
Each of these types is designed to perform its tasks.

*So when writing tests, be careful not to use the `RxMicro Annotations` as they are not available for the test framework!*
====

.Supported `RxMicro Test Annotations`
[cols="1,3"]
|===
|*Annotation*|*Description*

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/Alternative.java[`@Alternative`^]
|Declares the test class field as an <<{testing}#testing-alternatives-section,alternative>>.

_The RxMicro framework supports alternatives only for <<{testing}#testing-rest-based-microservice-tests-section,REST-based microservice tests>> and <<{testing}#testing-component-tests-section,component unit tests>>._

[[testing-annotations-WithConfig-inline]]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/WithConfig.java[`@WithConfig`^]
|Declares the *static* field of the test class as a configuration which must be registered in the configuration manager before starting the test.

_This annotation allows declaring a configuration using <<{core}#core-config-java-classes-section,Java classes>>._
_(The configuration defined in this way is only available while the test is running.)_

The source code of the project that uses the `@WithConfig` annotation, is available at the following link:

{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-microservice-with-config[`testing-microservice-with-config`^]

_The RxMicro framework supports test configuration only for <<{testing}#testing-rest-based-microservice-tests-section,REST-based microservice tests>> and <<{testing}#testing-component-tests-section,component unit tests>>._

[[testing-annotations-SetConfigValue-inline]]
|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/SetConfigValue.java[`@SetConfigValue`^]
|Allows overriding the default value for any configuration available only for the test environment.

_This annotation allows declaring a configuration using <<{core}#core-config-annotations-section,annotations>>._
_(The configuration defined in this way is only available while the test is running.
It means that this annotation is analogous to the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/DefaultConfigValue.java[`DefaultConfigValue`^] annotation!)_

_The RxMicro framework supports test configuration only for <<{testing}#testing-rest-based-microservice-tests-section,REST-based microservice tests>> and <<{testing}#testing-component-tests-section,component unit tests>>._

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClientSettings.java[`@BlockingHttpClientSettings`^]
|Allows to <<{testing}#testing-BlockingHttpClient-settings-section,configure the following component:>>
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^], in order to execute HTTP requests in tests.

_(This annotation applies only to the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] type fields.)_

_The RxMicro framework supports the `BlockingHttpClient` component only for <<{testing}#testing-rest-based-microservice-tests-section,REST-based microservice tests>> and <<{testing}#testing-integration-tests-section,REST-based microservice integration tests>>._

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroRestBasedMicroServiceTest.java[`@RxMicroRestBasedMicroServiceTest`^]
|Declares the test class as a <<{testing}#testing-rest-based-microservice-tests-section,REST-based microservice test>>.

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroComponentTest.java[`@RxMicroComponentTest`^]
|Declares the test class as a <<{testing}#testing-component-tests-section,component unit test>>.

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroIntegrationTest.java[`@RxMicroIntegrationTest`^]
|Declares the test class as a <<{testing}#testing-integration-tests-section,REST-based microservice integration test>>.

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeTest.java[`@BeforeTest`^]
|It is used to specify the method to be invoked by the RxMicro framework <<{testing}#testing-before-test-section,before running the test method>>.

_The RxMicro framework supports the `@BeforeTest` annotation only for <<{testing}#testing-rest-based-microservice-tests-section,REST-based microservice tests>> and <<{testing}#testing-component-tests-section,component unit tests>>._

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeIterationMethodSource.java[`@BeforeIterationMethodSource`^]
|It is used to specify the methods to be invoked by the RxMicro framework before <<{testing}#testing-before-test-section,performing each iteration of the parameterized test>>.

_The RxMicro framework supports the `@BeforeIterationMethodSource` annotation only for <<{testing}#testing-rest-based-microservice-tests-section,REST-based microservice tests>> and <<{testing}#testing-component-tests-section,component unit tests>>._

|{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java[`@InitMocks`^]
|Informs the test framework about the need to <<{testing}#InitMocks-inline,create mocks and inject them into the test class fields>>, annotated by the
{MOCKITO-DOC-ROOT-URL}org/mockito/Mock.html[`@Mock`^] annotation.

_(Using the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java[`@InitMocks`^]
annotation is preferable to the analogous
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java#L58[`@ExtendWith(MockitoExtension.class)`^] construction.)_
|===
