:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[testing-before-test-section]]
=== The `@BeforeThisTest` and `@BeforeIterationMethodSource` Annotations

In order to perform any actions before invoking the test method, the
https://junit.org/junit5/[JUnit 5^] framework provides a special {JUNIT5-DOC-ROOT-URL}api/org.junit.jupiter.api/org/junit/jupiter/api/BeforeEach.html[`@BeforeEach`^] annotation.

According to the working rules of the https://junit.org/junit5/[JUnit 5^] framework, if the test class contains a method annotated by the
{JUNIT5-DOC-ROOT-URL}api/org.junit.jupiter.api/org/junit/jupiter/api/BeforeEach.html[`@BeforeEach`^] annotation, then this method should be invoked before invoking each test method in the test class.

Let's consider the possibilities of using the {JUNIT5-DOC-ROOT-URL}api/org.junit.jupiter.api/org/junit/jupiter/api/BeforeEach.html[`@BeforeEach`^]
annotation. We'll use the example of a project consisting of two components: ChildComponent interface and ParentComponent class.

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-before-test/src/main/java/io/rxmicro/examples/testing/component/before/test/ChildComponent.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-before-test/src/main/java/io/rxmicro/examples/testing/component/before/test/ParentComponent.java[tag=content,indent=0]
----

When using the mock alternative, it is possible to program the behavior in the method annotated by the {JUNIT5-DOC-ROOT-URL}api/org.junit.jupiter.api/org/junit/jupiter/api/BeforeEach.html[`@BeforeEach`^] annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-before-test/src/test/java/io/rxmicro/examples/testing/component/before/test/ParentComponent1Test.java[tag=content,indent=0]
----
<1> Since the `beforeEach()` method will be surely invoked by the https://junit.org/junit5/[JUnit 5^]
framework before invoking the `Should_use_alternative()` test method, the programmed mock behavior will be used during the test;

The weak point in using the method annotated by the {JUNIT5-DOC-ROOT-URL}api/org.junit.jupiter.api/org/junit/jupiter/api/BeforeEach.html[`@BeforeEach`^]
annotation, is that it is impossible to program different behavior for two or more test methods in the same class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-before-test/src/test/java/io/rxmicro/examples/testing/component/before/test/ParentComponent2Test.java[tag=content,indent=0]
----

The standard solution to this problem consists in programming behavior in the test method:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-before-test/src/test/java/io/rxmicro/examples/testing/component/before/test/ParentComponent3Test.java[tag=content,indent=0]
----

However, the alternative configuration in the test method is not always convenient. +
*This can cause a problem, especially when it is necessary to configure the RxMicro component alternative before its registration in the runtime container!*

To solve this problem, the RxMicro framework provides two additional annotations:

* {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeThisTest.java[`@BeforeThisTest`^];
* {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeIterationMethodSource.java[`@BeforeIterationMethodSource`^];

The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeThisTest.java[`@BeforeThisTest`^]
annotation allows You to specify the method to be invoked before invoking a specific test method:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-before-test/src/test/java/io/rxmicro/examples/testing/component/before/test/ParentComponent4Test.java[tag=content,indent=0]
----
<1> To configure the mock alternative, it is necessary to create a method in the test class.
<2> If this method needs to be invoked before the test method, it is necessary to specify the name of this method using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeThisTest.java[`@BeforeThisTest`^] annotation. +
_(The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeThisTest.java[`@BeforeThisTest`^] annotation must annotate the test method!)_.

When creating parametrized tests, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeIterationMethodSource.java[`@BeforeIterationMethodSource`^]
annotation instead of the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeThisTest.java[`@BeforeThisTest`^] annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-before-test/src/test/java/io/rxmicro/examples/testing/component/before/test/ParentComponent5Test.java[tag=content,indent=0]
----
<1> Using the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeIterationMethodSource.java[`@BeforeIterationMethodSource`^]
annotation, the developer specifies an array of methods.
Each method in this array must be invoked before executing a new iteration of the parameterized test.
<2> For reporting it is recommended to specify the `final String method` parameter of the parameterized test.
This parameter is not used in the test, but if it is present, the https://junit.org/junit5/[JUnit 5^] framework automatically passes the method name to it.
Thus, in the execution report of the parameterized test, for each iteration the method that was invoked before execution of this iteration will be specified.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-before-test
include::../___notes/full-source-code-of-example.adoc[]

