:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[testing-component-tests-section]]
=== Testing of Microservice Components

==== Basic Principles

The basic principles of component testing are covered by the <<testing-alternatives-usage-section>> section.

==== Features of Testing Complex Components that Use Alternatives

The features of testing complex components that use alternatives are the same as for <<testing-rest-based-microservice-tests-complex-alternative-usage-section,REST-based microservice testing>>.

For more information, we recommend that You familiarize yourself with the following examples:

* Features of testing components that use REST clients:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-component-alternatives-rest-client[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-component-alternatives-rest-client`^];

* Features of testing components that use mongo repositories:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-component-alternatives-mongo-repository[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-component-alternatives-mongo-repository`^];

* Features of testing components that use postgres repositories:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-component-alternatives-postgres-repository[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-component-alternatives-postgres-repository`^];

<<<

include::_component-test/execution-test-order.adoc[]
