:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[testing-component-tests-section]]
=== Тестирование компонентов микросервиса

==== Базовые принципы

Базовые принципы тестирования компонентов рассмотрены в разделе: <<testing-alternatives-usage-section>>.

==== Особенности тестирования сложных компонентов, использующих альтернативы

Особенности тестирования сложных компонентов, использующих альтернативы такие же как и <<testing-rest-based-microservice-tests-complex-alternative-usage-section, при тестировании REST-based микросервисов>>.

For more information, we recommend that You familiarize yourself with the following examples:

* Особенности тестирования компонентов, использующих REST client:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-rest-client[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-rest-client`^];

* Особенности тестирования компонентов, использующих mongo репозитории:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-mongo-repository[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-mongo-repository`^];

* Особенности тестирования компонентов, использующих postgres репозитории:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-postgres-repository[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-postgres-repository`^];

<<<

include::_component-test/execution-test-order.adoc[]
