:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[testing-integration-tests-section]]
=== REST-based Microservice Integration Testing

The REST-based microservice integration testing allows You to test a complete system, which can consist of several REST-based microservices.

For easy writing of the REST-based microservices integration tests, the RxMicro framework provides:

. The additional {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroIntegrationTest.java[`@RxMicroIntegrationTest`^] annotation, that informs the RxMicro framework about the need to create an HTTP client and inject it into the tested class.
. A special *blocking* HTTP client to execute HTTP requests during testing:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^].
. The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/SystemOut.java[`SystemOut`^] interface for easy console access.

The main differences between integration testing and REST-based microservice testing:

. for integration tests, the RxMicro framework does not run an HTTP server;
. the developer has to start and stop the system consisting of REST-based microservices;
. the RxMicro framework does not support alternatives and additional configuration for integration tests;

<<<

include::_integration-test/basic.adoc[]

<<<

include::_integration-test/client-settings.adoc[]

<<<

include::_integration-test/docker-usage.adoc[]
