:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[testing-rest-based-microservice-tests-section]]
=== REST-based Microservice Testing

The REST-based microservice test is a standard Unit test that tests only the source code of a microservice.
If the current microservice depends on external services (e.g. database, other REST-based microservices, etc.), then it is allowed to use mocks for these external services during its testing.
If several REST-based microservices need to be tested, it is recommended to use the <<testing-integration-tests-section,REST-based microservice integration testing>>.

For easy writing of microservice tests, the RxMicro framework provides:

. The additional {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroRestBasedMicroServiceTest.java[`@RxMicroRestBasedMicroServiceTest`^] annotation, that informs the RxMicro framework about the need to start the tested REST-based microservice and prepare the environment to execute test HTTP requests.
. A special *blocking* HTTP client to execute HTTP requests during testing:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^].
. The {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/SystemOut.java[`SystemOut`^] interface for easy console access.

For each microservice test, the RxMicro framework performs the following actions:

. Before starting all the test methods in the class:
.. checks the test class for compliance with the rules of REST-based microservice testing defined by the RxMicro framework;
.. starts an HTTP server on a random free port;
.. creates an instance of the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] type;
.. connects the created {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] to the running HTTP server.
. Before starting each test method:
.. if necessary, invokes the methods defined using the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeTest.java[`@BeforeTest`^]
or {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeIterationMethodSource.java[`@BeforeIterationMethodSource`^] annotations;
.. if necessary, registers the RxMicro component alternatives in the RxMicro container;
.. registers the tested REST-based microservice on the running HTTP server;
.. if necessary, injects the custom component alternatives to the REST-based microservice;
.. injects a link to the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] instance into the test class;
.. if necessary, creates the `System.out` mock, and injects it into the test class.
. After performing each test method:
.. deletes all registered components from the RxMicro container;
.. deletes all registered REST-based microservices on the running HTTP server;
.. if necessary, restores the `System.out`.
. After performing all the tests in the class:
.. clears the resources of the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] component;
.. stops the HTTP server and releases the selected resources.

include::_micro-service-test/basic.adoc[]

include::_micro-service-test/alternatives.adoc[]

include::_micro-service-test/execution-test-order.adoc[]
