:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

[[testing-prepare-section]]
=== Preparatory Steps

Before writing tests, using the RxMicro framework, the following steps must be taken:

. Define the versions of used libraries.
. Add the required dependencies to the `pom.xml`.
. Configure the `maven-compiler-plugin`.
. Configure the `maven-surefire-plugin`.

[[testing-prepare-lib-versions-section]]
==== Definition the Versions of the Used Libraries:

[source,xml,subs="attributes+"]
----
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <rxmicro.version>{rxmicro-version}</rxmicro.version> <!--1-->

    <maven-compiler-plugin.version>{maven-compiler-plugin-version}</maven-compiler-plugin.version> <!--2-->
    <maven-surefire-plugin.version>{maven-surefire-plugin-version}</maven-surefire-plugin.version><!--3-->
</properties>
----
<1> {MAVEN-REPO-SEARCH-ROOT}io.rxmicro[The latest stable version of the RxMicro framework^].
<2> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-compiler-plugin[The latest stable version of the `maven-compiler-plugin`^].
<3> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-surefire-plugin[The latest stable version of the `maven-surefire-plugin`^].

[[testing-prepare-add-required-dependencies-section]]
==== Adding the Required Dependencies:

Before using the RxMicro modules for testing, You need to add the following dependencies to the project:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-test-junit</artifactId> <!--1-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-test-mockito-junit</artifactId> <!--2-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-http-client-jdk</artifactId> <!--3-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-rest-client-exchange-json</artifactId> <!--4-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
----
<1> `rxmicro-test-junit` - a unit testing library based on the https://junit.org/junit5/[JUnit 5^] framework.
<2> `rxmicro-test-mockito-junit` - a unit testing library based on the https://junit.org/junit5/[JUnit 5^] framework with integration of the https://site.mockito.org/[Mockito^] framework.
<3> `rxmicro-http-client-jdk` - an HTTP client library based on the https://developer.oracle.com/java/jdk-http-client.html[`java.net.http`^] JDK module.
<4> `rxmicro-rest-client-exchange-json` - a library for converting Java models to https://www.json.org/[JSON^] format and vice versa on the HTTP client side.

[TIP]
====
The `rxmicro-http-client-jdk` and `rxmicro-rest-client-exchange-json` libraries are required only during writing the
<<testing#testing-rest-based-microservice-tests-section, REST-based microservice tests>> and <<testing#testing-integration-tests-section, integration tests>>.
These dependencies can be omitted during writing the <<testing#testing-component-tests-section, component unit tests>>.

The `rxmicro-test-mockito-junit` library depends on the `rxmicro-test-junit`, so only one of them needs to be added:

. If only the https://junit.org/junit5/[JUnit 5^] framework is required, use the `rxmicro-test-junit` library.
. If You still need to create mocks, then use the `rxmicro-test-mockito-junit` library.
====

[[testing-prepare-maven-compiler-plugin-settings-section]]
==== Configuring the `maven-compiler-plugin`:

To solve <<testing-how-it-works-section,problems with the Java module system>> when writing the tests, it is necessary to add the additional execution to the `maven-compiler-plugin` configuration:

[source,xml]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version> <!--1-->
    <configuration>
        <release>11</release>
        <annotationProcessorPaths>
            <annotationProcessorPath>
                <groupId>io.rxmicro</groupId>
                <artifactId>rxmicro-annotation-processor</artifactId>
                <version>${rxmicro.version}</version>
            </annotationProcessorPath>
        </annotationProcessorPaths>
    </configuration>
    <executions>
        <execution>
            <id>source-compile</id>
            <goals>
                <goal>compile</goal>
            </goals>
            <configuration>
                <annotationProcessors>
                    <annotationProcessor>
                        io.rxmicro.annotation.processor.RxMicroAnnotationProcessor
                    </annotationProcessor>
                </annotationProcessors>
                <generatedSourcesDirectory>
                    ${project.build.directory}/generated-sources/
                </generatedSourcesDirectory>
            </configuration>
        </execution>
        <execution>
            <id>test-compile</id> <!--2-->
            <goals>
                <goal>testCompile</goal>
            </goals>
            <configuration>
                <annotationProcessors>
                    <annotationProcessor>
                        io.rxmicro.annotation.processor.RxMicroTestsAnnotationProcessor <!--3-->
                    </annotationProcessor>
                </annotationProcessors>
                <generatedTestSourcesDirectory>
                    ${project.build.directory}/generated-test-sources/ <!--4-->
                </generatedTestSourcesDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
----
<1> The plugin version defined in the <<testing-prepare-lib-versions-section,`properties`>> section.
<2> The separate configuration is required for the tests, so a new `execution` must be added.
<3> The annotation processor class that handles the test configuration.
<4> Location of Java classes generated by the `RxMicro Test Annotation Processor`.

[TIP]
====
The `io.rxmicro.annotation.processor.RxMicroTestsAnnotationProcessor` generates additional classes required *only during testing*.

*Therefore, You must always specify a separate folder for the generated classes!*
====

[[testing-prepare-maven-surefire-plugin-settings-section]]
==== Configuring the  `maven-surefire-plugin`:

include::../___shared/maven-surefire-plugin-configuration.adoc[]

include::../___notes/use-example-of-source-code-for-details.adoc[]
