:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../../

==== Компоненты с пользовательскими конструкторами

В случае если пользовательский компонент не содержит доступный конструктор без параметров:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-alternatives-withconstructor/src/main/java/io/rxmicro/examples/testing/component/alternatives/withconstructor/ParentComponent.java[tag=content,indent=0]
----
<1> Класс `ParentComponent` зависит от компонента `ChildComponent`. +
_(Данная зависимость указана явно в исходном коде.)_
<2> При создании объекта класса `ParentComponent` в конструкторе необходимо передать значение параметра `prefix`.

то the RxMicro framework не сможет создать объект данного класса.

*Поэтому разработчик должен создать объект данного класса самостоятельно в одном из методов
{JUNIT5-DOC-ROOT-URL}api/org.junit.jupiter.api/org/junit/jupiter/api/BeforeEach.html[`@BeforeEach`^],
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeTest.java[`@BeforeTest`^] или
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/BeforeIterationMethodSource.java[`@BeforeIterationMethodSource`^]*:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-component-alternatives-withconstructor/src/test/java/io/rxmicro/examples/testing/component/alternatives/withconstructor/ParentComponentTest.java[tag=content,indent=0]
----
<1> Объект класса `ParentComponent` создается внутри метода аннотированного аннотацией {JUNIT5-DOC-ROOT-URL}api/org.junit.jupiter.api/org/junit/jupiter/api/BeforeEach.html[`@BeforeEach`^].
<2> Альтернатива `childComponent` будет внедрена в объект класса `ParentComponent` после вызова метода `beforeEach()` и перед тестовым методом `Should_use_alternative()`.
<3> При тестировании метода `getEnvironment` вызывается метод из альтернативы вместо реального компонента.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-component-alternatives-simplest
include::../../___notes/full-source-code-of-example.adoc[]
