:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

==== Алгоритм внедрения альтернативы пользовательского компонента

Для внедрения альтернативы пользовательского компонента the RxMicro framework использует следующий алгоритм:

. Объект альтернативы создается разработчиком в коде теста или тестируемым фреймворком автоматически.
. The RxMicro framework создает объект тестируемого класса.
. В конструкторе или статической секции тестируемого класса создаются объекты реальных пользовательских компонентов.
. После завершения инициализации объект тестируемого класса содержит ссылки на реальные пользовательские компоненты.
. После создания объекта тестируемого класса the RxMicro framework внедряет альтернативы пользовательских компонентов, используя механизм `reflection`. +
_(Т.е. альтернативы заменяют реальные объекты уже после создания объекта тестируемого класса.)_;
. После внедрения альтернатив объект тестируемого класса содержит ссылки на альтернативы RxMicro компонентов вместо реальных RxMicro компонентов. +
_(Объекты реальных компонентов будут удалены сборщиком мусора позже.)_;

Таким образом главное отличие алгоритма внедрения альтернатив пользовательских компонентов заключается в том, что в процессе внедрения всегда создаются объекты реальных компонентов.

[IMPORTANT]
====
Если реальный компонент создает ссылку на внешний ресурс, то данный ресурс *не будет* освобожден автоматически при внедрении альтернативы!
====

Для создания альтернатив пользовательских компонентов, работающих с внешними ресурсами рекомендуется использовать модуль <<{cdi}#cdi-section,`rxmicro.cdi`>>.

[IMPORTANT]
====
Если для создания объектов пользовательских компонентов разработчик использует модуль <<{cdi}#cdi-section,`rxmicro.cdi`>>, то тогда *все* пользовательские компоненты подчиняются алгоритму внедрения альтернативы RxMicro компонента.
====
