:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

==== Basic Principles

To understand the REST-based microservice testing principles, let's create the simplest microservice that returns the `"Hello World!"` message.

Since the microservice will return a JSON object, it is necessary to create a response model:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-microservice-basic/src/main/java/io/rxmicro/examples/testing/microservice/basic/model/Response.java[tag=content,indent=0]
----

When there is the `GET` request to the microservice, it should return the `"Hello World!"` message:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-microservice-basic/src/main/java/io/rxmicro/examples/testing/microservice/basic/MicroService.java[tag=content,indent=0]
----

The testing process of the REST-based microservice is to perform an HTTP request after the RxMicro framework starts the tested microservice on the HTTP server.
After receiving a response from the microservice, this response is compared to the expected response:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-microservice-basic/src/test/java/io/rxmicro/examples/testing/microservice/basic/MicroServiceTest.java[tag=content,indent=0]
----
<1> To start the HTTP server and register the tested REST-based microservice, it is necessary to annotate the test class by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroRestBasedMicroServiceTest.java[`@RxMicroRestBasedMicroServiceTest`^] annotation.
In the parameter of this annotation it is specified which REST-based microservice class will be tested in the current test.
<2> To execute *blocking* HTTP requests, the RxMicro framework supports the special
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] component.
The developer must declare a reference to this component, and while starting the test, the RxMicro framework will automatically inject the created
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] class instance, using the `reflection` mechanism.
<3> Upon receiving the HTTP response from the microservice, the developer should compare the response body with the expected result in the test.

include::../_note_json_compare.adoc[]

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-testing-junit/testing-microservice-basic
include::../../___notes/full-source-code-of-example.adoc[]

include::../../___notes/recompile-after-change.adoc[]
