:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

==== Базовые принципы

Для понимания принципов тестирования REST-based микросервиса, создадим простейший микросерис, который возвращает сообщение `"Hello World!"`.

Так как микросервис будет возвращать JSON объект, то необходимо создать модель ответа:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-microservice-basic/src/main/java/io/rxmicro/examples/testing/microservice/basic/model/Response.java[tag=content,indent=0]
----

При `GET` запросе на микросервис, он должен вернуть сообщение `"Hello World!"`:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-microservice-basic/src/main/java/io/rxmicro/examples/testing/microservice/basic/MicroService.java[tag=content,indent=0]
----

Процесс тестирования REST-based микросервиса заключается в том, чтобы после того как the RxMicro framework запустит тестируемый микросервис на HTTP сервере выполнить HTTP запрос.
После получения ответа от микросервиса, данный ответ сравнивается с ожидаемым ответом:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-microservice-basic/src/test/java/io/rxmicro/examples/testing/microservice/basic/MicroServiceTest.java[tag=content,indent=0]
----
<1> Для запуска HTTP сервера и регистрации тестируемого REST-based микросервиса, необходимо тестовый класс аннотировать аннотацией
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroRestBasedMicroServiceTest.java[`@RxMicroRestBasedMicroServiceTest`^].
В параметре данной аннотации указывается какой именно класс REST-based микросервиса будет тестироваться в текущем тесте.
<2> Для выполнения *блокирующих* HTTP запросов, the RxMicro framework поддерживает специальный компонент:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^].
Разработчик должен объявить ссылку на данный компонент и в процессе запуска теста, the RxMicro framework автоматически внедрит созданный объект класса
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^], используя механизм `reflection`.
<3> Получив от микросервиса HTTP ответ, в тесте разработчик должен сравнить тело ответа с ожидаемым результатом.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}testing-microservice-basic
include::../../___notes/full-source-code-of-example.adoc[]

include::../../___notes/recompile-after-change.adoc[]
