:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

==== Custom and the RxMicro Framework Code Execution Order

For efficient writing of Rest-based microservice tests, it is necessary to know the execution order of user, and the RxMicro framework code.

When testing a Rest-based microservice, using the following test:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-testing-junit/testing-microservice-order/src/test/java/io/rxmicro/examples/testing/microservice/order/MicroServiceTest.java[tag=content,indent=0]
----

the execution order will be as follows:

[source,text,subs="verbatim,quotes"]
----
*RX-MICRO:* Test class validated.
*RX-MICRO:* HTTP server started without any REST-based microservices using random free port.
*RX-MICRO:* Blocking HTTP client created and connected to the started HTTP server.
*USER-TEST:* '@org.junit.jupiter.api.BeforeAll' invoked.

*USER-TEST:* new instance of the REST-based microservice test class created.
*MOCKITO:* All mocks created and injected.
*RX-MICRO:* Alternatives of the RxMicro components registered in the RxMicro runtime containers.
*RX-MICRO:* Blocking HTTP client injected to the instance of the test class.
*RX-MICRO:* SystemOut instance created and injected to the instance of the test class.
*USER-TEST:* '@org.junit.jupiter.api.BeforeEach' invoked.
*USER-TEST:* 'beforeTest1UserMethod' invoked.
*RX-MICRO:* Current REST-based microservice instance created and registered in the HTTP server.
*RX-MICRO:* Alternatives of the user components injected to the REST-based microservice instance.
*USER-TEST:* 'test1()' invoked.
*USER-TEST:* '@org.junit.jupiter.api.AfterEach' invoked.
*RX-MICRO:* All registered alternatives removed from the RxMicro runtime containers.
*RX-MICRO:* Current REST-based microservice instance unregistered from the HTTP server.
*RX-MICRO:* System.out reset.
*MOCKITO:* All mocks destroyed.

*USER-TEST:* new instance of the REST-based microservice test class created.
*MOCKITO:* All mocks created and injected.
*RX-MICRO:* Alternatives of the RxMicro components registered in the RxMicro runtime containers.
*RX-MICRO:* Blocking HTTP client injected to the instance of the test class.
*RX-MICRO:* SystemOut instance created and injected to the instance of the test class.
*USER-TEST:* '@org.junit.jupiter.api.BeforeEach' invoked.
*USER-TEST:* 'beforeTest2UserMethod' invoked.
*RX-MICRO:* Current REST-based microservice instance created and registered in the HTTP server.
*RX-MICRO:* Alternatives of the user components injected to the REST-based microservice instance.
*USER-TEST:* 'test2()' invoked.
*USER-TEST:* '@org.junit.jupiter.api.AfterEach' invoked.
*RX-MICRO:* All registered alternatives removed from the RxMicro runtime containers.
*RX-MICRO:* Current REST-based microservice instance unregistered from the HTTP server.
*RX-MICRO:* System.out reset.
*MOCKITO:* All mocks destroyed.

*USER-TEST:* '@org.junit.jupiter.api.AfterAll' invoked.
*RX-MICRO:* Blocking HTTP client released.
*RX-MICRO:* HTTP server stopped.
----

In the above execution order of user, and the RxMicro framework code the following clarifications are implied:

. The `MOCKITO` prefix means that the action is activated by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java[`@InitMocks`^] annotation.
. The `RX-MICRO` prefix means that the action is activated by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroRestBasedMicroServiceTest.java[`@RxMicroRestBasedMicroServiceTest`^] annotation.
. The `USER-TEST` prefix means that at this stage a custom method from the `MicroServiceTest` class is invoked.
