:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[project-documentation-basic-usage-section]]
=== Basic Usage

Default settings allow You to generate REST-based microservice documentation using minimal configurations. +
_(This advantage is achieved through close integration with other RxMicro modules.)_

==== Min Settings

To generate REST-based microservice documentation during the compilation of the microservice project, the following two steps must be done:

* Add the `rxmicro-documentation-asciidoctor` dependency to `pom.xml` of the microservice project:

[source,xml]
----
<dependency>
    <groupId>io.rxmicro</groupId>
    <artifactId>rxmicro-documentation-asciidoctor</artifactId>
    <version>${rxmicro.version}</version>
</dependency>
----

* Add the `rxmicro.documentation.asciidoctor` module to the `module-info.java` descriptor of the microservice project:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-documentation-asciidoctor/documentation-asciidoctor-quick-start/src/main/java/module-info.java[tags=content]
----

<1> The `rxmicro.documentation.asciidoctor` must be added using the `static` modifier. +
_(For more information on the benefits of the `static` modifier, refer to the <<project-documentation-basic-usage-maven-dependency-plugin>>.)_

After performing these steps during compiling the microservice project, the `RxMicro Annotation Processor` will generate the `ExamplesDocumentationAsciidoctorQuickStartDocumentation.adoc` file.
The generated file will contain REST-based microservice documentation in the http://asciidoc.org/[`AsciiDoc`^] format, and by default will be located in the `./src/main/asciidoc` folder.

[NOTE]
====
In terms of the version control system, the `./src/main/asciidoc` folder is the source code, so it will be controlled by this system.
Therefore, if REST-based microservice documentation is to be dynamically generated, it is necessary to:

* specify that files in the `./src/main/asciidoc` folder must be ignored by the version control system;
* or configure the `rxmicro.documentation.asciidoctor` module, so that it generates REST-based microservice documentation in another folder, for example in the `target/docs`. +
_(To configure the folder in which REST-based microservice documentation should be generated, refer to the <<core#rxmicro-annotation-processor-options-section>>.)_

Using the `./src/main/asciidoc` folder by default provides the following benefits:

* The `asciidoctor-maven-plugin`, which converts the http://asciidoc.org/[`AsciiDoc`^] format to https://html.spec.whatwg.org/[`HTML`^] or https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf[`PDF`^]
, by default reads files from the `./src/main/asciidoc` folder.
* Automatic building of REST-based microservice documentation can be used as an initial version of the document.
After formation of the initial version, the generation can be disabled and all changes to the documentation will be made manually by the developer and stored in the version control system.
* Compared to the previous version, a more efficient way to keep REST-based microservice documentation up to date is to divide all documentation into fragments.
Static fragments (business task description, charts and figures) will be created manually by the developer.
Dynamic fragments will be generated by the `RxMicro Annotation Processor` at each project compilation.
As a result, a final document containing static and dynamic fragments will be compiled from these fragments. +
_(When using this approach, do not forget to add the all dynamic fragments to ignore list for Your version control system!)_
====

==== `Asciidoctor-maven-plugin` Settings

The `asciidoctor-maven-plugin` plugin allows You to convert documentation from the http://asciidoc.org/[`AsciiDoc`^] format to
https://html.spec.whatwg.org/[`HTML`^], https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf[`PDF`^] and other formats.

[source,xml]
----
<plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId> <!--1-->
    <version>${asciidoctor-maven-plugin.version}</version>
    <executions>
        <execution>
            <id>output-html5</id>
            <phase>package</phase> <!--2-->
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>html5</backend> <!--3-->
                <sourceHighlighter>highlight.js</sourceHighlighter> <!--4-->
                <preserveDirectories>true</preserveDirectories>
                <relativeBaseDir>true</relativeBaseDir>
                <attributes> <!--5-->
                    <icons>font</icons>
                    <pagenums/>
                    <toclevels>3</toclevels>
                </attributes>
            </configuration>
        </execution>
    </executions>
</plugin>
----
<1> {MAVEN-REPO-SEARCH-ROOT}org.asciidoctor/asciidoctor-maven-plugin[The latest stable version of the `asciidoctor-maven-plugin`^].
<2> The `asciidoctor-maven-plugin` must convert REST-based microservice documentation at the `package` phase.
<3> Using the `backend` directive, You can specify in which format the http://asciidoc.org/[`AsciiDoc`^] document should be converted.
<4> If the http://asciidoc.org/[`AsciiDoc`^] document contains examples of source code in a programming language, You need to add the js library for highlighting the syntax of that language.
<5> Using the `attributes` directive, it is possible to override the attributes of the   http://asciidoc.org/[`AsciiDoc`^] document.

[NOTE]
====
For more information about the `asciidoctor-maven-plugin` plugin features, refer to the documentation:

[.example-code-link]
https://asciidoctor.org/docs/asciidoctor-maven-plugin/[`https://asciidoctor.org/docs/asciidoctor-maven-plugin/`^]
====

[[project-documentation-basic-usage-maven-dependency-plugin]]
==== `Asciidoctor-dependency-plugin` Settings

REST-based microservice documentation is generated during the compilation process, therefore the libraries used to configure the REST-based microservice documentation generation process are not required in `runtime`.
Therefore, the `maven-dependency-plugin` should not copy artifacts related to the generation of REST-based microservice documentation to the `lib` folder:

[source,xml]
----
<plugin>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>${maven-dependency-plugin.version}</version>
    <executions>
        <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
                <goal>copy-dependencies</goal>
            </goals>
            <configuration>
                <outputDirectory>${project.build.directory}/lib</outputDirectory>
                <includeScope>compile</includeScope>
                <excludeArtifactIds> <!--1-->
                    rxmicro-documentation,
                    rxmicro-documentation-asciidoctor
                </excludeArtifactIds>
            </configuration>
        </execution>
    </executions>
</plugin>
----

<1> The `rxmicro-documentation` and `rxmicro-documentation-asciidoctor` artifacts are required *only* during the compilation process.

[IMPORTANT]
====
In order that in `runtime` no errors occur when excluding the artifacts required for REST-based microservice documentation generation, it is required to use the `static` modifier in the `module-info.java` descriptor: `requires static rxmicro.documentation.asciidoctor;`.

Without this modifier the following error will occur when starting the microservice: `Module rxmicro.documentation.asciidoctor not found`!
====

:project-documentation-file: ExamplesDocumentationAsciidoctorQuickStartDocumentation.html
include::../___notes/generated-project-documentation.adoc[]

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}documentation-asciidoctor-quick-start
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
