:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[rest-client-params-basic]]
=== Обработка HTTP параметров

include::../_rest/___http_params_basic_rules.adoc[]

После создания классов моделей, необходимо создать обработчик HTTP запросов, использующий данные модели:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/SimpleUsageRestClient.java[tag=content,indent=0]
----
<1> Если для HTTP запроса был создан отдельный класс модели, то этот класс необходимо передавать параметром метода, обрабатывающего HTTP запрос.
<2> Кроме поддержки классов модели HTTP запроса, RxMicro поддерживает обработчики запросов, принимающие HTTP параметры запросов в качестве параметров метода.
<3> Для определения общей стратегии именования всех HTTP параметров, которые передаются в качестве параметров метода обработчик запросов должен быть аннотирован аннотацией `@ParameterMappingStrategy`.
<4> Для того чтобы параметр метода объявить как поле HTTP параметра, не нужно использовать каких-либо дополнительных аннотаций.
<5> С помощью аннотации `@Parameter` возможно задать имя HTTP параметра, которое не соответствует используемой стратегии, объявленной с помощью аннотации `@ParameterMappingStrategy`.

[IMPORTANT]
====
*Обратите внимание, что RxMicro не различает каким способом будут переданы параметры HTTP запроса на обработчик: с помощью стартовой строки или HTTP тела!*
====

include::../___notes/model-class-intead-of-method-parameters-note.adoc[tags=**;!path-variables;!headers;!all]

Несмотря на различные подходы к поддержке обработки HTTP заголовков, с точки зрения генерируемого сообщения по протоколу HTTP два вышеуказанных обработчика абсолютно равнозначны:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/SimpleUsageRestClientTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Поддерживаемые типы данных

include::../_rest/___param_types.adoc[]

<<<

==== Поддержка сложных моделей

В отличие от HTTP заголовков HTTP параметры могут передаваться в теле запроса.

Поэтому кроме примитивов RxMicro поддерживает также и вложенные JSON объекты и массивы.

[TIP]
====
Именно поэтому в списке поддерживаемых типов указаны следующие типы:

* `? extends Object` - пользовательский класс вложенной Java модели;
* `java.util.List<? extends Object>` - список пользовательских классов вложенной Java модели;
====

Пример вложенной модели:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/model/nested/NestedModel.java[tag=content,indent=0]
----

А также примеры более сложных Java моделей, использующих вложенную модель:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/model/ComplexRequest.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/model/ComplexResponse.java[tag=content,indent=0]
----

<1> Поле примитивного JSON типа.
<2> JSON массив примитивного типа.
<3> Вложенный JSON объект.
<4> JSON массив вложенных JSON объектов.

После создания классов моделей, необходимо создать REST клиент, методы которого используют данные модели:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/ComplexModelRestClient.java[tag=content,indent=0]
----

Так как запрос теперь передается в HTTP теле, то отправляемый и получаемый JSON объекты должны быть равны:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/ComplexModelRestClientTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

[[rest-client-query-params-static]]
==== Статические Query параметры

TODO

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/StaticQueryParametersRestClient.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/StaticQueryParametersRestClientTest.java[tag=content,indent=0]
----

[NOTE]
====
Для понимания отличий аннотаций {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/AddQueryParameter.java[`@AddQueryParameter`^] и
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/SetQueryParameter.java[`@SetQueryParameter`^] рекомендуем обратится к примеру:

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/ComplexStaticQueryParametersRestClient.java[`ComplexStaticQueryParametersRestClient.java`^]

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/ComplexStaticQueryParametersRestClientTest.java[`ComplexStaticQueryParametersRestClientTest.java`^]
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

[[rest-client-query-params-repeating]]
==== Повторяющиеся Query параметры

TODO

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/RepeatingQueryParamsRestClient.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/RepeatingQueryParamsRestClientTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
