:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

[[rest-client-partial-implementation-section]]
=== Partial Implementation

Если генерируемый by `RxMicro Annotation Processor` REST client содержит ошибки, некорректную или неоптимизированную логику, то разработчик может использовать the `Partial Implementation` feature.

Данная feature позволяет реализовывать обработчики HTTP запроса для REST клиента самостоятельно, вместо того, чтобы они были сгененированы by the RxMicro framework.

Для активации данной feature необходимо с помощью аннотации
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/PartialImplementation.java[`@PartialImplementation`^]
указать абстрактный класс, который содержит реализацию обработчики HTTP запроса для REST клиента:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-partial-implementation/src/main/java/io/rxmicro/examples/rest/client/partial/implementation/RESTClient.java[tag=content,indent=0]
----
<1> C помощью аннотации
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/PartialImplementation.java[`@PartialImplementation`^]
указывается абстрактный класс `AbstractRESTClient`.

Абстрактный класс `AbstractRESTClient` содержит следующий контент:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-partial-implementation/src/main/java/io/rxmicro/examples/rest/client/partial/implementation/AbstractRESTClient.java[tag=content,indent=0]
----

и должен удовлетворять следующим требованиям:

. Класс должен быть абстрактным.
. Класс должен наследоваться от класса
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/detail/AbstractRestClient.java[`AbstractRestClient`^].
. Класс должен реализовывать интерфейс REST клиента.
. Класс должен содержать реализацию всех методов, которые не генерируются автоматически.

С точки зрения инфраструктуры генерируемые и определенные разработчиком обработчики HTTP запросов для REST клиента ничем не отличаются:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-partial-implementation/src/test/java/io/rxmicro/examples/rest/client/partial/implementation/RESTClientTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-partial-implementation
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
