:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

=== Возвращаемые типы обработчиков HTTP запроса

include::../_rest/___http-handler-return-types.adoc[]

<<<

==== Поддерживаемые типы возвращаемого результата для HTTP ответа без тела

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-handlers/src/main/java/io/rxmicro/examples/rest/client/handlers/RestClientWithoutBody.java[tag=content,indent=0]
----
<1> Тип {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<Void>`^]
рекомендуется при использовании библиотеки {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^].
<2> Вместо {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<Void>`^] может быть использован также тип
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage<Void>`^].
<3> При использовании библиотеки {REACTOR-CORE-DOC-USER_GUIDE}[*Project Reactor*^] только тип
{REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono<Void>`^] может быть использован.
<4> При использовании библиотеки {RX-JAVA-USER-GUIDE}[*RxJava*^] только тип
{RX-JAVA-DOC-ROOT-URL}io/reactivex/Completable.html[`Completable`^] может быть использован.

Все указанные выше обработчики HTTP запроса не должны выбрасывать каких-либо исключений:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-handlers/src/test/java/io/rxmicro/examples/rest/client/handlers/RestClientWithoutBodyTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-handlers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Поддерживаемые типы возвращаемого результата для HTTP ответа с телом

RxMicro поддерживает следующие типы возвращаемого результата для HTTP ответа с телом:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-handlers/src/main/java/io/rxmicro/examples/rest/client/handlers/RestClientWithBody.java[tag=content,indent=0]
----
<1> Тип {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<MODEL>`^]
рекомендуется при использовании библиотеки {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^].
<2> Вместо {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<MODEL>`^] может быть использован также тип
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage<MODEL>`^].
<3> При использовании библиотеки {REACTOR-CORE-DOC-USER_GUIDE}[*Project Reactor*^] только тип
{REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono<MODEL>`^] может быть использован.
<4> При использовании библиотеки {RX-JAVA-USER-GUIDE}[*RxJava*^] только тип
{RX-JAVA-DOC-ROOT-URL}io/reactivex/Single.html[`Single<MODEL>`^] может быть использован.

include::../_rest/___note-reactive-parametrized-types.adoc[]

Все указанные выше обработчики возвращают объект класса `Response` с сообщением `Hello World!`:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-handlers/src/test/java/io/rxmicro/examples/rest/client/handlers/RestClientWithBodyTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-handlers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
