:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-client-expressions-section]]
=== Expressions

RxMicro поддерживает выражения для REST клиентов.

Выражения могут быть полезны для передачи конфигурационных параметров на сервер.

Для использования выражений необходимо создать конфигурационный класс:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-expressions/src/main/java/io/rxmicro/examples/rest/client/expressions/CustomHttpClientConfig.java[tag=content,indent=0]
----

, который должен удовлетворять следующим требованиям:

. Класс должен быть публичным.
. Класс должен содержать публичный конструктор без параметров.
. Класс должен наследовать класс
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http-client/src/main/java/io/rxmicro/http/client/HttpClientConfig.java[`HttpClientConfig`^].
. Для установки значений свойств класс должен содержать https://www.w3schools.com/java/java_encapsulation.asp[`setters`^]. +
_(Только те поля, которые будут содержать `setters` могут быть проинициализированы!)_

Для того, чтобы подключить данный конфигурационный класс к REST клиенту, необходимо указать его в параметре аннотации
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/RestClient.java[`@RestClient`^]:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-expressions/src/main/java/io/rxmicro/examples/rest/client/expressions/RESTClient.java[tag=content,indent=0]
----
<1> Подключение конфигурационного класса к REST клиенту.
<2> Указание `name space` для данного конфигурациооного файла. +
_(Для получения дополнительных сведений, касательно `name space` рекомендуем обратиться к разделу <<core#configuration>>)_
<3> После подключения конфигурационного класса, его `properties` могут быть использованы в выражениях.

Функциональность выражений может быть продемонстрирована с помощью теста:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-expressions/src/test/java/io/rxmicro/examples/rest/client/expressions/RESTClientTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-expressions
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
