:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-client-expressions-section]]
=== Expressions

The RxMicro framework supports expressions for REST clients.

Expressions can be useful to send configuration parameters to the server.

To use expressions You need to create a configuration class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-expressions/src/main/java/io/rxmicro/examples/rest/client/expressions/CustomHttpClientConfig.java[tag=content,indent=0]
----

, which must meet the following requirements:

. The class must be public.
. The class must contain a public constructor without parameters.
. The class must extend the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-http-client/src/main/java/io/rxmicro/http/client/HttpClientConfig.java[`HttpClientConfig`^] class.
. To set property values, the class must contain https://www.w3schools.com/java/java_encapsulation.asp[`setters`^]. +
_(Only those fields, that will contain `setters`, can be initialized!)_

To attach this configuration class to a REST client, You must specify it in the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/RestClient.java[`@RestClient`^] annotation parameter:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-expressions/src/main/java/io/rxmicro/examples/rest/client/expressions/RESTClient.java[tag=content,indent=0]
----
<1> Attaching the configuration class to a REST client.
<2> The `name space` specification for this configuration file. +
_(For more information on `name space`, refer to the <<core#configuration-section>> section)_
<3> After attaching the configuration class, its `properties` can be used in expressions.

The functionality of expressions can be demonstrated through the test:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-expressions/src/test/java/io/rxmicro/examples/rest/client/expressions/RESTClientTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-expressions
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
