:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-client-headers-basic]]
=== HTTP Headers Handling

include::../_rest/___http-headers-basic-rules.adoc[]

After creating model classes, it is necessary to create a request handler that uses the following models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-headers/src/main/java/io/rxmicro/examples/rest/client/headers/SimpleUsageRestClient.java[tag=content,indent=0]
----
<1> If a separate model class has been created for an HTTP request, then this class must be passed by the method parameter that handles the HTTP request.
<2> Besides supporting HTTP request model classes, the RxMicro framework supports request handlers that accept HTTP headers as method parameters.
<3> To define a common naming strategy for all HTTP headers which are passed as method parameters, the request handler must be annotated by the `@HeaderMappingStrategy` annotation.
<4> To declare a method parameter as an HTTP header field, use the `@Header` annotation.
<5> Using the `@Header` annotation, it is possible to specify an HTTP header name that does not correspond to the strategy used, declared by the `@HeaderMappingStrategy` annotation.

include::../___notes/model-class-intead-of-method-parameters-note.adoc[tags=**;!path-variables;!params;!all]

Despite the different approaches to HTTP header handling support, as to the message generated by the HTTP protocol, the two above-mentioned handlers are absolutely equal:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-headers/src/test/java/io/rxmicro/examples/rest/client/headers/SimpleUsageRestClientTest.java[tag=content,indent=0]
----
<1> When performing a request to different URL Paths, the result is the same.
<2> The `Endpoint-Version` name corresponds to the `endpointVersion` field of the request model. +
_(This correspondence is formed basing on the default strategy use, which is defined by the `@HeaderMappingStrategy` annotation.)_
<3> The `UseProxy` name corresponds to the `useProxy` field of the request model, since this name is specified in the `@Header` annotation.
<4> After executing the request in the resulting HTTP response, the `Endpoint-Version` and `UseProxy` headers are equal to `v1` and `true` respectively.
_(The handler returns the same header values it received from an HTTP request.)_

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-headers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Supported Data Types

include::../_rest/___header-types.adoc[]

<<<

[[rest-client-headers-static]]
==== Static HTTP Headers

For static header installation, the RxMicro framework provides the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/AddHeader.java[`@AddHeader`^] and
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/SetHeader.java[`@SetHeader`^] annotations:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-headers/src/main/java/io/rxmicro/examples/rest/client/headers/StaticHeadersRestClient.java[tag=content,indent=0]
----
<1> If the HTTP header is set for the REST client, it is added to the HTTP requests for each handler.
<2> If the HTTP header is set for the handler, it is added to the HTTP requests only for that handler.

In terms of the HTTP protocol, static headers do not differ from any others:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-headers/src/test/java/io/rxmicro/examples/rest/client/headers/StaticHeadersRestClientTest.java[tag=content,indent=0]
----

[NOTE]
====
In order to understand the differences between the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/AddHeader.java[`@AddHeader`^] and
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/SetHeader.java[`@SetHeader`^] annotations, check out the following example:

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-client-headers/src/main/java/io/rxmicro/examples/rest/client/headers/ComplexStaticHeadersRestClient.java[`ComplexStaticHeadersRestClient.java`^]

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-client-headers/src/test/java/io/rxmicro/examples/rest/client/headers/ComplexStaticHeadersRestClientTest.java[`ComplexStaticHeadersRestClientTest.java`^]
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-headers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

[[rest-client-headers-repeating]]
==== Repeating HTTP Headers

If the HTTP header of an HTTP request is a list of values, the list elements are transferred by default via the HTTP protocol as a string separated by the `|` symbol.

If You want the HTTP header to be repeated for each value, You need to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RepeatHeader.java[`@RepeatHeader`^] annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-headers/src/main/java/io/rxmicro/examples/rest/client/headers/RepeatingHeadersRestClient.java[tag=content,indent=0]
----

[NOTE]
====
*The use of the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RepeatHeader.java[`@RepeatHeader`^] annotation is supported for request models only!*

For response models it makes no sense, because the RxMicro framework converts any of the supported formats into a list of values.
====

As a result of converting the Java model to HTTP response, the result will be as follows:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-headers/src/test/java/io/rxmicro/examples/rest/client/headers/RepeatingHeadersRestClientTest.java[tag=content,indent=0]
----
<1> By default, HTTP header list elements are transferred via the HTTP protocol as a string separated by the `|` symbol.
<2> If the field is annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RepeatHeader.java[`@RepeatHeader`^] annotation, then the header is repeated for each element of the list.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-headers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
