:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-client-params-basic]]
=== HTTP Parameters Handling

include::../_rest/___http-params-basic-rules.adoc[]

After creating model classes, it is necessary to create an HTTP request handler that uses the following models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/SimpleUsageRestClient.java[tag=content,indent=0]
----
<1> If a separate model class has been created for an HTTP request, then this class must be passed by the method parameter that handles the HTTP request.
<2> Besides supporting HTTP request model classes, the RxMicro framework supports request handlers that accept HTTP request parameters as method parameters.
<3> To define a common naming strategy for all HTTP parameters which are passed as method parameters, the request handler must be annotated by the `@ParameterMappingStrategy` annotation.
<4> To declare a method parameter as an HTTP parameter field, You do not need to use any additional annotations.
<5> Using the `@Parameter` annotation, it is possible to specify an HTTP parameter name that does not correspond to the strategy used, declared by the `@ParameterMappingStrategy` annotation.

[IMPORTANT]
====
*Note that the RxMicro framework does not distinguish whether HTTP request parameters will be transferred to the handler using the start line or HTTP body!*
====

include::../___notes/model-class-intead-of-method-parameters-note.adoc[tags=**;!path-variables;!headers;!all]

Despite the different approaches to HTTP parameter handling support, as to the message generated by the HTTP protocol, the two above-mentioned handlers are absolutely equal:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/SimpleUsageRestClientTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-client/rest-client-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Supported Data Types

include::../_rest/___param-types.adoc[]

<<<

==== Complex Model Support

Unlike HTTP headers, HTTP parameters can be transferred in the request body.

Therefore, besides primitives the RxMicro framework also supports nested JSON objects and arrays.

[TIP]
====
Therefore, the list of supported types includes the following types:

* `? extends Object` - custom class of the nested Java model;
* `java.util.List<? extends Object>` - list of the nested Java model custom classes;
====

Nested Model Example:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/model/nested/NestedModel.java[tag=content,indent=0]
----

As well as examples of more complex Java models that use a nested model:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/model/ComplexRequest.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/model/ComplexResponse.java[tag=content,indent=0]
----

<1> Primitive JSON type field.
<2> Primitive JSON array type.
<3> Nested JSON object.
<4> JSON array of JSON nested objects.

After creating model classes, it is necessary to create a request handler that uses the following models:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/ComplexModelRestClient.java[tag=content,indent=0]
----

Since the request is transferred in an HTTP body, the sent and received JSON objects must be the same:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/ComplexModelRestClientTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-client/rest-client-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

[[rest-client-query-params-static]]
==== Static Query Parameters

For setting static query parameters, the RxMicro framework provides the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/AddQueryParameter.java[`@AddQueryParameter`^] and
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/SetQueryParameter.java[`@SetQueryParameter`^] annotations:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/StaticQueryParametersRestClient.java[tag=content,indent=0]
----
<1> If the static query parameter is set for the REST client, it is added to the HTTP requests for each handler.
<2> If the static query parameter is set for the handler, it is added to the HTTP requests only for that handler.

In terms of the HTTP protocol, static query parameters do not differ from any standard parameter:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/StaticQueryParametersRestClientTest.java[tag=content,indent=0]
----

[NOTE]
====
In order to understand the differences between the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/AddQueryParameter.java[`@AddQueryParameter`^] and
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/SetQueryParameter.java[`@SetQueryParameter`^] annotations, check out the following example:

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/ComplexStaticQueryParametersRestClient.java[`ComplexStaticQueryParametersRestClient.java`^]

* {RX-MICRO-EXAMPLES-SRC-ROOT-BLOB-URL}rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/ComplexStaticQueryParametersRestClientTest.java[`ComplexStaticQueryParametersRestClientTest.java`^]
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-client/rest-client-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

[[rest-client-query-params-repeating]]
==== Repeating Query Parameters

If the static query parameter of an HTTP request is a list of values, the list elements are transferred by default via the HTTP protocol as a string separated by the `|` symbol.

If You want the static query parameter to be repeated for each value, You need to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RepeatQueryParameter.java[`@RepeatQueryParameter`^] annotation:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/main/java/io/rxmicro/examples/rest/client/params/RepeatingQueryParamsRestClient.java[tag=content,indent=0]
----

As a result of converting the Java model to HTTP response, the result will be as follows:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-params/src/test/java/io/rxmicro/examples/rest/client/params/RepeatingQueryParamsRestClientTest.java[tag=content,indent=0]
----
<1> By default, static query parameter list elements are transferred via the HTTP protocol as a string separated by the `|` symbol.
<2> If the field is annotated by the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/RepeatQueryParameter.java[`@RepeatQueryParameter`^] annotation, then the static query parameter is repeated for each element of the list.

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-client/rest-client-params
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
