:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-client-partial-implementation-section]]
=== Partial Implementation

If the REST client generated by the `RxMicro Annotation Processor` contains errors, incorrect or non-optimized logic, the developer can use the `Partial Implementation` feature.

This feature allows You to implement HTTP request handlers for the REST client on Your own, instead of generating them by the RxMicro framework.

To activate this feature, You need to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/PartialImplementation.java[`@PartialImplementation`^]
annotation, and specify an abstract class that contains a partial implementation of HTTP request handler(s) for REST client:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-partial-implementation/src/main/java/io/rxmicro/examples/rest/client/partial/implementation/RESTClient.java[tag=content,indent=0]
----
<1> Using the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/PartialImplementation.java[`@PartialImplementation`^]
annotation, the `AbstractRESTClient` class is specified.

An `AbstractRESTClient` contains the following content:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-partial-implementation/src/main/java/io/rxmicro/examples/rest/client/partial/implementation/AbstractRESTClient.java[tag=content,indent=0]
----

An abstract class that contains a partial implementation must meet the following requirements:

. The class must be an `abstract` one.
. The class must extend the {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/detail/AbstractRestClient.java[`AbstractRestClient`^] one.
. The class must implement the REST client interface.
. The class must contain an implementation of all methods that are not generated automatically.

In terms of infrastructure, the HTTP request handlers generated and defined by the developer for REST client do not differ:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-partial-implementation/src/test/java/io/rxmicro/examples/rest/client/partial/implementation/RESTClientTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-client/rest-client-partial-implementation
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
