:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-client-path-variables-basic]]
=== The `path variables` Support

include::../_rest/___path-var-basic-rules.adoc[]

After creating model classes, it is necessary to create an HTTP request handler that uses the following model:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-path-variables/src/main/java/io/rxmicro/examples/rest/client/path/variables/RESTClient.java[tag=content,indent=0]
----
<1> When using `path variables` in request models, be sure to use *all* `path variables` in the URL Path.
_(Based on the analysis of the URL Path, and considering all `path variables`, the RxMicro framework generates the final URL to which the HTTP request will be sent.)_
<2> In order to declare a method parameter as `path variable`, You must use the `@PathVariable` annotation.
<3> Using the `@PathVariable` annotation it is possible to specify the `path variable` name, which does not match the name of the method parameter.

include::../___notes/model-class-intead-of-method-parameters-note.adoc[tags=**;!headers;!params;!all]

Despite the different approaches to `path variables` handling support, in terms of the final URL the two above-mentioned handlers are absolutely equal:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-path-variables/src/test/java/io/rxmicro/examples/rest/client/path/variables/RESTClientTest.java[tag=content,indent=0]
----
<1> As a result of the HTTP request handler execution, the RxMicro framework generates the same URL: `/CATEGORY/TYPE-SUB-TYPE`

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-path-variables
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

==== Supported Data Types

include::../_rest/___path-variables-types.adoc[]
