:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-client-path-variables-basic]]
=== Поддержка `path variables`

include::../_rest/___path-var-basic-rules.adoc[]

После создания классов моделей, необходимо создать обработчик HTTP запросов, использующий данную модель:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-path-variables/src/main/java/io/rxmicro/examples/rest/client/path/variables/RESTClient.java[tag=content,indent=0]
----
<1> При использовании `path variables` в моделях запроса обязательно использовать *все* `path variables` в URL Path.
_(На основании анализа URL Path с учетом значений всех `path variables` RxMicro формирует окончательный URL на который будет отправлен HTTP запрос.)_
<2> Для того чтобы параметр метода объявить как `path variable`, необходимо использовать аннотацию `@PathVariable`.
<3> С помощью аннотации `@PathVariable` возможно задать имя `path variable`, которое не соответствует имени параметра метода.

include::../___notes/model-class-intead-of-method-parameters-note.adoc[tags=**;!headers;!params;!all]

Несмотря на различные подходы к поддержке обработки `path variables`, с точки зрения окончательного URL два вышеуказанных обработчика абсолютно равнозначны:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-client-path-variables/src/test/java/io/rxmicro/examples/rest/client/path/variables/RESTClientTest.java[tag=content,indent=0]
----
<1> В результате выполнения обработчика HTTP запроса RxMicro формирует один и тотже URL: `/CATEGORY/TYPE-SUB-TYPE`

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}rest-client-path-variables
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

==== Поддерживаемые типы данных

include::../_rest/___path-variables-types.adoc[]
