:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

=== REST Client Implementation Requirements

==== REST Client Interface Requirements

REST Client is a Java interface that annotated by the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/RestClient.java[`@RestClient`^] annotation:

[source,java]
----
import java.util.concurrent.CompletableFuture;

import io.rxmicro.rest.client.RestClient;
import io.rxmicro.rest.method.GET;

@RestClient
public interface RESTClient {

    @GET("/")
    CompletableFuture<Model> getContent();
}
----

that must meet the following requirements:

. The interface must be a `public` one.
. The interface must be annotated by the required {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/RestClient.java[`@RestClient`^] annotation.
. The interface couldn't extend any other interfaces.
. The interface couldn't be a nested one.

<<<

==== HTTP Request Handler Requirements

HTTP request handler is a method, that must meet the following requirements:

. The method couldn't be a `private` one.
. The method couldn't be an `abstract` one.
. The method couldn't be a `static` one.
. The method must be annotated by *only one* of the following annotations:
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/GET.java[`GET`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/POST.java[`POST`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/PUT.java[`PUT`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/DELETE.java[`DELETE`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/PATCH.java[`PATCH`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/HEAD.java[`HEAD`^];
.. {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/method/OPTIONS.java[`OPTIONS`^].
. The method must return one of the following reactive types:
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture`^];
.. {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage`^];
.. {REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Completable.html[`Completable`^];
.. {RX-JAVA-DOC-ROOT-URL}io/reactivex/Single.html[`Single`^].
. If the method returns a reactive type, that this type must be parametrized by a HTTP response model type.
(The additional types such as `java.lang.Void` and `java.util.Optional` are supported also.
_(Read more: <<{core}#core-reactive-bussiness-process-reactive-class-mapping-table>>)_).

[IMPORTANT]
====
A REST client can contain `static`, `private` and `default` methods, but such methods couldn't be HTTP request handlers!
====

include::../_rest/___note-Flux-Flowable.adoc[]

:target: REST clients
include::../_rest/___requirements-param-types.adoc[]

include::../_rest/___note-reactive-libs.adoc[]
