:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

[[rest-client-rest-client-generator-config-section]]
=== Configuring the Code Generation Process

The RxMicro framework provides an option to configure the code generation process for REST client.
For this purpose, it is necessary to use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-client/src/main/java/io/rxmicro/rest/client/RestClientGeneratorConfig.java[`@RestClientGeneratorConfig`^]
annotation, that annotates the `module-info.java` module descriptor:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-generator/src/main/java/module-info.java[tags=content,indent=0]
----
<1> The `exchangeFormat` parameter allows You to specify a format for message exchange with a server. +
_(By default, it is used the message exchange format which added to the `module-info.java` descriptor.
If several modules supporting the message exchange format are added to the `module-info.java` descriptor, then using the `exchangeFormat`, You need to specify which module should be used for REST clients.)_
<2> The `generateRequestValidators` parameter allows enabling/disabling the option of generating HTTP request validators for all REST client methods in the project. +
_(The `DISABLED` value means that validators won't be generated by the `RxMicro Annotation Processor`.)_
<3> The `generateResponseValidators` parameter allows enabling/disabling the option of generating HTTP response validators for all REST client methods in the project. +
_(The `AUTO_DETECT` value means that validators will be generated only if the developer adds the <<{validation}#validation-section, `rxmicro.validation`>> module to the `module-info.java` descriptor.)_
<4> The `requestValidationMode` parameter specifies how the HTTP request parameters should be checked.

If the `requestValidationMode` parameter is equal to the `RETURN_ERROR_SIGNAL`, then error handling should be performed in reactive style:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-generator/src/main/java/io/rxmicro/examples/request/validaton/pseudo/code/BusinessService.java[tags=RETURN_ERROR_SIGNAL,indent=0]
----

If the `requestValidationMode` parameter is equal to the `THROW_EXCEPTION`, then it is necessary to catch the exception

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-generator/src/main/java/io/rxmicro/examples/request/validaton/pseudo/code/BusinessService.java[tags=THROW_EXCEPTION,indent=0]
----

[IMPORTANT]
====
The RxMicro team strong recommends using the `AUTO_DETECT` generate option always!
(This is default value for {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest-server/src/main/java/io/rxmicro/rest/client/RestClientGeneratorConfig.java[`@RestClientGeneratorConfig`^] annotation).

_(HTTP request validation can be useful for identifying errors in business task implementation algorithms.
For example, instead of returning an incorrect request model to a server, the REST client will throw an error.
This approach increases the speed of error search and debugging of the source code that performs the business task.)_

*FYI:* By default the request validators are generated but not invoked!
To activate the validation of requests it is necessary to set `enableAdditionalValidations` property:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/rest_client/ActivateRequestValidators.java[tags=content,indent=0]
----
<1> Enables the requests validators

Thus the RxMicro team recommends the following approach:

* Your project configuration must enable generation of validators for all possible model classes.
* Your `development` and `staging` environment must enable additional validation.
* Your `production` environment must disable additional validation!
====
