:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../

=== HTTP Request Handler Return Types

include::../_rest/___http-handler-return-types.adoc[]

<<<

==== Supported Return Result Types for HTTP Response without Body

The RxMicro framework supports the following return result types for an HTTP response without body:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-handlers/src/main/java/io/rxmicro/examples/rest/client/handlers/RestClientWithoutBody.java[tag=content,indent=0]
----
<1> The {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<Void>`^]
type is recommended when using the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^] library.
<2> Instead of the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<Void>`^] type, can also be used the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage<Void>`^] type.
<3> When using the {REACTOR-CORE-DOC-USER_GUIDE}[*Project Reactor*^] library, only the
{REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono<Void>`^] type can be used.
<4> When using the {RX-JAVA-USER-GUIDE}[*RxJava*^] library, only the
{RX-JAVA-DOC-ROOT-URL}io/reactivex/Completable.html[`Completable`^] type can be used.

All the above mentioned HTTP request handlers shouldn't throw any exceptions:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-handlers/src/test/java/io/rxmicro/examples/rest/client/handlers/RestClientWithoutBodyTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-client/rest-client-handlers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]

<<<

==== Supported Return Result Types for HTTP Response with Body

The RxMicro framework supports the following return result types for an HTTP response with body:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-handlers/src/main/java/io/rxmicro/examples/rest/client/handlers/RestClientWithBody.java[tag=content,indent=0]
----
<1> The {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<MODEL>`^]
type is recommended when using the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/package-summary.html[*java.util.concurrent*^] library.
<2> Instead of the {JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletableFuture.html[`CompletableFuture<MODEL>`^] type, can also be used the
{JDK-JAVA-BASE-DOC-ROOT-URL}java/util/concurrent/CompletionStage.html[`CompletionStage<MODEL>`^] type.
<3> When using the {REACTOR-CORE-DOC-USER_GUIDE}[*Project Reactor*^] library, only the
{REACTOR-CORE-DOC-ROOT-URL}reactor/core/publisher/Mono.html[`Mono<MODEL>`^] type can be used.
<4> When using the {RX-JAVA-USER-GUIDE}[*RxJava*^] library, only the
{RX-JAVA-DOC-ROOT-URL}io/reactivex/Single.html[`Single<MODEL>`^] type can be used.

include::../_rest/___note-reactive-parametrized-types.adoc[]

All of the above mentioned handlers return the `Response` class instance with the `Hello World!` message:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-rest-client/rest-client-handlers/src/test/java/io/rxmicro/examples/rest/client/handlers/RestClientWithBodyTest.java[tag=content,indent=0]
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-rest-client/rest-client-handlers
include::../___notes/full-source-code-of-example.adoc[]

include::../___notes/recompile-after-change.adoc[]
