:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

==== Базовые правила

The RxMicro framework поддерживает HTTP заголовки в моделях запроса и ответа:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-headers/src/main/java/io/rxmicro/examples/rest/controller/headers/model/Request.java[tag=content,indent=0]
----

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/rest-controller-headers/src/main/java/io/rxmicro/examples/rest/controller/headers/model/Response.java[tag=content,indent=0]
----
<1> Аннотация {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/HeaderMappingStrategy.java[`@HeaderMappingStrategy`^]
позволяет задать общие правила преобразования для всех имен заголовков из HTTP формата в Java и наоборот в текущем классе модели. +
_(По умолчанию используется стратегия
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-model/src/main/java/io/rxmicro/model/MappingStrategy.java#L59[`MappingStrategy.CAPITALIZE_WITH_HYPHEN`^].
В качестве базового имени используется имя поля, а затем применяя правила указанной стратегии, формируется имя HTTP заголовка.)_
<2> Для того, чтобы поле модели объявить как поле HTTP заголовка, необходимо использовать аннотацию
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Header.java[`@Header`^].
<3> С помощью аннотации {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/Header.java[`@Header`^]
возможно задать имя HTTP заголовка, которое не соответствует используемой стратегии, объявленной с помощью аннотации
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-rest/src/main/java/io/rxmicro/rest/HeaderMappingStrategy.java[`@HeaderMappingStrategy`^].

Для определения имени HTTP заголовка для указанного поля модели the RxMicro framework использует следующий алгоритм:

. Если поле аннотировано аннотацией `@Header` с явным указанием имени HTTP заголовка используется указанное имя;
. Если имя HTTP заголовка не указано в аннотации `@Header`, the RxMicro framework проверяет наличие аннотации `@HeaderMappingStrategy` над классом модели;
. Если класс модели аннотирован аннотацией `@HeaderMappingStrategy`, то используется указанная стратегия именования. +
_(В качестве базового имени используется имя поля, а затем применяя правила указанной стратегии, формируется имя HTTP заголовка.)_
. Если аннотация `@HeaderMappingStrategy` отсутствует в качестве имени HTTP заголовка используется имя поля класса модели.