:FRAGMENT_RELATIVE_DIR: ../../../
include::../../../___fragment-settings.adoc[]

[[core-config-order-settings]]
===== Изменение порядка считывания источников конфигураций

Для изменения порядка считывания конфигураций необходимо использовать метод:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L118[`Configs.Builder.withOrderedConfigLoadSources`^]:

[source,java]
----
public static void main(final String[] args) {
    new Configs.Builder()
            .withOrderedConfigLoadSources(
                    SEPARATE_CLASS_PATH_RESOURCE, // <1>
                    RXMICRO_CLASS_PATH_RESOURCE   // <2>
            )
            .build();
    start(MicroService.class, args);
}
----
<1> Сначала необходимо считывать конфигурацию с classpath ресурса `${name-space}.properties` (В нашем случае это `http-server.properties`)
<2> а затем уже с classpath ресурса `rxmicro.properties`.

Т.е. порядок считывания конфигурация с classpath ресурсов изменен по сравнению с
<<core-config-order-default-section, порядком по умолчанию>>.

При запуске микросервиса настройки с classpath ресурса `http-server.properties` будут перезаписаны настройками с classpath ресурса `rxmicro.properties`:

[source,text]
----
2020-01-11 16:52:26.797 [INFO] io.rxmicro.rest.server.netty.internal.component.NettyServer :
Server started at localhost:9090 using NETTY transport in 500 millis. # <1>
----
<1> HTTP сервер запустился на `localhost:9090`.

[IMPORTANT]
====
Метод
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L118[`Configs.Builder.withOrderedConfigLoadSources`^]
позволяет не только изменять порядок считывания источников конфигураций, но еще и активировать/деактивировать источники.

*В приведенном выше примере the RxMicro framework будет игнорировать любые источники конфигураций кроме classpath ресурсов!*
====

Метод
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L118[`Configs.Builder.withOrderedConfigLoadSources`^]
- универсальный.

The RxMicro framework также предоставляет другие дополнительные методы:

* {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L124[`Configs.Builder.withAllConfigLoadSources`^] - активации всех типов конфигурирования в порядке заданном перечислением:
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/ConfigLoadSource.java[`ConfigLoadSource`^]

* {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L129[`Configs.Builder.withDockerConfigLoadSources`^] - активация конфигураций с помощью аннотаций (которые позволяют переопределить значения по умолчанию) и с помощью переменных окружения.
Данная комбинация рекомендована для микросервисов работающих в https://www.docker.com/[docker^] контейнерах.

[TIP]
====
Метод
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L124[`Configs.Builder.withAllConfigLoadSources`^]
использовался для активации считывания конфигураций с properties файлов в подразделе <<core-config-properties-files-section>>.

Если планируется использовать только `properties` файлы, рекомендуется указывать только эти типы, исключив все остальные:

[source,java]
----
public static void main(final String[] args) {
    new Configs.Builder()
            .withOrderedConfigLoadSources(
                    RXMICRO_FILE_AT_THE_HOME_DIR,    // <1>
                    RXMICRO_FILE_AT_THE_CURRENT_DIR, // <2>
                    SEPARATE_FILE_AT_THE_HOME_DIR,   // <3>
                    SEPARATE_FILE_AT_THE_CURRENT_DIR // <4>
            )
            .build();
    start(MicroService.class, args);
}
----
<1> Активация считывания конфигурации с файла `$HOME/rxmicro.properties`.
<2> Активация считывания конфигурации с файла `rxmicro.properties` в текущей директории.
<3> Активация считывания конфигурации с файлов `$HOME/${name-space}.properties` (например `http-server.properties`).
<4> Активация считывания конфигурации с файлов `${name-space}.properties` (например `http-server.properties`) в текущей директории.

*Порядок считывания задается порядком аргументов метода
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L118[`Configs.Builder.withOrderedConfigLoadSources`^]*
====

[IMPORTANT]
====
*Если Вы точно знаете какие источники конфигурации должны использоваться микросервисом, ВСЕГДА указывайте их явно!*

*При таком подходе при старте микросервиса the RxMicro framework не будет пытаться искать несуществующие источники, тратя драгоценные микросекунды!*
====
