:FRAGMENT_RELATIVE_DIR:
include::___fragment-settings.adoc[]

*RxMicro* is a modern, JVM-based, full stack framework designed to develop distributed reactive applications that use a microservice architecture.

The RxMicro framework provides developers with a convenient tool to focus on writing an application business logic.
Meanwhile, routine and standard operations, which are the prerequisite for launching an application, are delegated to the framework.

The RxMicro framework is small and lightweight.
Even though the RxMicro framework is designed to create microservices, a developer can easily use separate *RxMicro* modules to develop any type of application using a reactive approach.

The RxMicro framework is a framework that uses https://en.wikipedia.org/wiki/Reactive_programming[reactive programming^] as the main and *only* approach when designing microservices.

*Any blocking operations are not supported!*

[IMPORTANT]
====
When developing a project using the RxMicro framework, use only *non-blocking drivers* to interact with databases, network connections and files.
Otherwise your project will work *too slow*, and won't be able to process a large number of clients' requests.
====

<<<

include::_introduction/features.adoc[]

<<<

include::_introduction/benefits.adoc[]

<<<

include::_introduction/requirements.adoc[]
