:FRAGMENT_RELATIVE_DIR:
include::___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../

Microservices - also known as the microservice architecture - is an architectural style that structures an application as a collection of services that are:

* Highly maintainable and testable.
* Loosely coupled.
* Independently deployable.
* Organized around business capabilities.
* Owned by a small team.

_(Read more at https://microservices.io/[`https://microservices.io/`^]...)_

Thus, a microservice project consists of several microservices.
Each microservice must fulfill only one business task.

Let's look at a microservice that displays the current date and time in UTC format:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/microservices/MicroService1.java[tags=content]
----

Does this microprogram constitute a microservice? +
Yes, since this microprogram fulfills a business task. +
Unfortunately, this program has a serious disadvantage: it interacts with clients through the console.
Therefore, *only a client's program with a console interface launched in a session of the current logged-in OS user will be able to interact with this microservice!*
This restriction makes it impossible to scale this microservice!

Can we improve this situation?
Yes, we can:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/microservices/MicroService2.java[tags=content]
----

This microservice uses a file system to interact with client's programs.
In this way, the only requirement for the client's program is to be run on the same computer on which the microservice is running.
The situation has improved, but it is still impossible to scale this microservice horizontally!

Can we improve this situation?
Yes, we can:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/microservices/MicroService3.java[tags=content]
----

Now, the microservice uses the network to interact with clients.
This implementation of the microservice is scalable as the microservice can now be run on several networked computers.
The situation has improved markedly, but there are problems with networking:

* Presence of firewalls.
* The need to create an interaction protocol.
* Independence from the programming language is an important criterion for the interaction protocol.

Can we improve this situation?
Yes, for this purpose You can use the HTTP protocol with the REST architecture style:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}code-fragments/src/main/java/io/rxmicro/examples/code/fragments/microservices/MicroService4.java[tags=content]
----

*That's why microservices are often referred to as REST-based microservices*

For simple tasks, the entire logic of the microservice can be found in one class, which is often called *microservice*.
If a microservice has to solve a complex task, then this microservice is divided into two logical components:

. REST controller, the main task of which is:
.. to accept HTTP requests;
.. to validate HTTP requests;
.. to convert HTTP requests into Java models;
.. to invoke request handlers;
.. once the response model is received, convert it to an HTTP response.
. Business service, the main task of which is:
.. if the task is of medium complexity, then independently calculate the result and return it to the REST controller;
.. if it is a high-complexity task, then decompose it into sub-tasks and delegate its execution to other microservices. After all sub-tasks have been completed, merge the result and return it to the REST controller.

Therefore, the following is implied in this guide:

. If You find the term *microservice*, it means *REST-based microservice*, unless stated otherwise!
. If You find the term *REST controller*, it means a logical component of the microservice that performs its direct functions!
