:FRAGMENT_RELATIVE_DIR:
include::___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../

Microservices - also known as the microservice architecture - is an architectural style that structures an application as a collection of services that are:

* Highly maintainable and testable.
* Loosely coupled.
* Independently deployable.
* Organized around business capabilities.
* Owned by a small team.

_(Read more at https://microservices.io/[`https://microservices.io/`^]...)_

Таким образом микросервисный проект состоит из нескольких микросервисов.
Каждый микросервис должен выполнять только одну бизнес задачу.

Давайте рассмотрим микросервис, который отображает текущую дату и время в UTC формате:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/microservices/src/main/java/io/rxmicro/examples/microservices/MicroService1.java[tags=content]
----

Является ли данная микропрограмма микросервисом? +
Да, ведь данная микропрограмма выполняет поставленную бизнес задачу. +
Однако данная программа содержит существенный недостаток - он взаимодействует с клиентами через консоль.
Таким образом *только клиентская программа с консольным интерфейсом, запущенная в сессии текущего залогиненного пользователя операционной системы сможет взаимодействовать с данным микросервисом!* Данное ограничение делает невозможным масшабирование данного микросервиса!

Можем ли мы улучшить данную ситуацию?
Да можем:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/microservices/src/main/java/io/rxmicro/examples/microservices/MicroService2.java[tags=content]
----

Данный микросервис использует файловую систему для взаимодействия с клиентскими программами.
Таким образом единственным требованием к клиентской программе является требование запуска на том же самом компьютере, на котором запущен микросервис.
Ситуация улучшилась, но горизонтальное масшабирование данного микросервиса все еще невозможно!

Можем ли мы улучшить данную ситуацию?
Да можем:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/microservices/src/main/java/io/rxmicro/examples/microservices/MicroService3.java[tags=content]
----

Теперь микросервис использует сеть для взаимодействия с клиентами.
Данная реализация микросервиса масштабируемая так как теперь микросервис может быть запущен на нескольких компьютерах, объединенных в сеть.
Ситуация заметно улучшилась, но возникает проблемы сетевого взаимодействия:

* Наличие firewalls.
* Необходимость создания протокола взаимодействия.
* Важным критерием для протокола взаимодействия является независимость от языка программирования.

Можем ли мы улучшить данную ситуацию?
Да, для этого можно использовать протокол HTTP и стиль архитектуры REST:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/microservices/src/main/java/io/rxmicro/examples/microservices/MicroService4.java[tags=content]
----

*Именно поэтому очень часто под микросервисами подразумевается именно REST-based микросервисы!*

Для простых задач вся логика работы микросервиса может находится в одном классе, который очень часто называется просто *микросервисом*.
Если микросервис должен решать сложную задачу, то тогда такой микросервис разбивается на два логических компонента:

. REST контроллер, основная задача которого:
.. принимать HTTP запросы;
.. выполнять валидацию HTTP запросов;
.. конвертировать HTTP запросы в Java модели;
.. вызывать обработчики полученных запросов;
.. получив модель ответа конвертировать, конвертировать ее в HTTP ответ.
. Бизнес сервис, основная задача которого:
.. если задача средней сложности, то самостоятельно вычислить результат и вернуть его REST контроллеру;
.. если задача большой сложности, то декомпозировать ее на подзадачи и передать на выполнение другим микросервисам, а после выполнения всех подзадач объединить результат и вернуть его REST контроллеру.

Поэтому в данном руководстве подразумевается:

. Если встречается термин *микросервис*, то подразумевается именно *REST-based микросервис*, если не указано обратное!
. Если встречается термин *REST контроллер*, то подразумевается логический компонент микросервиса, выполняющий свои непосредственные функции!

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}microservices
include::___notes/full-source-code-of-example.adoc[]
