:FRAGMENT_RELATIVE_DIR:
include::___fragment-settings.adoc[]

This section describes in detail the steps to be taken in order to create the REST-based microservice that returns the `"Hello World!"` message, using the RxMicro framework.

In order to successfully execute these instructions, You need to install
https://openjdk.java.net/projects/jdk/11/[JDK 11 LTS^] or higher on Your computer.
For Your convenience it is also recommended to use a modern IDE, for example https://www.jetbrains.com/idea/[IntelliJ IDEA^].

[NOTE]
====
The features of the *IntelliJ IDEA Community Edition* version are enough for a complete and convenient work on a project that uses the RxMicro framework.
====

The RxMicro framework consists of several dozens of modules, so for convenient handling it is recommended to install https://maven.apache.org/[`maven`^] on Your computer.

[IMPORTANT]
====
Any modern IDE for Java (`IntelliJ IDEA, Eclipse, NetBeans`) already contains a built-in `maven`, so there is no need in its additional installation on Your computer.

To run `maven` commands, You can use Your IDE instead of the terminal.
====

include::_quick-start/create-simple-project.adoc[]

<<<

include::_quick-start/maven-config.adoc[]

<<<

include::_quick-start/java-source-code.adoc[]

<<<

include::_quick-start/compiling.adoc[]

<<<

include::_quick-start/run.adoc[]

<<<

include::_quick-start/verify.adoc[]

<<<

include::_quick-start/tests.adoc[]

<<<

include::_quick-start/quck-start-project.adoc[]
