:FRAGMENT_RELATIVE_DIR:
include::___fragment-settings.adoc[]

REST Client is an interface that contains at least one declarative HTTP request handler.

To create REST clients, the RxMicro framework provides the following modules:

* The {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest[`rxmicro.rest`^] is a basic module that defines basic `RxMicro Annotations`, required when using the
https://en.wikipedia.org/wiki/Representational_state_transfer[`REST`^] architecture of building program systems;
* The {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-client[`rxmicro.rest.client`^] is a basic module used to create and run REST clients;
* The {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-client-jdk[`rxmicro.rest.client.jdk`^] is an HTTP client implementation module based on https://openjdk.java.net/groups/net/httpclient/intro.html[`Java HTTP Client`^];
* The {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-client-exchange-json[`rxmicro.rest.client.exchange.json`^] is a module for converting Java models to https://www.json.org/[`JSON`^] format and vice versa;

[NOTE]
====
Due to transit dependencies only two modules usually need to be added to a project:
{RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-client-jdk[`rxmicro.rest.client.jdk`^] and {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-client-exchange-json[`rxmicro.rest.client.exchange.json`^]. +
_(All other modules are automatically added to the project!)_
====

<<<

include::_rest-client/requirements.adoc[]

<<<

include::_rest-client/annotations.adoc[]

<<<

include::_rest-client/return-types.adoc[]

<<<

include::_rest-client/http-headers.adoc[]

<<<

include::_rest-client/http-params.adoc[]

<<<

include::_rest-client/path-variables.adoc[]

<<<

include::_rest-client/internal.adoc[]

<<<

include::_rest-client/versioning.adoc[]

<<<

include::_rest-client/base-url-path.adoc[]

<<<

include::_rest-client/expressions.adoc[]

<<<

include::_rest-controller/request-id.adoc[]

<<<

include::_rest-client/partial-implementation.adoc[]

<<<

include::_rest-client/rest-client-generator-config.adoc[]
