:FRAGMENT_RELATIVE_DIR:
include::___fragment-settings.adoc[]

REST Controller is a class that contains at least one declarative HTTP request handler.

Each REST-based microservice project must contain at least one REST Controller. +
_(The REST Controller is the entry point for the client.)_

To create REST controllers, the RxMicro framework provides the following modules:

* The {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest[`rxmicro.rest`^] is a basic module that defines basic `RxMicro Annotations`, required when using the
https://en.wikipedia.org/wiki/Representational_state_transfer[`REST`^] architecture of building program systems;
* The {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-server[`rxmicro.rest.server`^] is a basic HTTP server module used to create REST controllers and run REST-based microservices;
* The {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-server-netty[`rxmicro.rest.server.netty`^] is an HTTP server implementation module based on https://netty.io/[`Netty`^];
* The {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-server-exchange-json[`rxmicro.rest.server.exchange.json`^] is a module for converting Java models to https://www.json.org/[`JSON`^] format and vice versa;

[NOTE]
====
Due to transit dependencies only two modules usually need to be added to a project:
{RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-server-netty[`rxmicro.rest.server.netty`^] and {RX-MICRO-SRC-ROOT-TREE-URL}rxmicro-rest-server-exchange-json[`rxmicro.rest.server.exchange.json`^]. +
_(All other modules are automatically added to the project!)_
====

<<<

include::_rest-controller/requirements.adoc[]

<<<

include::_rest-controller/annotations.adoc[]

<<<

include::_rest-controller/return-types.adoc[]

<<<

include::_rest-controller/routing.adoc[]

<<<

include::_rest-controller/not-found.adoc[]

<<<

include::_rest-controller/error.adoc[]

<<<

include::_rest-controller/set-status-code.adoc[]

<<<

include::_rest-controller/redirect.adoc[]

<<<

include::_rest-controller/http-headers.adoc[]

<<<

include::_rest-controller/http-params.adoc[]

<<<

include::_rest-controller/path-variables.adoc[]

<<<

include::_rest-controller/internal.adoc[]

<<<

include::_rest-controller/versioning.adoc[]

<<<

include::_rest-controller/base-url-path.adoc[]

<<<

include::_rest-controller/cors.adoc[]

<<<

include::_rest-controller/request-id.adoc[]

<<<

include::_rest-controller/rest-server-generator-config.adoc[]
