:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

=== Проект на Github

Проект REST-based микросервиса `HelloWorldMicroService` доступен по ссылке:

[.example-code-link]
{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}quick-start[`{RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}quick-start`^].

[IMPORTANT]
====
Конфигурационный файл `pom.xml` является эталонной конфигурацией и может быть скопирован в Ваш следующий проект, использующий the RxMicro framework.

*НЕ ЗАБУДЬТЕ только удалить ссылку на родительский проект*:

[source,xml]
----
<parent>
    <artifactId>examples</artifactId>
    <groupId>io.rxmicro</groupId>
    <version>0.4</version>
</parent>
----

*и добавить секцию `properties` с описанием версий используемых библиотек*:

[source,xml,subs="attributes+"]
----
<properties>
    <rxmicro.version>{RXMICRO-VERSION}</rxmicro.version> <!--1-->

    <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version> <!--2-->
    <maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version> <!--3-->
    <maven-dependency-plugin.version>3.1.1</maven-dependency-plugin.version> <!--4-->
</properties>
----

<1> {MAVEN-REPO-SEARCH-ROOT}io.rxmicro/rxmicro[Последняя стабильная версия of the RxMicro framework^].
<2> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-compiler-plugin[Последняя стабильная версия `maven-compiler-plugin`^].
<3> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-surefire-plugin[Последняя стабильная версия `maven-surefire-plugin`^].
<4> {MAVEN-REPO-SEARCH-ROOT}org.apache.maven.plugins/maven-dependency-plugin[Последняя стабильная версия `maven-dependency-plugin`^].
====
