:FRAGMENT_RELATIVE_DIR: ../
include::../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

=== Автоматизированный тест

The RxMicro framework предоставляет модули для эффективного написания <<{testing}#tesing-section,любых видов тестов>>.
Из всех поддерживаемых видов тестов, для текущего проекта необходим тест REST-based микросервиса.

==== Конфигурирование проекта

Перед написанием теста REST-based микросервиса, необходимо сконфигурировать `pom.xml` Вашего проекта, выполнив следующие шаги:

. Добавить необходимые зависимости в `pom.xml`.
. Сконфигурировать `maven-compiler-plugin`.
. Сконфигурировать `maven-surefire-plugin`.

===== Добавление необходимых зависимостей

Перед использованием RxMicro модулей для тестирования, необходимо в проект добавить следующие зависимости:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-test-junit</artifactId> <!--1-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-http-client-jdk</artifactId> <!--2-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.rxmicro</groupId>
        <artifactId>rxmicro-rest-client-exchange-json</artifactId> <!--3-->
        <version>${rxmicro.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
----
<1> Библиотека модульного тестирования на базе фреймворка https://junit.org/junit5/[JUnit 5^]
<2> Библиотека http клиента на базе JDK модуля https://developer.oracle.com/java/jdk-http-client.html[`java.net.http`^];
<3> Библиотека конвертации Java модели в https://www.json.org/[JSON^] формат и наоборот на стороне HTTP клиента;

Процесс тестирования REST-based микросервиса заключается в том, что в процессе теста запускается REST-based микросервис и с помощью HTTP клиента отправляется запрос на него. +
_(Именно поэтому в `maven` зависимости необходимо подключить библиотеку HTTP клиента (`rxmicro-http-client-jdk`) и библиотеку поддерживающую https://www.json.org/[JSON^]
формат на стороне HTTP клиента (`rxmicro-rest-client-exchange-json`))_. +
После получения ответа от микросервиса, данный ответ сравнивается с ожидаемым ответом.

===== Конфигурирование `maven-compiler-plugin`

Так как the RxMicro framework использует {JDK-JAVA-COMPILER-DOC-ROOT-URL}javax/annotation/processing/Processor.html[Java annotation processors^], необходимо настроить `maven-compiler-plugin`:

[source,xml]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <release>11</release>
        <annotationProcessorPaths>
            <annotationProcessorPath>
                <groupId>io.rxmicro</groupId>
                <artifactId>rxmicro-annotation-processor</artifactId>
                <version>${rxmicro.version}</version>
            </annotationProcessorPath>
        </annotationProcessorPaths>
    </configuration>
    <executions>
        <execution>
            <id>source-compile</id>
            <goals>
                <goal>compile</goal>
            </goals>
            <configuration>
                <annotationProcessors>
                    <annotationProcessor>
            io.rxmicro.annotation.processor.RxMicroAnnotationProcessor
                    </annotationProcessor>
                </annotationProcessors>
                <generatedSourcesDirectory>
                    ${project.build.directory}/generated-sources/
                </generatedSourcesDirectory>
            </configuration>
        </execution>
        <execution>
            <id>test-compile</id> <!--1-->
            <goals>
                <goal>testCompile</goal>
            </goals>
            <configuration>
                <annotationProcessors>
                    <annotationProcessor>
            io.rxmicro.annotation.processor.RxMicroTestsAnnotationProcessor <!--2-->
                    </annotationProcessor>
                </annotationProcessors>
                <generatedTestSourcesDirectory>
                    ${project.build.directory}/generated-test-sources/ <!--3-->
                </generatedTestSourcesDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
----
<1> Для тестов необходима отдельная конфигурация, поэтому необходимо добавить новый `execution`.
<2> Класс процессора аннотаций, который обрабатывает тестовую конфигурацию.
<3> Местоположение генерируемых Java классов процессором тестовых аннотаций.

[NOTE]
====
Для получения дополнительных знаний о том, как работает процессор аннотаций для тестового окружения, рекомендуется перейти в раздел: <<{testing}#testing-how-it-works-section>>.
====

===== Конфигурирование `maven-surefire-plugin`

include::../___shared/maven-surefire-plugin-configuration.adoc[]

==== Создание теста

Тест REST-based микросервиса - один класс, содержащий один тестовый метод:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/quick-start/src/test/java/io/rxmicro/examples/quick/start/HelloWorldMicroServiceTest.java[tag=content]
----
<1> RxMicro тестовая аннотация, указывающая какой микросервис необходимо запустить для теста.
<2> {RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test/src/main/java/io/rxmicro/test/BlockingHttpClient.java[`BlockingHttpClient`^] - базовый интерфейс HTTP клиента, разработанный для использования в тестах.
Данный интерфейс позволяет выполнять *блокирующие* вызовы к микросервису по протоколу `HTTP`.
Данное поле инициализируется автоматически при выполнении теста с помощью `reflection` и после инициализации ссылается на тестовый HTTP сервер, который был запущен для теста автоматически.
<3> Блокирующий запрос на микросервис.
<4> Сравнение содержимого HTTP воду с предопределенным значением.
<5> Сравнение HTTP кода состояния.

[NOTE]
====
Для низкоуровневой и эффективной работы с JSON форматом, RxMicro предоставляет отдельный модуль `rxmicro.json`.

Для получения общего представления о возможностях данного модуля, которые необходимы при написании тестов, рекомендуется перейти в раздел: <<{core}#core-rx-micro-json-section>>.
====

*В микросервисных тестах рекомендуется сравнивать тело HTTP запроса перед сравнением HTTP статуса в том случае, когда микросервис всегда возвращает текстовое сообщение о возникшей ошибке!
(При таком подходе легче будет понять в чем ошибка, если она возникла во время тестирования.)*

*Если микросервис возвращает ТОЛЬКО статус при возникновении ошибки, то сравнение HTTP тела необходимо пропустить!*

[NOTE]
====
Для получения дополнительных знаний о том, как тестировать REST-based микросервисы, рекомендуется перейти в раздел: <<{testing}#testing-rest-based-microservice-tests-section>>.
====

==== Запуск теста

Для запуска тестов необходимо выполнить команду:

[source,txt,subs="verbatim,quotes"]
----
*mvn* clean test
----

После запуска в консоли отобразится следующая информация:

[source,text,subs="verbatim,quotes"]
----
...
[INFO] Compiling 3 source files to ~/examples/quick-start/target/classes
[INFO]
[INFO] -------------------------------------------------------
[INFO]  *RX-MICRO ANNOTATIONS PROCESSING* # <1>
[INFO] -------------------------------------------------------
[INFO] Current environment context is:
  Current module:
    `examples.quick.start`
  Available RxMicro modules:
    ...
  Include packages: <none>
  Exclude packages: <none>
[INFO] Found the following REST controllers:
  GET / -> io.rxmicro.examples.quick.start.HelloWorldMicroService.sayHelloWorld()
[INFO] Generating java classes...
[INFO] All java classes generated successful in 0.398 seconds. # <2>
[INFO] -------------------------------------------------------
[INFO] Annotations processing completed successful.
...
[INFO] Compiling 1 source file to ~/examples/quick-start/target/test-classes
[INFO]
[INFO] -------------------------------------------------------
[INFO]  *RX-MICRO TEST ANNOTATIONS PROCESSING* # <3>
[INFO] -------------------------------------------------------
[INFO] Generating java classes...
[INFO] All java classes generated successful in 0.366 seconds. # <4>
[INFO] -------------------------------------------------------
[INFO] Annotations processing completed successful.
...
[INFO] -------------------------------------------------------
[INFO]  *T E S T S*
[INFO] -------------------------------------------------------
*opens* rxmicro.runtime/io.rxmicro.runtime.local to ALL-UNNAMED # <5>
*opens* rxmicro.runtime/io.rxmicro.runtime.local.error to ALL-UNNAMED # <5>
*opens* rxmicro.runtime/io.rxmicro.runtime.local.provider to ALL-UNNAMED # <5>
*opens* rxmicro.rest.server/io.rxmicro.rest.server.local.model to ALL-UNNAMED # <5>
*opens* rxmicro.rest.server/io.rxmicro.rest.server.local.component to ALL-UNNAMED # <5>
*opens* rxmicro.rest.server/io.rxmicro.rest.server.local.component.impl to ALL-UNNAMED
*opens* examples.quick.start/io.rxmicro.examples.quick.start to ALL-UNNAMED # <5>
*opens* examples.quick.start/rxmicro to ALL-UNNAMED # <5>
[INFO] Running *io.rxmicro.examples.quick.start.HelloWorldMicroServiceTest* # <6>
[INFO] i.r.r.s.n.i.c.NettyServer : Server started at 0.0.0.0:45853 using NETTY transport. # <7>
[INFO] i.r.h.c.j.i.JdkHttpClient : JdkHttpClient released # <8>
[INFO] i.r.r.s.n.i.c.NettyServer : Retrieved shutdown request ...
[INFO] i.r.r.s.n.i.c.NettyServer : Server stopped # <9>
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0 # <10>
[INFO]
[INFO] *BUILD SUCCESS*
[INFO] -------------------------------------------------------
----

<1> Запуск `RxMicro Annotation Processor`.
<2> `RxMicro Annotation Processor` успешно отработал.
<3> Запуск `RxMicro Tests Annotation Processor`.
<4> `RxMicro Tests Annotation Processor` успешно отработал.
<5> Для тестовой конфигурации автоматически добавились недостающие экспорты, используя возможности класса {JDK-JAVA-BASE-DOC-ROOT-URL}java/lang/Module.html[`java.lang.Module`^].
<6> Запуск теста REST-based микросервиса.
<7> Автоматически запустился HTTP сервер на случайном свободном порту.
<8> Ресурсы компонента `BlockingHttpClient` были освобождены.
<9> HTTP сервер успешно остановился.

[NOTE]
====
Для получения дополнительных знаний о том, как работает процессор аннотаций для тестового окружения, рекомендуется перейти в раздел: <<{testing}#testing-how-it-works-section>>.
====
