:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

==== Basic Structure of the Config Module

Each class that extends the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Config.java[`Config`^]
abstract class is a configuration class.

Each configuration class defines its own namespace.
Each namespace clearly defines the corresponding configuration class.
The namespace is necessary to set the settings of the configuration class fields in text form.
(_Further details will be described below._)

To work with configurations, the RxMicro framework provides the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java[`Configs`^] configuration manager.

To read the current settings, You must use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L98[`Configs.getConfig`^] method:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/config-basic/src/main/java/io/rxmicro/examples/config/basic/ReadConfigMicroService.java[tag=content,indent=0]
----
<1> Getting the current HTTP server configuration using the `Configs.getConfig` static method.

To change the standard configuration settings, You must use the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Configs.java#L135[`Configs.Builder`^] class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/config-basic/src/main/java/io/rxmicro/examples/config/basic/CustomizeConfigMicroService.java[tag=content,indent=0]
----
<1> Setting the HTTP server custom port.
<2> Creating the configuration manager object.
<3> REST-based microservice should be started after configuration manager settings, otherwise changes will not take effect.

[IMPORTANT]
====
Each subsequent invocation of the `Configs.Builder.build()` method overrides all configuration manager settings.
_(In any microservice project there is only one configuration manager object!)_

It means that if the developer creates several `Configs.Builder` instances, it will be the last invocation of the `build`
method that matters, the others will be ignored.
====

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-common/config-basic
include::../../___notes/full-source-code-of-example.adoc[]

include::../../___notes/recompile-after-change.adoc[]

[NOTE]
====
Settings customization via the `Configs.Builder.build()` is one of the types of configuration.
This type of configuration is called <<core-config-java-classes-section,configuration using Java classes>>.
====
