:FRAGMENT_RELATIVE_DIR: ../../
include::../../___fragment-settings.adoc[]

:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../

==== User Defined Configurations

The developer can use the configuration module for custom configurations.

To do this, it is necessary to create a separate class:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/config-custom/src/main/java/io/rxmicro/examples/config/custom/BusinessServiceConfig.java[tag=content,indent=0]
----

[IMPORTANT]
====
The custom configuration class must meet the following requirements:

. The class must be public.
. The class must contain a public constructor without parameters.
. The class must extend the
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-config/src/main/java/io/rxmicro/config/Config.java[`Config`^] abstract class.
. To set property values, the class must contain https://www.w3schools.com/java/java_encapsulation.asp[`setters`^]. +
_(Only those fields that contain `setters` can be initialized!)_
====

Since this class will be created and initialized by the classes from `rxmicro.runtime` and `rxmicro.config` modules automatically, it is necessary to export the package to these modules in the `module-info.java` descriptor. +
_(These are the https://www.oracle.com/corporate/features/understanding-java-9-modules.html[JPMS^] requirements.)_

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/config-custom/src/main/java/module-info.java[tag=content,indent=0]
----
<1> Allow the `rxmicro.runtime` module access to public classes from the `io.rxmicro.example.config.custom` package.
<2> Allow the `rxmicro.config` module access to public classes from the `io.rxmicro.example.config.custom` package.

After these changes, a class of custom configurations is available for use:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/group-common/config-custom/src/main/java/io/rxmicro/examples/config/custom/MicroService.java[tag=content,indent=0]
----

The `production` flag can now be set using any type of configuration, for example using the classpath of the `business-service.properties` resource:

[source,properties]
----
production=false
----

:link: {RX-MICRO-EXAMPLES-SRC-ROOT-TREE-URL}group-common/config-custom
include::../../___notes/full-source-code-of-example.adoc[]

include::../../___notes/recompile-after-change.adoc[]
