:RX-MICRO-USAGE-ROOT-LOCAL-PATH: ../../../../../../../../

==== Порядок выполнения пользовательского и RxMicro кода

Для эффективного написания тестов REST-based микросервиса, необходимо знать порядок выполнения пользовательского и RxMicro кода.

При тестировании REST-based микросервиса, используя следующий тест:

[source,java]
----
include::{RX-MICRO-USAGE-ROOT-LOCAL-PATH}examples/testing-microservice-order/src/test/java/io/rxmicro/examples/testing/microservice/order/MicroServiceTest.java[tag=content,indent=0]
----

порядок выполнения будет следующим:

[source,text]
----
RX-MICRO: Test class validated.
RX-MICRO: HTTP server started without any REST-based microservices using random free port.
RX-MICRO: Blocking HTTP client created and connected to the started HTTP server.
USER-TEST: '@BeforeAll' method invoked.

USER-TEST: new instance of the REST-based microservice test class created.
MOCKITO: All mocks created and injected.
RX-MICRO: Alternatives of the RxMicro components registered in the RxMicro runtime containers.
RX-MICRO: Blocking HTTP client injected to the instance of the test class.
RX-MICRO: SystemOut instance created and injected to the instance of the test class.
USER-TEST: '@BeforeEach' method invoked.
USER-TEST: 'beforeEachPreparer1' method invoked.
RX-MICRO: Current REST-based microservice instance created and registered in the HTTP server.
RX-MICRO: Alternatives of the user components injected to the REST-based microservice instance.
USER-TEST: 'test1()' method invoked.
USER-TEST: '@AfterEach' method invoked.
RX-MICRO: All registered alternatives removed from the RxMicro runtime containers.
RX-MICRO: Current REST-based microservice instance unregistered from the HTTP server.
RX-MICRO: System.out reset.
MOCKITO: All mocks destroyed.

USER-TEST: new instance of the REST-based microservice test class created.
MOCKITO: All mocks created and injected.
RX-MICRO: Alternatives of the RxMicro components registered in the RxMicro runtime containers.
RX-MICRO: Blocking HTTP client injected to the instance of the test class.
RX-MICRO: SystemOut instance created and injected to the instance of the test class.
USER-TEST: '@BeforeEach' method invoked.
USER-TEST: 'beforeEachPreparer2' method invoked.
RX-MICRO: Current REST-based microservice instance created and registered in the HTTP server.
RX-MICRO: Alternatives of the user components injected to the REST-based microservice instance.
USER-TEST: 'test2()' method invoked.
USER-TEST: '@AfterEach' method invoked.
RX-MICRO: All registered alternatives removed from the RxMicro runtime containers.
RX-MICRO: Current REST-based microservice instance unregistered from the HTTP server.
RX-MICRO: System.out reset.
MOCKITO: All mocks destroyed.

USER-TEST: '@AfterAll' method invoked.
RX-MICRO: Blocking HTTP client released.
RX-MICRO: HTTP server stopped.

----

В приведенном выше порядке выполнения пользовательского и RxMicro кода подразумеваются следующие уточнения:

. Префик `MOCKITO` означает, что действие активируется аннотацией
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-mockito-junit/src/main/java/io/rxmicro/test/mockito/junit/InitMocks.java[`@InitMocks`^].
. Префик `RX-MICRO` означает, что действие активируется аннотацией
{RX-MICRO-SRC-ROOT-BLOB-URL}rxmicro-test-junit/src/main/java/io/rxmicro/test/junit/RxMicroRestBasedMicroServiceTest.java[`@RxMicroRestBasedMicroServiceTest`^].
. Префик `USER-TEST` означает, что на данном этапе вызывается пользовательский метод из класса `MicroServiceTest`.
