name: Update User Guide

on:
  push:
    branches: [ master ]
    paths:
      - 'documentation/**'
      - 'examples/documentation-asciidoctor-custom-sections/**'
      - 'examples/documentation-asciidoctor-echo/**'
      - 'examples/documentation-asciidoctor-errors/**'
      - 'examples/documentation-asciidoctor-metadata-annotations/**'
      - 'examples/documentation-asciidoctor-metadata-pomxml/**'
      - 'examples/documentation-asciidoctor-quick-start/**'
      - 'examples/documentation-asciidoctor-validation/**'

jobs:
  update-user-guide:
    name: Update User Guide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: rxmicro-doc-maven-${{ runner.os }}-cache
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install the Last Version of RxMicro
        run: |
          git clone https://github.com/rxmicro/rxmicro
          cd rxmicro/
          mvn -DskipTests -B install --file pom.xml

      - name: Recompile Examples of Project Documentations
        run : |
          cd rxmicro/
          LATEST_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          cd ../
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file examples/documentation-asciidoctor-custom-sections/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file examples/documentation-asciidoctor-echo/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file examples/documentation-asciidoctor-errors/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file examples/documentation-asciidoctor-quick-start/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file examples/documentation-asciidoctor-validation/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file examples/documentation-asciidoctor-metadata-annotations/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file examples/documentation-asciidoctor-metadata-pomxml/pom.xml

      - name: Build User Guide
        run: |
          cd rxmicro/
          LATEST_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          cd ../
          cd documentation/
          mvn -Drxmicro.version=$LATEST_VERSION -B verify --file pom.xml

      - name: Clone `rxmicro.github.io`
        run: git clone https://github.com/rxmicro/rxmicro.github.io

      - name: Update `rxmicro.github.io` Repository
        run: |
          CURRENT_DIR=$(pwd)
          rm -R $CURRENT_DIR/rxmicro.github.io/doc/latest/
          mv -v $CURRENT_DIR/documentation/target/generated-docs/images $CURRENT_DIR/rxmicro.github.io/doc/latest
          mv -v $CURRENT_DIR/documentation/target/generated-docs/project-documentation-examples $CURRENT_DIR/rxmicro.github.io/doc/latest
          mv -v $CURRENT_DIR/documentation/target/generated-docs/ru $CURRENT_DIR/rxmicro.github.io/doc/latest

      - name: Commit and Push Changes to `rxmicro.github.io` Repository
        run: |
          cd rxmicro.github.io
          git config user.email "rxmicro.io@gmail.com"
          git config user.name "rxmicro"
          git add --all
          git commit -m "Update user guide. Commit#${{ github.sha }}"

          git remote set-url origin https://rxmicro:${{ secrets.AUTO_UPDATE_RX_MICRO_IO_DOC_ACCESS_TOKEN }}@github.com/rxmicro/rxmicro.github.io.git
          git push origin master
